export type LearningLevel = 'basic' | 'extended'
export type BlockType = 'paragraph' | 'heading' | 'formula' | 'example' | 'warning' | 'tip' | 'table' | 'diagram' | 'interactive_question' | 'quiz' | 'summary'
export interface CurriculumSkill { slug: string; name: string; description: string; level: LearningLevel; mastery: number }
export interface CurriculumLesson { slug: string; title: string; duration: number; difficulty: 1 | 2 | 3 | 4 | 5; objectives: string[]; skills: CurriculumSkill[]; blocks: { type: BlockType; title?: string; body: string; formula?: string }[] }
export interface CurriculumTopic { slug: string; title: string; description: string; level: LearningLevel; mastery: number; lessons: CurriculumLesson[] }
const lesson = (slug: string, title: string, skills: string[], level: LearningLevel, difficulty: 1|2|3|4|5 = 2): CurriculumLesson => ({ slug, title, duration: 18, difficulty, objectives: [`Zrozumiesz pojęcie: ${title}`, 'Rozwiążesz zadania od podstaw do poziomu maturalnego'], skills: skills.map((name, i) => ({ slug: `${slug}-${i}`, name, description: `Opanuj umiejętność: ${name}.`, level, mastery: 0 })), blocks: [{ type: 'paragraph', title: 'Cel lekcji', body: `W tej lekcji krok po kroku poznasz temat „${title}”. Najpierw zbudujemy intuicję, potem przejdziemy do procedury i zadań maturalnych.` }, { type: 'formula', title: 'Najważniejsza reguła', body: 'Zapisz regułę własnymi słowami, zanim przejdziesz do ćwiczeń.', formula: 'f(x)=ax^2+bx+c' }, { type: 'example', title: 'Przykład standardowy', body: 'Przeanalizuj dane, wybierz właściwą definicję, wykonaj obliczenia i sprawdź wynik w kontekście zadania.' }, { type: 'warning', title: 'Uważaj', body: 'Nie pomijaj dziedziny i warunków stosowania wzoru.' }, { type: 'interactive_question', title: 'Sprawdź się', body: 'Jaki jest pierwszy krok rozwiązania tego typu zadania?' }, { type: 'summary', title: 'Podsumowanie', body: 'Znasz definicję, procedurę i typowe pułapki. Następny krok to trening mieszany.' }] })
const topics = (level: LearningLevel, items: Array<[string, string, string[]]>): CurriculumTopic[] => items.map(([slug, title, skills]) => ({ slug, title, level, mastery: 0, description: `Kompletny moduł ${title}: teoria, przykłady, praktyka, błędy i test opanowania.`, lessons: [lesson(`${slug}-fundamenty`, `${title} — fundamenty`, skills.slice(0, 3), level, 1), lesson(`${slug}-zadania`, `${title} — zadania standardowe`, skills, level, 3), lesson(`${slug}-matura`, `${title} — zadania maturalne`, skills, level, 4)] }))
const basic = topics('basic', [['realne','Liczby rzeczywiste',['działania i kolejność','potęgi i pierwiastki','przedziały']], ['algebra','Wyrażenia algebraiczne',['redukcja wyrazów','wzory skróconego mnożenia','procenty']], ['rownania','Równania i nierówności',['równania liniowe','układy równań','nierówności']], ['funkcje','Funkcje',['dziedzina i zbiór wartości','odczyt z wykresu','przesunięcia wykresu']], ['kwadratowa','Funkcja kwadratowa',['delta i miejsca zerowe','wierzchołek','optymalizacja']], ['wielomiany','Wielomiany',['dzielenie wielomianów','pierwiastki','twierdzenie Bezout']], ['wymierne','Funkcje wymierne',['dziedzina','asymptoty','równania wymierne']], ['ciagi','Ciągi',['arytmetyczny','geometryczny','suma wyrazów']], ['trygonometria','Trygonometria',['sinus i cosinus','tożsamości','równania trygonometryczne']], ['planimetria','Planimetria',['trójkąty','okręgi','pola figur']], ['geometria','Geometria analityczna',['prosta','odległość','okrąg']], ['kombinatoryka','Kombinatoryka',['reguła mnożenia','permutacje','kombinacje']], ['prawdopodobienstwo','Prawdopodobieństwo',['zdarzenia','drzewa','prawdopodobieństwo warunkowe']], ['statystyka','Statystyka',['średnia i mediana','odchylenie','interpretacja danych']], ['stereometria','Geometria przestrzenna',['graniastosłupy','ostrosłupy','bryły obrotowe']], ['zastosowania','Zastosowania matematyki',['modelowanie','procent składany','zadania tekstowe']]])
const extended = topics('extended', [['granice','Granice i ciągłość',['granice ciągów','granice funkcji','ciągłość']], ['pochodne','Pochodne',['definicja pochodnej','reguły różniczkowania','interpretacja geometryczna']], ['optymalizacja','Optymalizacja',['monotoniczność','ekstrema','zadania optymalizacyjne']], ['parametry','Równania z parametrem',['liczba rozwiązań','parametr w funkcji','warunki brzegowe']], ['dowody','Dowodzenie',['indukcja','nierówności','dowody geometryczne']]])
export const curriculum: CurriculumTopic[] = [...basic, ...extended]
export const getCurriculum = (level?: LearningLevel) => level ? curriculum.filter((topic) => topic.level === level) : curriculum
export const getTopic = (slug: string) => curriculum.find((topic) => topic.slug === slug)
