'use client'

import { createClient } from '@/lib/supabase/client'

export type Exam = { id: string; title: string; year: number; level: 'basic' | 'extended'; durationMinutes: number; totalPoints: number; description: string | null; source: string | null; questionCount: number; attempts: ExamAttempt[]; inProgress?: ExamAttempt }
export type ExamQuestion = { id: string; questionId: string; number: number; points: number; questionText: string; questionType: string; topicId: string; topicName?: string; correctAnswer?: string }
export type ExamAttempt = { id: string; examId: string; startedAt: string; finishedAt: string | null; timeRemainingSeconds: number; status: string; totalPoints: number; earnedPoints: number; percentage: number }
export type ExamAnswer = { questionId: string; answer: string; flagged: boolean; savedAt: string }

async function userId() { const supabase = createClient(); if (!supabase) return null; const { data } = await supabase.auth.getUser(); return data.user?.id ?? null }

export async function listExams(filters?: { query?: string; level?: string; year?: string; status?: string }) : Promise<Exam[]> {
  const supabase = createClient(); const uid = await userId(); if (!supabase) return []
  let query = supabase.from('exams').select('id,title,year,level,duration_minutes,total_points,description,source,exam_questions(id)').eq('published', true).order('year', { ascending: false })
  if (filters?.level && filters.level !== 'all') query = query.eq('level', filters.level)
  if (filters?.year && filters.year !== 'all') query = query.eq('year', Number(filters.year))
  const { data, error } = await query; if (error) throw error
  const ids = (data ?? []).map((x: any) => x.id)
  const { data: attempts } = ids.length && uid ? await supabase.from('exam_attempts').select('*').eq('user_id', uid).in('exam_id', ids).order('created_at', { ascending: false }) : { data: [] as any[] }
  return (data ?? []).map((x: any) => { const rows = (attempts ?? []).filter((a: any) => a.exam_id === x.id); const inProgress = rows.find((a: any) => a.status === 'in_progress'); return { id: x.id, title: x.title, year: x.year, level: x.level, durationMinutes: x.duration_minutes, totalPoints: x.total_points, description: x.description, source: x.source, questionCount: x.exam_questions?.length ?? 0, attempts: rows.map(mapAttempt), inProgress: inProgress ? mapAttempt(inProgress) : undefined } }).filter((exam) => !filters?.query || `${exam.title} ${exam.year} ${exam.source ?? ''}`.toLowerCase().includes(filters.query.toLowerCase())).filter((exam) => !filters?.status || filters.status === 'all' || (filters.status === 'in_progress' ? exam.inProgress : filters.status === 'completed' ? exam.attempts.some((a) => a.status === 'completed') : !exam.attempts.length)) }

function mapAttempt(x: any): ExamAttempt { return { id: String(x.id), examId: String(x.exam_id), startedAt: String(x.started_at), finishedAt: x.finished_at ? String(x.finished_at) : null, timeRemainingSeconds: Number(x.time_remaining_seconds), status: String(x.status), totalPoints: Number(x.total_points), earnedPoints: Number(x.earned_points), percentage: Number(x.percentage) } }

export async function getExam(examId: string): Promise<Exam | null> { const all = await listExams(); return all.find((x) => x.id === examId) ?? null }
export async function getExamQuestions(examId: string): Promise<ExamQuestion[]> { const supabase = createClient(); if (!supabase) return []; const { data, error } = await supabase.from('exam_questions').select('id,question_id,question_number,points,questions(id,question_text,question_type,topic_id,correct_answer,topics(name))').eq('exam_id', examId).order('order_index'); if (error) throw error; return (data ?? []).map((x: any) => ({ id: String(x.id), questionId: String(x.question_id), number: Number(x.question_number), points: Number(x.points), questionText: String(x.questions?.question_text ?? ''), questionType: String(x.questions?.question_type ?? 'open'), topicId: String(x.questions?.topic_id ?? ''), topicName: x.questions?.topics?.name, correctAnswer: x.questions?.correct_answer })) }
export async function startExam(examId: string): Promise<ExamAttempt> { const supabase = createClient(); const uid = await userId(); if (!supabase || !uid) throw new Error('Zaloguj się, aby rozpocząć egzamin.'); const exam = await getExam(examId); if (!exam) throw new Error('Nie znaleziono egzaminu.'); const { data, error } = await supabase.from('exam_attempts').insert({ user_id: uid, exam_id: examId, time_remaining_seconds: exam.durationMinutes * 60, total_points: exam.totalPoints, status: 'in_progress' }).select('*').single(); if (error) throw error; return mapAttempt(data) }
export async function getAttempt(attemptId: string) { const supabase = createClient(); if (!supabase) return null; const { data, error } = await supabase.from('exam_attempts').select('*').eq('id', attemptId).single(); if (error) throw error; return mapAttempt(data) }
export async function getExamAnswers(attemptId: string): Promise<ExamAnswer[]> { const supabase = createClient(); if (!supabase) return []; const { data, error } = await supabase.from('exam_answers').select('question_id,answer,flagged,saved_at').eq('attempt_id', attemptId); if (error) throw error; return (data ?? []).map((x: any) => ({ questionId: String(x.question_id), answer: String(x.answer ?? ''), flagged: Boolean(x.flagged), savedAt: String(x.saved_at) })) }
export async function saveExamAnswer(attemptId: string, questionId: string, answer: string, flagged: boolean) { const supabase = createClient(); if (!supabase) throw new Error('Brak połączenia.'); const { error } = await supabase.from('exam_answers').upsert({ attempt_id: attemptId, question_id: questionId, answer, flagged, saved_at: new Date().toISOString() }, { onConflict: 'attempt_id,question_id' }); if (error) throw error }
export async function saveExamTime(attemptId: string, seconds: number) { const supabase = createClient(); if (!supabase) return; const { error } = await supabase.from('exam_attempts').update({ time_remaining_seconds: Math.max(0, seconds), updated_at: new Date().toISOString() }).eq('id', attemptId).eq('status', 'in_progress'); if (error) throw error }
export async function finishExam(attemptId: string): Promise<ExamAttempt> { const supabase = createClient(); if (!supabase) throw new Error('Brak połączenia.'); const { data, error } = await supabase.rpc('finish_exam_attempt', { p_attempt_id: attemptId }); if (error) throw error; return mapAttempt(data) }
export async function abandonExam(attemptId: string) { const supabase = createClient(); if (!supabase) return; const { error } = await supabase.from('exam_attempts').update({ status: 'abandoned', updated_at: new Date().toISOString() }).eq('id', attemptId).eq('status', 'in_progress'); if (error) throw error }
export async function getExamResultStats(attemptId: string) { const supabase = createClient(); if (!supabase) return { correct: 0, incorrect: 0, unanswered: 0, topics: [] as { name: string; percentage: number }[] }; const { data, error } = await supabase.from('exam_answers').select('answer,questions(correct_answer,topics(name))').eq('attempt_id', attemptId); if (error) throw error; const rows = data ?? []; const correct = rows.filter((x: any) => x.answer && String(x.answer).trim().toLowerCase() === String(x.questions?.correct_answer ?? '').trim().toLowerCase()).length; const unanswered = rows.filter((x: any) => !String(x.answer ?? '').trim()).length; const grouped = new Map<string, { total: number; correct: number }>(); rows.forEach((x: any) => { const name = String(x.questions?.topics?.name ?? 'Inne'); const item = grouped.get(name) ?? { total: 0, correct: 0 }; item.total += 1; if (x.answer && String(x.answer).trim().toLowerCase() === String(x.questions?.correct_answer ?? '').trim().toLowerCase()) item.correct += 1; grouped.set(name, item) }); return { correct, incorrect: rows.length - correct - unanswered, unanswered, topics: [...grouped.entries()].map(([name, value]) => ({ name, percentage: Math.round(value.correct / value.total * 100) })) } }
export async function retryExam(examId: string) { return startExam(examId) }
export async function getExamHistory(examId: string) { const supabase = createClient(); const uid = await userId(); if (!supabase || !uid) return []; const { data, error } = await supabase.from('exam_attempts').select('*').eq('exam_id', examId).eq('user_id', uid).eq('status', 'completed').order('finished_at', { ascending: false }); if (error) throw error; return (data ?? []).map(mapAttempt) }
