import type { ContentTask } from '@/content/types'

/**
 * Bank zadań do działu „Wyrażenia algebraiczne” (poziom podstawowy z elementami rozszerzenia).
 * Kody `al-*` są stabilnym kluczem importu — nie zmieniaj ich przy edycji treści.
 */
export const algebraTasks: ContentTask[] = [
  {
    id: 'al-01',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-wzory',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Oblicz $x^{2}-y^{2}$ dla $x = 12$ i $y = 8$.',
    answer: '80',
    acceptedAnswers: ['80', '80,0'],
    tags: ['wzory', 'roznica-kwadratow'],
    skills: ['algebra-wzory-skroconego-mnozenia'],
    hints: ['Zamiast podnosić do kwadratu, użyj wzoru na różnicę kwadratów.', '$x^{2}-y^{2} = (x-y)(x+y)$'],
    solution: '$x^{2}-y^{2} = (x-y)(x+y) = (12-8)(12+8) = 4 \\cdot 20 = 80$.',
    steps: ['Zapisz różnicę kwadratów jako iloczyn.', 'Oblicz $12-8$ i $12+8$.', 'Pomnóż otrzymane liczby.'],
  },
  {
    id: 'al-02',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-wzory',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Oblicz wartość wyrażenia $(2x+1)^{2}$ dla $x = 2$.',
    answer: '25',
    acceptedAnswers: ['25', '25,0'],
    tags: ['wzory', 'kwadrat-sumy'],
    skills: ['algebra-wzory-skroconego-mnozenia'],
    hints: ['Podstaw $x = 2$ do nawiasu.', 'Następnie podnieś wynik do kwadratu.'],
    solution: 'Dla $x = 2$ mamy $2x+1 = 5$, więc $(2x+1)^{2} = 25$.',
    steps: ['Podstaw $x = 2$.', '$2 \\cdot 2 + 1 = 5$.', '$5^{2} = 25$.'],
  },
  {
    id: 'al-03',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-wzory',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Oblicz $101^{2}-99^{2}$.',
    answer: '400',
    acceptedAnswers: ['400', '400,0'],
    tags: ['wzory', 'roznica-kwadratow', 'rachunek-pamieciowy'],
    skills: ['algebra-wzory-skroconego-mnozenia'],
    hints: ['To różnica kwadratów dwóch bliskich liczb.', '$(101-99)(101+99)$'],
    solution: '$101^{2}-99^{2} = (101-99)(101+99) = 2 \\cdot 200 = 400$.',
    steps: ['Zauważ różnicę kwadratów.', 'Oblicz różnicę i sumę.', 'Pomnóż: $2 \\cdot 200$.'],
  },
  {
    id: 'al-04',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-wzory',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Oblicz $(2\\sqrt{5}-3)(2\\sqrt{5}+3)$.',
    answer: '11',
    acceptedAnswers: ['11', '11,0'],
    tags: ['wzory', 'pierwiastki'],
    skills: ['algebra-wzory-skroconego-mnozenia'],
    hints: ['Iloczyn wyrażeń sprzężonych to różnica kwadratów.', '$(2\\sqrt{5})^{2} = 4 \\cdot 5$'],
    solution: '$(2\\sqrt{5})^{2} - 3^{2} = 4 \\cdot 5 - 9 = 20 - 9 = 11$.',
    steps: ['Zastosuj $a^{2}-b^{2}$ z $a = 2\\sqrt{5}$ i $b = 3$.', 'Podnieś do kwadratu: $20$ i $9$.', 'Odejmij.'],
  },
  {
    id: 'al-05',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-wzory',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Które wyrażenie jest równe $9x^{2}-16$?',
    options: ['$(3x-4)(3x+4)$', '$(3x-4)^{2}$', '$(9x-16)(x+1)$', '$(3x+4)^{2}$'],
    answer: '(3x-4)(3x+4)',
    tags: ['wzory', 'roznica-kwadratow', 'zamkniete'],
    skills: ['algebra-wzory-skroconego-mnozenia'],
    hints: ['Zauważ różnicę dwóch kwadratów.', '$9x^{2} = (3x)^{2}$ oraz $16 = 4^{2}$'],
    solution: '$9x^{2}-16 = (3x)^{2}-4^{2} = (3x-4)(3x+4)$. Pozostałe odpowiedzi są błędne, bo $(3x-4)^{2}$ zawiera wyraz $-24x$, a $(3x+4)^{2}$ wyraz $+24x$.',
    steps: ['Zapisz oba wyrazy jako kwadraty.', 'Zastosuj $a^{2}-b^{2} = (a-b)(a+b)$.'],
  },
  {
    id: 'al-06',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-wzory',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Uprość, a następnie oblicz wartość dla $x = 4$: $3x^{2}-5x+2x^{2}+7x-4$.',
    answer: '84',
    acceptedAnswers: ['84', '84,0'],
    tags: ['redukcja'],
    skills: ['algebra-redukcja-wyrazen'],
    hints: ['Najpierw zredukuj wyrazy podobne.', 'Wyrazy z $x^{2}$ i osobno wyrazy z $x$.'],
    solution: 'Redukcja: $5x^{2}+2x-4$. Dla $x = 4$: $5 \\cdot 16 + 2 \\cdot 4 - 4 = 80 + 8 - 4 = 84$.',
    steps: ['Zredukuj: $3x^{2}+2x^{2} = 5x^{2}$.', 'Zredukuj: $-5x+7x = 2x$.', 'Podstaw $x = 4$ i oblicz.'],
  },
  {
    id: 'al-07',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-przeksztalcenia',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Rozłóż na czynniki i oblicz wartość dla $x = 7$: $\\dfrac{x^{2}-9}{x-3}$.',
    answer: '10',
    acceptedAnswers: ['10', '10,0'],
    tags: ['rozkladanie', 'wymierne', 'skracanie'],
    skills: ['algebra-rozkladanie-na-czynniki', 'algebra-dziedzina-wyrazenia-wymiernego'],
    hints: ['Licznik to różnica kwadratów.', '$x^{2}-9 = (x-3)(x+3)$'],
    solution: '$\\dfrac{x^{2}-9}{x-3} = \\dfrac{(x-3)(x+3)}{x-3} = x+3$ dla $x \\neq 3$. Dla $x = 7$ wartość wynosi $10$.',
    steps: ['Rozłóż licznik na czynniki.', 'Zapisz założenie $x \\neq 3$.', 'Skróć i podstaw $x = 7$.'],
  },
  {
    id: 'al-08',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-przeksztalcenia',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Dla jakiej liczby $x$ wyrażenie $\\dfrac{5}{x-2}$ nie ma sensu?',
    answer: '2',
    acceptedAnswers: ['2', '2,0'],
    tags: ['dziedzina', 'wymierne'],
    skills: ['algebra-dziedzina-wyrazenia-wymiernego'],
    hints: ['Ułamek nie ma sensu, gdy mianownik jest równy zero.', 'Rozwiąż $x-2 = 0$.'],
    solution: 'Mianownik $x-2$ zeruje się dla $x = 2$, więc dla tej liczby wyrażenie nie ma sensu.',
    steps: ['Przyrównaj mianownik do zera.', 'Rozwiąż równanie liniowe.'],
  },
  {
    id: 'al-09',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-przeksztalcenia',
    type: 'single_choice',
    difficulty: 3,
    points: 1,
    prompt: 'Jaka jest dziedzina wyrażenia $\\dfrac{x+1}{x^{2}-4}$?',
    options: ['$x \\neq -2$ i $x \\neq 2$', '$x \\neq 2$', '$x \\neq -1$', '$x \\neq 0$'],
    answer: '$x \\neq -2$ i $x \\neq 2$',
    tags: ['dziedzina', 'wymierne', 'zamkniete'],
    skills: ['algebra-dziedzina-wyrazenia-wymiernego'],
    hints: ['Rozłóż mianownik na czynniki.', '$x^{2}-4 = (x-2)(x+2)$'],
    solution: '$x^{2}-4 = (x-2)(x+2)$, więc mianownik zeruje się dla $x = 2$ oraz $x = -2$. Dziedzina to $\\mathbb{R} \\setminus \\{-2, 2\\}$.',
    steps: ['Rozłóż mianownik.', 'Wyklucz pierwiastki mianownika.', 'Zapisz dziedzinę.'],
  },
  {
    id: 'al-10',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-przeksztalcenia',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'Rozłóż na czynniki i podaj liczbę czynników liniowych: $x^{4}-16$.',
    answer: '2',
    acceptedAnswers: ['2', '2,0'],
    tags: ['rozkladanie', 'wielomiany'],
    skills: ['algebra-rozkladanie-na-czynniki'],
    hints: ['Najpierw różnica kwadratów: $x^{4}-16 = (x^{2}-4)(x^{2}+4)$', 'Czynnik $x^{2}+4$ nie rozkłada się nad liczbami rzeczywistymi.'],
    solution: '$x^{4}-16 = (x^{2}-4)(x^{2}+4) = (x-2)(x+2)(x^{2}+4)$. Czynniki liniowe to $(x-2)$ i $(x+2)$ — jest ich $2$.',
    steps: ['Zastosuj różnicę kwadratów.', 'Rozłóż $x^{2}-4$ ponownie.', 'Policz czynniki liniowe (stopnia pierwszego).'],
  },
  {
    id: 'al-11',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-przeksztalcenia',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'Rozłóż na czynniki: $x^{3}+2x^{2}-3x-6$, a następnie oblicz wartość dla $x = -2$.',
    answer: '0',
    acceptedAnswers: ['0', '0,0'],
    tags: ['rozkladanie', 'grupowanie'],
    skills: ['algebra-rozkladanie-na-czynniki'],
    hints: ['Pogrupuj dwa pierwsze i dwa ostatnie wyrazy.', '$x^{2}(x+2) - 3(x+2)$'],
    solution: '$x^{3}+2x^{2}-3x-6 = x^{2}(x+2)-3(x+2) = (x+2)(x^{2}-3)$. Dla $x = -2$ pierwszy czynnik jest zerem, więc wartość wynosi $0$.',
    steps: ['Pogrupuj wyrazy.', 'Wyłącz wspólny czynnik $(x+2)$.', 'Podstaw $x = -2$.'],
  },
  {
    id: 'al-12',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-matura',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Oblicz $15\\%$ liczby $240$.',
    answer: '36',
    acceptedAnswers: ['36', '36,0'],
    tags: ['procenty'],
    skills: ['algebra-procenty-w-praktyce'],
    hints: ['$1\\%$ z $240$ to $2{,}4$.', 'Pomnóż $2{,}4$ przez $15$.'],
    solution: '$15\\% \\cdot 240 = 0{,}15 \\cdot 240 = 36$.',
    steps: ['Zamień procent na ułamek.', 'Pomnóż przez liczbę.'],
  },
  {
    id: 'al-13',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-matura',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'Po podwyżce o $20\\%$ cena towaru wynosi $156$ zł. Ile kosztował towar przed podwyżką?',
    answer: '130',
    acceptedAnswers: ['130', '130,0'],
    tags: ['procenty', 'zadanie-tekstowe'],
    skills: ['algebra-procenty-w-praktyce'],
    hints: ['Podwyżka o $20\\%$ to mnożenie przez $1{,}2$.', 'Ułóż równanie $1{,}2x = 156$.'],
    solution: 'Niech $x$ będzie ceną przed podwyżką. $1{,}2x = 156$, więc $x = \\dfrac{156}{1{,}2} = 130$ zł.',
    steps: ['Zapisz cenę po podwyżce jako $1{,}2x$.', 'Ułóż równanie $1{,}2x = 156$.', 'Podziel obie strony przez $1{,}2$.'],
  },
  {
    id: 'al-14',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-matura',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'Cena $240$ zł została obniżona dwukrotnie, za każdym razem o $10\\%$. Jaka jest cena końcowa (w złotych)?',
    answer: '194.4',
    acceptedAnswers: ['194.4', '194,4', '194.40'],
    tags: ['procenty', 'procent-skladany'],
    skills: ['algebra-procenty-w-praktyce'],
    hints: ['Obniżka o $10\\%$ to mnożenie przez $0{,}9$.', 'Zastosuj ten czynnik dwa razy.'],
    solution: '$240 \\cdot 0{,}9 = 216$, a następnie $216 \\cdot 0{,}9 = 194{,}40$ zł. Wynik jest wyższy niż przy jednej obniżce o $20\\%$ (wtedy byłoby $240 \\cdot 0{,}8 = 192$ zł), bo drugą obniżkę liczymy od mniejszej podstawy.',
    steps: ['Pomnóż $240$ przez $0{,}9$.', 'Pomnóż wynik ponownie przez $0{,}9$.', 'Zapisz cenę końcową.'],
  },
  {
    id: 'al-15',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-matura',
    type: 'proof',
    difficulty: 4,
    points: 2,
    prompt: 'Wykaż, że dla dowolnych liczb rzeczywistych $a$ i $b$ zachodzi nierówność $(a+b)^{2} \\geq 4ab$.',
    answer: 'a2+2ab+b2-4ab=(a-b)2>=0',
    tags: ['dowod', 'nierownosc', 'otwarte'],
    skills: ['algebra-dowod-nierownosci-algebraicznej'],
    hints: ['Przenieś prawą stronę na lewą.', 'Otrzymane wyrażenie to kwadrat różnicy.'],
    solution: 'Przekształcamy nierówność równoważnie: $(a+b)^{2} - 4ab = a^{2}+2ab+b^{2}-4ab = a^{2}-2ab+b^{2} = (a-b)^{2}$. Ponieważ kwadrat każdej liczby rzeczywistej jest nieujemny, zachodzi $(a-b)^{2} \\geq 0$, a więc $(a+b)^{2} \\geq 4ab$. Co należało wykazać.',
    steps: [
      'Przenieś $4ab$ na lewą stronę nierówności.',
      'Zapisz lewą stronę jako $a^{2}+2ab+b^{2}-4ab$.',
      'Zredukuj wyrazy: otrzymasz $(a-b)^{2}$.',
      'Powołaj się na nieujemność kwadratu i zakończ wnioskiem „co należało wykazać”.',
    ],
    rubric: [
      { criterion: 'Poprawne przekształcenie do postaci $(a-b)^{2}$', points: 1 },
      { criterion: 'Powołanie się na nieujemność kwadratu i wniosek końcowy', points: 1 },
    ],
    sourceType: 'authored',
  },
  {
    id: 'al-16',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-matura',
    type: 'proof',
    difficulty: 4,
    points: 2,
    prompt: 'Wykaż, że $(a+b)^{2} - (a-b)^{2} = 4ab$ dla dowolnych liczb rzeczywistych $a$ i $b$.',
    answer: 'a2+2ab+b2-(a2-2ab+b2)=4ab',
    tags: ['dowod', 'tozsamosc', 'otwarte'],
    skills: ['algebra-dowod-nierownosci-algebraicznej', 'algebra-wzory-skroconego-mnozenia'],
    hints: ['Rozwiń oba nawiasy osobno.', 'Uważaj na znak minus przed drugim nawiasem.'],
    solution: 'Lewa strona: $(a+b)^{2} = a^{2}+2ab+b^{2}$ oraz $(a-b)^{2} = a^{2}-2ab+b^{2}$. Po odjęciu: $a^{2}+2ab+b^{2}-a^{2}+2ab-b^{2} = 4ab$. Otrzymaliśmy prawą stronę, więc tożsamość jest prawdziwa.',
    steps: [
      'Rozwiń $(a+b)^{2}$.',
      'Rozwiń $(a-b)^{2}$ i pamiętaj o minusie przed całym nawiasem.',
      'Zredukuj wyrazy podobne i wskaż $4ab$.',
    ],
    rubric: [
      { criterion: 'Poprawne rozwinięcie obu kwadratów', points: 1 },
      { criterion: 'Poprawna redukcja z zachowaniem znaków i wniosek', points: 1 },
    ],
  },
  {
    id: 'al-17',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-matura',
    type: 'numeric',
    difficulty: 4,
    points: 2,
    prompt: 'Dane są liczby dodatnie $x$ i $y$ takie, że $x^{2}+y^{2} = 25$ oraz $xy = 12$. Oblicz $x+y$.',
    answer: '7',
    acceptedAnswers: ['7', '7,0'],
    tags: ['wzory', 'uklad', 'otwarte'],
    skills: ['algebra-wzory-skroconego-mnozenia'],
    hints: ['Zauważ, że $(x+y)^{2} = x^{2}+2xy+y^{2}$.', 'Podstaw dane wartości do tego wzoru.'],
    solution: '$(x+y)^{2} = x^{2}+2xy+y^{2} = 25 + 2 \\cdot 12 = 49$. Ponieważ $x$ i $y$ są dodatnie, $x+y = 7$.',
    steps: ['Zapisz wzór na kwadrat sumy.', 'Podstaw $x^{2}+y^{2} = 25$ i $xy = 12$.', 'Pierwiastkuj, wybierając rozwiązanie dodatnie.'],
  },
  {
    id: 'al-18',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-matura',
    type: 'numeric',
    difficulty: 3,
    points: 1,
    prompt: 'Oblicz $(x+1)^{3}$ dla $x = 2$.',
    answer: '27',
    acceptedAnswers: ['27', '27,0'],
    tags: ['wzory', 'szescian', 'rozszerzenie'],
    skills: ['algebra-wzory-skroconego-mnozenia'],
    hints: ['Najpierw podstaw $x = 2$.', '$(2+1)^{3} = 3^{3}$'],
    solution: 'Dla $x = 2$ mamy $(2+1)^{3} = 3^{3} = 27$. Kontrolnie ze wzoru: $8 + 3 \\cdot 4 \\cdot 1 + 3 \\cdot 2 \\cdot 1 + 1 = 27$.',
    steps: ['Podstaw $x = 2$.', 'Podnieś $3$ do trzeciej potęgi.'],
    level: 'extended',
  },
  {
    id: 'al-19',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-wzory',
    type: 'text',
    difficulty: 3,
    points: 1,
    prompt: 'Doprowadź do najprostszej postaci: $\\dfrac{6x^{2}y}{3xy}$ (dla $x \\neq 0$ i $y \\neq 0$).',
    answer: '2x',
    acceptedAnswers: ['2x', '2*x'],
    tags: ['wymierne', 'skracanie'],
    skills: ['algebra-redukcja-wyrazen'],
    hints: ['Podziel współczynniki: $6 : 3$.', 'Podziel potęgi tej samej litery, odejmując wykładniki.'],
    solution: '$\\dfrac{6x^{2}y}{3xy} = 2x^{2-1}y^{1-1} = 2x$.',
    steps: ['Podziel współczynniki liczbowe.', 'Odejmij wykładniki przy $x$ i przy $y$.'],
  },
  {
    id: 'al-20',
    topicSlug: 'algebra',
    lessonSlug: 'algebra-przeksztalcenia',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'Oblicz $\\dfrac{x^{2}+6x+9}{x+3}$ dla $x = 4$.',
    answer: '7',
    acceptedAnswers: ['7', '7,0'],
    tags: ['rozkladanie', 'wymierne'],
    skills: ['algebra-rozkladanie-na-czynniki', 'algebra-dziedzina-wyrazenia-wymiernego'],
    hints: ['Licznik to kwadrat sumy: $(x+3)^{2}$.', 'Po skróceniu zostaje $x+3$.'],
    solution: '$\\dfrac{x^{2}+6x+9}{x+3} = \\dfrac{(x+3)^{2}}{x+3} = x+3$ dla $x \\neq -3$. Dla $x = 4$ wartość to $7$.',
    steps: ['Zapisz licznik jako $(x+3)^{2}$.', 'Zapisz założenie $x \\neq -3$.', 'Skróć i podstaw $x = 4$.'],
  },
]
