import type { ContentTask } from '@/content/types'

/**
 * Bank zadań do działu „Ciągi”. Kody `cg-*` są stabilnym kluczem importu.
 */
export const ciagiTasks: ContentTask[] = [
  {
    id: 'cg-01',
    topicSlug: 'ciagi',
    lessonSlug: 'ciagi-pojecie',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Ciąg $(a_n)$ jest zadany wzorem $a_n = 3n - 1$. Oblicz siódmy wyraz tego ciągu.',
    answer: '20',
    acceptedAnswers: ['20', '20,0'],
    tags: ['wzor-ogolny'],
    skills: ['ciagi-pojecie'],
    hints: ['Podstaw $n = 7$ do wzoru ogólnego.', '$a_7 = 3 \\cdot 7 - 1$'],
    solution: '$a_7 = 3 \\cdot 7 - 1 = 21 - 1 = 20$.',
    steps: ['Podstaw $n = 7$: $a_7 = 3 \\cdot 7 - 1$.', 'Policz: $21 - 1 = 20$.'],
  },
  {
    id: 'cg-02',
    topicSlug: 'ciagi',
    lessonSlug: 'ciagi-pojecie',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Cztery pierwsze wyrazy ciągu to $4, 7, 10, 13$. Który wzór opisuje ten ciąg?',
    options: ['$a_n = 3n + 1$', '$a_n = 3n$', '$a_n = n + 3$', '$a_n = 4n$'],
    answer: '$a_n = 3n + 1$',
    tags: ['wzor-ogolny'],
    skills: ['ciagi-pojecie'],
    hints: ['Wyrazy rosną o $3$, więc przy $n$ stoi współczynnik $3$.', 'Sprawdź, które wzory dają $a_1 = 4$.'],
    solution: 'Wyrazy rosną o $3$, więc wzór ma postać $a_n = 3n + b$. Z $a_1 = 4$ wynika $b = 1$, stąd $a_n = 3n + 1$. Sprawdzenie: $a_2 = 7$, $a_3 = 10$, $a_4 = 13$.',
    steps: ['Zauważ stałą różnicę $3$: wzór to $3n + b$.', 'Podstaw $n = 1$: $3 + b = 4$, więc $b = 1$.', 'Sprawdź wzór na pozostałych wyrazach.'],
  },
  {
    id: 'cg-03',
    topicSlug: 'ciagi',
    lessonSlug: 'ciagi-pojecie',
    type: 'numeric',
    difficulty: 3,
    points: 1,
    prompt: 'Ciąg $(a_n)$ jest zadany rekurencyjnie: $a_1 = 3$, $a_{n+1} = 2a_n - 1$. Oblicz $a_4$.',
    answer: '17',
    acceptedAnswers: ['17'],
    tags: ['rekurencja'],
    skills: ['ciagi-pojecie'],
    hints: ['Wyliczaj kolejne wyrazy: najpierw $a_2$.', '$a_2 = 2 \\cdot 3 - 1 = 5$'],
    solution: '$a_2 = 2 \\cdot 3 - 1 = 5$, $a_3 = 2 \\cdot 5 - 1 = 9$, $a_4 = 2 \\cdot 9 - 1 = 17$.',
    steps: ['$a_2 = 2a_1 - 1 = 5$.', '$a_3 = 2a_2 - 1 = 9$.', '$a_4 = 2a_3 - 1 = 17$.'],
  },
  {
    id: 'cg-04',
    topicSlug: 'ciagi',
    lessonSlug: 'ciagi-arytmetyczny',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'W ciągu arytmetycznym $(a_n)$ mamy $a_1 = 5$ i $r = -2$. Oblicz $a_{10}$.',
    answer: '-13',
    acceptedAnswers: ['-13', '−13'],
    tags: ['arytmetyczny', 'wyraz-ogolny'],
    skills: ['ciagi-arytmetyczny'],
    hints: ['Użyj wzoru $a_n = a_1 + (n-1)r$.', '$a_{10} = 5 + 9 \\cdot (-2)$'],
    solution: '$a_{10} = a_1 + 9r = 5 + 9 \\cdot (-2) = 5 - 18 = -13$.',
    steps: ['Zapisz wzór: $a_n = a_1 + (n-1)r$.', 'Podstaw: $a_{10} = 5 + 9 \\cdot (-2)$.', 'Oblicz: $-13$.'],
  },
  {
    id: 'cg-05',
    topicSlug: 'ciagi',
    lessonSlug: 'ciagi-arytmetyczny',
    type: 'numeric',
    difficulty: 3,
    points: 1,
    prompt: 'W ciągu arytmetycznym $a_4 = 10$ oraz $a_9 = 25$. Oblicz dwudziesty wyraz $a_{20}$.',
    answer: '58',
    acceptedAnswers: ['58'],
    tags: ['arytmetyczny', 'wyznaczanie-r'],
    skills: ['ciagi-arytmetyczny'],
    hints: ['Między $a_4$ a $a_9$ jest $5$ kroków: $a_9 - a_4 = 5r$.', 'Najpierw znajdziesz $r$, potem $a_1$.'],
    solution: '$a_9 - a_4 = 5r = 15$, więc $r = 3$. Dalej $a_1 = a_4 - 3r = 10 - 9 = 1$. Wtedy $a_{20} = 1 + 19 \\cdot 3 = 58$.',
    steps: ['Oblicz $r$: $5r = 25 - 10 = 15$, więc $r = 3$.', 'Wyznacz $a_1 = a_4 - 3r = 1$.', 'Podstaw do $a_n = a_1 + (n-1)r$: $a_{20} = 58$.'],
  },
  {
    id: 'cg-06',
    topicSlug: 'ciagi',
    lessonSlug: 'ciagi-arytmetyczny',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Suma wszystkich liczb naturalnych od $1$ do $100$ jest równa:',
    options: ['5050', '5000', '5500', '10100'],
    answer: '5050',
    tags: ['suma', 'arytmetyczny'],
    skills: ['ciagi-suma-arytmetyczna'],
    hints: ['To suma $100$ początkowych wyrazów ciągu arytmetycznego $1, 2, 3, \\ldots$', 'Zastosuj $S_n = \\frac{a_1 + a_n}{2} \\cdot n$.'],
    solution: '$S_{100} = \\frac{1 + 100}{2} \\cdot 100 = 50{,}5 \\cdot 100 = 5050$.',
    steps: ['Rozpoznaj ciąg arytmetyczny: $a_1 = 1$, $a_{100} = 100$, $n = 100$.', 'Podstaw do wzoru na sumę.', 'Oblicz $5050$.'],
  },
  {
    id: 'cg-07',
    topicSlug: 'ciagi',
    lessonSlug: 'ciagi-arytmetyczny',
    type: 'open',
    difficulty: 3,
    points: 3,
    prompt: 'W sali kinowej pierwszy rząd ma $14$ miejsc, a każdy następny rząd ma o $2$ miejsca więcej od poprzedniego. Sala ma $18$ rzędów. Ile łącznie miejsc znajduje się na sali?',
    answer: '558',
    acceptedAnswers: ['558'],
    tags: ['arytmetyczny', 'zadanie-tekstowe'],
    skills: ['ciagi-suma-arytmetyczna'],
    hints: ['Liczba miejsc w rzędach tworzy ciąg arytmetyczny: $a_1 = 14$, $r = 2$.', 'Ilość miejsc to suma $S_{18} = \\frac{2a_1 + 17r}{2} \\cdot 18$.'],
    solution: 'Liczby miejsc tworzą ciąg arytmetyczny $a_1 = 14$, $r = 2$, $n = 18$. Suma: $S_{18} = \\frac{2 \\cdot 14 + 17 \\cdot 2}{2} \\cdot 18 = \\frac{28 + 34}{2} \\cdot 18 = 31 \\cdot 18 = 558$. Sala ma $558$ miejsc.',
    steps: ['Zapisz model: $a_1 = 14$, $r = 2$, $n = 18$.', 'Podstaw do wzoru na sumę: $S_{18} = \\frac{2a_1 + 17r}{2} \\cdot 18$.', 'Oblicz $558$ i podaj interpretację.'],
    rubric: [
      { criterion: 'Zapisanie modelu ciągu arytmetycznego ($a_1$, $r$, $n$)', points: 1 },
      { criterion: 'Poprawne podstawienie do wzoru na sumę', points: 1 },
      { criterion: 'Wynik $558$ wraz z interpretacją w kontekście', points: 1 },
    ],
  },
  {
    id: 'cg-08',
    topicSlug: 'ciagi',
    lessonSlug: 'ciagi-arytmetyczny',
    type: 'open',
    difficulty: 4,
    points: 4,
    prompt: 'Trzy liczby (w tej kolejności) tworzą ciąg arytmetyczny. Ich suma jest równa $27$, a iloczyn równy $585$. Wyznacz te liczby.',
    answer: '5, 9, 13 lub 13, 9, 5',
    acceptedAnswers: ['5, 9, 13 lub 13, 9, 5', '5,9,13', '13,9,5', '5 9 13', '13 9 5'],
    tags: ['arytmetyczny', 'uklad'],
    skills: ['ciagi-arytmetyczny'],
    hints: ['Zapisz liczby jako $a - d$, $a$, $a + d$ — wtedy suma od razu daje $3a$.', 'Z równania $3a = 27$ masz $a = 9$; podstaw do równania na iloczyn.'],
    solution: 'Liczby: $a - d$, $a$, $a + d$. Suma: $3a = 27$, więc $a = 9$. Iloczyn: $9(9-d)(9+d) = 585$, czyli $9(81 - d^{2}) = 585$, stąd $81 - d^{2} = 65$, $d^{2} = 16$ i $d = \\pm 4$. Liczby to $5, 9, 13$ albo (w odwrotnej kolejności) $13, 9, 5$.',
    steps: ['Zapisz liczby jako $a-d$, $a$, $a+d$ i rozpisz sumę: $3a = 27$.', 'Wyznacz $a = 9$.', 'Zapisz iloczyn: $9(81 - d^{2}) = 585$ i wyznacz $d^{2} = 16$.', 'Podaj obie możliwości $d = \\pm 4$ i uporządkuj odpowiedź.'],
    rubric: [
      { criterion: 'Oznaczenie $a - d$, $a$, $a + d$ i wyznaczenie $a = 9$', points: 1 },
      { criterion: 'Ułożenie równania na iloczyn i wyznaczenie $d^{2} = 16$', points: 2 },
      { criterion: 'Podanie obu uporządkowanych odpowiedzi', points: 1 },
    ],
  },
  {
    id: 'cg-09',
    topicSlug: 'ciagi',
    lessonSlug: 'ciagi-geometryczny',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'W ciągu geometrycznym $(b_n)$ mamy $b_1 = 3$ i $q = 2$. Oblicz $b_6$.',
    answer: '96',
    acceptedAnswers: ['96'],
    tags: ['geometryczny', 'wyraz-ogolny'],
    skills: ['ciagi-geometryczny'],
    hints: ['Użyj wzoru $b_n = b_1 q^{n-1}$.', '$b_6 = 3 \\cdot 2^{5}$'],
    solution: '$b_6 = b_1 \\cdot q^{5} = 3 \\cdot 32 = 96$.',
    steps: ['Zapisz wzór $b_n = b_1 q^{n-1}$.', 'Podstaw: $3 \\cdot 2^{5} = 3 \\cdot 32$.', 'Oblicz $96$.'],
  },
  {
    id: 'cg-10',
    topicSlug: 'ciagi',
    lessonSlug: 'ciagi-geometryczny',
    type: 'numeric',
    difficulty: 3,
    points: 1,
    prompt: 'W ciągu geometrycznym $b_3 = 12$ oraz $b_6 = 96$. Oblicz pierwszy wyraz $b_1$.',
    answer: '3',
    acceptedAnswers: ['3'],
    tags: ['geometryczny', 'wyznaczanie-q'],
    skills: ['ciagi-geometryczny'],
    hints: ['Między $b_3$ a $b_6$ są trzy kroki: $b_6 = b_3 \\cdot q^{3}$.', 'Z równania $q^{3} = 8$ wynika $q = 2$.'],
    solution: '$b_6 = b_3 \\cdot q^{3}$, więc $96 = 12 \\cdot q^{3}$, stąd $q^{3} = 8$ i $q = 2$. Wtedy $b_1 = \\frac{b_3}{q^{2}} = \\frac{12}{4} = 3$.',
    steps: ['Zapisz zależność $b_6 = b_3 q^{3}$.', 'Wyznacz $q = 2$.', 'Oblicz $b_1 = \\frac{b_3}{q^{2}} = 3$.'],
  },
  {
    id: 'cg-11',
    topicSlug: 'ciagi',
    lessonSlug: 'ciagi-geometryczny',
    type: 'numeric',
    difficulty: 3,
    points: 1,
    prompt: 'Oblicz sumę $1 + \\frac{1}{2} + \\frac{1}{4} + \\ldots + \\frac{1}{64}$. Wynik podaj w postaci ułamka zwykłego.',
    answer: '127/64',
    acceptedAnswers: ['127/64', '1 63/64'],
    tags: ['geometryczny', 'suma'],
    skills: ['ciagi-geometryczny'],
    hints: ['To $7$ wyrazów ciągu geometrycznego z $b_1 = 1$, $q = \\frac{1}{2}$.', 'Zastosuj $S_n = \\frac{b_1(1 - q^{n})}{1 - q}$.'],
    solution: 'Wyrazy to $\\left(\\frac{1}{2}\\right)^{0}, \\ldots, \\left(\\frac{1}{2}\\right)^{6}$ — $n = 7$ wyrazów. $S_7 = \\frac{1 \\cdot (1 - (1/2)^{7})}{1 - 1/2} = 2 \\left(1 - \\frac{1}{128}\\right) = 2 \\cdot \\frac{127}{128} = \\frac{127}{64}$.',
    steps: ['Rozpoznaj ciąg geometryczny: $b_1 = 1$, $q = \\frac{1}{2}$, $n = 7$.', 'Podstaw do wzoru na sumę.', 'Oblicz $\\frac{127}{64}$.'],
  },
  {
    id: 'cg-12',
    topicSlug: 'ciagi',
    lessonSlug: 'ciagi-geometryczny',
    type: 'open',
    difficulty: 3,
    points: 2,
    prompt: 'Pan Adam wpłacił do banku $8000$ zł na lokatę oprocentowaną $6\\%$ w skali roku, z kapitalizacją odsetek na koniec każdego roku. Jaką kwotę pan Adam otrzyma po trzech latach? Wynik zaokrąglij do groszy.',
    answer: '9528,13',
    acceptedAnswers: ['9528,13', '9528.13'],
    tags: ['geometryczny', 'procent-skladany'],
    skills: ['ciagi-procent-skladany'],
    hints: ['Po każdym roku kapitał mnoży się przez $1{,}06$.', '$K_3 = 8000 \\cdot 1{,}06^{3}$'],
    solution: 'Kwota po $n$ latach: $K_n = 8000 \\cdot 1{,}06^{n}$. Po trzech latach: $K_3 = 8000 \\cdot 1{,}191016 = 9528{,}128$, czyli po zaokrągleniu $9528{,}13$ zł.',
    steps: ['Zapisz wzór procentu składanego: $K_n = K_0 \\left(1 + \\frac{6}{100}\\right)^{n}$.', 'Podstaw: $8000 \\cdot 1{,}06^{3}$.', 'Oblicz $9528{,}128$ i zaokrąglij do $9528{,}13$ zł.'],
    rubric: [
      { criterion: 'Zapisanie wzoru procentu składanego ze współczynnikiem $1{,}06$', points: 1 },
      { criterion: 'Poprawny rachunek i zaokrąglenie do groszy', points: 1 },
    ],
  },
  {
    id: 'cg-13',
    topicSlug: 'ciagi',
    lessonSlug: 'ciagi-granica',
    type: 'numeric',
    level: 'extended',
    difficulty: 3,
    points: 2,
    prompt: 'Oblicz granicę $\\lim_{n \\to \\infty} \\frac{5n + 3}{n + 1}$.',
    answer: '5',
    acceptedAnswers: ['5'],
    tags: ['granica', 'rozszerzenie'],
    skills: ['ciagi-granica'],
    hints: ['Stopnie licznika i mianownika są równe — granica to stosunek współczynników przy $n$.', 'Albo podziel licznik i mianownik przez $n$.'],
    solution: 'Podziel licznik i mianownik przez $n$: $\\lim \\frac{5 + 3/n}{1 + 1/n} = \\frac{5 + 0}{1 + 0} = 5$.',
    steps: ['Podziel licznik i mianownik przez $n$.', 'Skorzystaj z $\\frac{1}{n} \\to 0$.', 'Granica wynosi $5$.'],
  },
  {
    id: 'cg-14',
    topicSlug: 'ciagi',
    lessonSlug: 'ciagi-granica',
    type: 'single_choice',
    level: 'extended',
    difficulty: 3,
    points: 2,
    prompt: 'Granica $\\lim_{n \\to \\infty} \\frac{2n^{2} - n}{n^{2} + 3n}$ jest równa:',
    options: ['2', '0', '1', 'granica nie istnieje'],
    answer: '2',
    tags: ['granica', 'ulamek-wielomianowy'],
    skills: ['ciagi-granica'],
    hints: ['Stopnie licznika i mianownika są równe ($2 = 2$).', 'Stosunek współczynników przy $n^{2}$ decyduje o wartości granicy.'],
    solution: 'Oba wielomiany mają stopień $2$, więc granica równa się stosunkowi współczynników przy $n^{2}$: $\\frac{2}{1} = 2$.',
    steps: ['Porównaj stopnie: licznik $2$, mianownik $2$.', 'Podziel przez $n^{2}$: $\\frac{2 - 1/n}{1 + 3/n}$.', 'Granica: $2$.'],
  },
  {
    id: 'cg-15',
    topicSlug: 'ciagi',
    lessonSlug: 'ciagi-granica',
    type: 'open',
    level: 'extended',
    difficulty: 4,
    points: 3,
    prompt: 'Dany jest nieskończony ciąg geometryczny o pierwszym wyrazie $9$ i ilorazie $\\frac{1}{3}$. Oblicz sumę tego ciągu. Pamiętaj o sprawdzeniu warunku zbieżności.',
    answer: '27/2',
    acceptedAnswers: ['27/2', '13,5', '13.5'],
    tags: ['szereg', 'granica'],
    skills: ['ciagi-szereg', 'ciagi-granica'],
    hints: ['Sprawdź, czy $|q| < 1$.', 'Suma szeregu: $S = \\frac{b_1}{1 - q}$.'],
    solution: 'Ponieważ $\\left|\\frac{1}{3}\\right| < 1$, szereg jest zbieżny i $S = \\frac{b_1}{1 - q} = \\frac{9}{1 - 1/3} = \\frac{9}{2/3} = \\frac{27}{2} = 13{,}5$.',
    steps: ['Sprawdź warunek: $|q| = \\frac{1}{3} < 1$ — szereg zbieżny.', 'Podstaw do $S = \\frac{b_1}{1 - q}$.', 'Oblicz $S = \\frac{27}{2}$.'],
    rubric: [
      { criterion: 'Sprawdzenie warunku zbieżności $|q| < 1$', points: 1 },
      { criterion: 'Poprawne podstawienie do wzoru na sumę szeregu', points: 1 },
      { criterion: 'Wynik $\\frac{27}{2}$', points: 1 },
    ],
  },
]
