import type { ContentTask } from '@/content/types'

export const dowodyTasks: ContentTask[] = [
  { id: 'dw-01', topicSlug: 'dowody', lessonSlug: 'dowody-algebraiczne', type: 'proof', level: 'extended', difficulty: 2, points: 2, prompt: 'Udowodnij tożsamość $(a-b)^2=a^2-2ab+b^2$.', answer: 'a^2-2ab+b^2', tags: ['dowod'], skills: ['dowody-algebraiczne'], hints: ['Rozwiń kwadrat różnicy.'], solution: 'Z definicji iloczynu: $(a-b)^2=a^2-ab-ab+b^2=a^2-2ab+b^2$.', steps: ['Rozwiń iloczyn.', 'Złącz wyrazy.'], rubric: [{ criterion: 'Rozwinięcie iloczynu', points: 1 }, { criterion: 'Poprawny wniosek', points: 1 }] },
  { id: 'dw-02', topicSlug: 'dowody', lessonSlug: 'dowody-algebraiczne', type: 'proof', level: 'extended', difficulty: 3, points: 3, prompt: 'Udowodnij nierówność $(a-b)^2\\geq0$ dla każdych liczb rzeczywistych $a,b$.', answer: 'kwadrat jest nieujemny', tags: ['nierownosc'], skills: ['dowody-algebraiczne'], hints: ['Kwadrat liczby rzeczywistej jest nieujemny.'], solution: 'Dla każdej $a,b\\in\\mathbb R$ wyrażenie $(a-b)^2$ jest kwadratem liczby rzeczywistej $a-b$, więc jest nieujemne.', steps: ['Rozpoznaj kwadrat.', 'Zastosuj własność kwadratu.'], rubric: [{ criterion: 'Rozpoznanie kwadratu', points: 1 }, { criterion: 'Własność kwadratu', points: 1 }, { criterion: 'Wniosek', points: 1 }] },
  { id: 'dw-03', topicSlug: 'dowody', lessonSlug: 'dowody-algebraiczne', type: 'open', level: 'extended', difficulty: 3, points: 3, prompt: 'Udowodnij, że jeśli $x>0$, to $x+1>x$.', answer: 'x+1>x', tags: ['nierownosc'], skills: ['dowody-algebraiczne'], hints: ['Odejmij $x$ od obu stron.'], solution: 'Od obu stron odejmujemy $x$: otrzymujemy $1>0$, co jest prawdą. Zatem $x+1>x$.', steps: ['Odejmij $x$.', 'Sprowadź do $1>0$.'], rubric: [{ criterion: 'Równoważne przekształcenie', points: 1 }, { criterion: 'Prawdziwość zdania $1>0$', points: 1 }, { criterion: 'Wniosek', points: 1 }] },
  { id: 'dw-04', topicSlug: 'dowody', lessonSlug: 'dowody-indukcja', type: 'proof', level: 'extended', difficulty: 3, points: 3, prompt: 'Udowodnij indukcyjnie, że każda potęga $2^n$ dla $n\\geq1$ jest liczbą całkowitą.', answer: 'tak', tags: ['indukcja'], skills: ['dowody-indukcja'], hints: ['Sprawdź $n=1$.', 'Załóż wynik dla $n$ i pomnóż przez 2.'], solution: 'Dla $n=1$ mamy $2^1=2\\in\\mathbb Z$. Jeśli $2^n\\in\\mathbb Z$, to $2^{n+1}=2\\cdot2^n$ jest iloczynem dwóch liczb całkowitych, więc jest całkowite.', steps: ['Sprawdź przypadek $n=1$.', 'Załóż indukcyjnie.', 'Przejdź do $n+1$.'], rubric: [{ criterion: 'Przypadek bazowy', points: 1 }, { criterion: 'Założenie indukcyjne', points: 1 }, { criterion: 'Krok indukcyjny', points: 1 }] },
  { id: 'dw-05', topicSlug: 'dowody', lessonSlug: 'dowody-indukcja', type: 'open', level: 'extended', difficulty: 4, points: 4, prompt: 'Udowodnij indukcyjnie wzór $1+2+\\cdots+n=\\frac{n(n+1)}2$ dla każdego $n\\geq1$.', answer: 'tak', tags: ['indukcja'], skills: ['dowody-indukcja'], hints: ['Dla $n=1$ obie strony są równe $1$.', 'Dodaj $n+1$ do założenia.'], solution: 'Dla $n=1$ mamy $1=1$. Załóżmy sumę $S_n=n(n+1)/2$. Wtedy $S_{n+1}=S_n+n+1=\\frac{n(n+1)+2n+2}{2}=\\frac{(n+1)(n+2)}2$.', steps: ['Sprawdź $n=1$.', 'Zapisz założenie indukcyjne.', 'Dodaj $n+1$ i uprość.'], rubric: [{ criterion: 'Przypadek bazowy', points: 1 }, { criterion: 'Założenie indukcyjne', points: 1 }, { criterion: 'Przejście do $n+1$', points: 2 }] },
  { id: 'dw-06', topicSlug: 'dowody', lessonSlug: 'dowody-geometryczne', type: 'proof', level: 'extended', difficulty: 3, points: 3, prompt: 'Udowodnij, że suma kątów w trójkącie wynosi $180^\\circ$.', answer: '180^circ', tags: ['geometria'], skills: ['dowody-geometryczne'], hints: ['Poprowadź prostą równoległą do podstawy przez wierzchołek.'], solution: 'Poprowadźmy przez wierzchołek $A$ prostą równoległą do podstawy $BC$. Kąty przy $A$ dzielą prosty kąt na trzy kąty odpowiadające kątom trójkąta, a wprost po tej prostej suma kątów wynosi $180^\\circ$.', steps: ['Dodaj prostą równoległą.', 'Zidentyfikuj odpowiadające kąty.', 'Podsumuj.'], rubric: [{ criterion: 'Konstrukcja prostej równoległej', points: 1 }, { criterion: 'Związek kątów', points: 1 }, { criterion: 'Wniosek o sumie $180^\\circ$', points: 1 }] },
  { id: 'dw-07', topicSlug: 'dowody', lessonSlug: 'dowody-geometryczne', type: 'open', level: 'extended', difficulty: 3, points: 3, prompt: 'Udowodnij, że w trójkącie równoramiennym kąty przy podstawie są równe.', answer: 'kąty przy podstawie są równe', tags: ['geometria'], skills: ['dowody-geometryczne'], hints: ['Użyj definicji trójkąta równoramiennego i twierdzenia o bokach przeciwległych.'], solution: 'Niech $AB=AC$. Kąty $ABC$ i $BCA$ są przeciwległe do równych boków $AC$ i $AB$. Twierdzenie o kątach przeciwległych do równych boków daje ich równość.', steps: ['Wypisz równość boków.', 'Wskaż kąty przeciwległe.', 'Zastosuj twierdzenie.'], rubric: [{ criterion: 'Oznaczenie równych boków', points: 1 }, { criterion: 'Wskazanie kątów', points: 1 }, { criterion: 'Wniosek', points: 1 }] },
  { id: 'dw-08', topicSlug: 'dowody', lessonSlug: 'dowody-algebraiczne', type: 'open', level: 'extended', difficulty: 4, points: 4, prompt: 'Udowodnij, że dla każdego $x$ zachodzi $x^2-4x+4\\geq0$.', answer: 'kwadrat (x-2)^2', tags: ['nierownosc'], skills: ['dowody-algebraiczne'], hints: ['Dokończ do kwadratu.'], solution: '$x^2-4x+4=(x-2)^2\\geq0$, ponieważ kwadrat liczby rzeczywistej jest nieujemny.', steps: ['Dokończ kwadrat.', 'Zastosuj własność kwadratu.'], rubric: [{ criterion: 'Dokończenie do kwadratu', points: 2 }, { criterion: 'Własność kwadratu', points: 1 }, { criterion: 'Wniosek', points: 1 }] },
  { id: 'dw-09', topicSlug: 'dowody', lessonSlug: 'dowody-uzasadnianie', type: 'open', level: 'basic', difficulty: 3, points: 3, prompt: 'Uzasadnij, że suma trzech kolejnych liczb całkowitych jest wielokrotnością $3$.', answer: '3n+3=3(n+1)', tags: ['uzasadnianie'], skills: ['dowody-uzasadnianie'], hints: ['Zapisz liczby jako $n$, $n+1$, $n+2$.'], solution: 'Suma jest $n+(n+1)+(n+2)=3n+3=3(n+1)$, czyli wielokrotnością $3$.', steps: ['Zapisz trzy liczby.', 'Dodaj je.', 'Wspólny czynnik 3.'], rubric: [{ criterion: 'Zapis trzech kolejnych liczb', points: 1 }, { criterion: 'Obliczenie sumy', points: 1 }, { criterion: 'Wyłonienie czynnika 3', points: 1 }] },
  { id: 'dw-10', topicSlug: 'dowody', lessonSlug: 'dowody-indukcja', type: 'open', level: 'extended', difficulty: 4, points: 4, prompt: 'Udowodnij indukcyjnie, że dla $n\\geq1$ zachodzi $n^2\\geq n$.', answer: 'tak', tags: ['indukcja', 'nierownosc'], skills: ['dowody-indukcja'], hints: ['Dla $n=1$ równość jest prawdziwa.', 'Załóż $n^2\\geq n$ i dodaj $2n+1$.'], solution: 'Dla $n=1$ mamy $1\\geq1$. Załóżmy $n^2\\geq n$. Wtedy $(n+1)^2=n^2+2n+1\\geq n+2n+1\\geq n+1$, co dowodzi kroku indukcyjnego.', steps: ['Sprawdź $n=1$.', 'Zastosuj założenie.', 'Dokańcz nierówność.'], rubric: [{ criterion: 'Przypadek bazowy', points: 1 }, { criterion: 'Założenie indukcyjne', points: 1 }, { criterion: 'Krok dla $n+1$', points: 2 }] },
]
