import type { ContentTask } from '@/content/types'

/**
 * Bank zadań do działu „Funkcje”.
 * Kody `fn-*` są stabilnym kluczem importu — nie zmieniaj ich przy edycji treści.
 */
export const funkcjeTasks: ContentTask[] = [
  {
    id: 'fn-01',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-wlasnosci',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Funkcja $f$ jest zadana wzorem $f(x) = 2x - 6$. Podaj miejsce zerowe funkcji $f$.',
    answer: '3',
    acceptedAnswers: ['3', '3,0'],
    tags: ['miejsca-zerowe', 'liniowa'],
    skills: ['funkcje-miejsca-zerowe'],
    hints: ['Miejsce zerowe: rozwiąż $f(x) = 0$.', '$2x - 6 = 0$'],
    solution: '$2x - 6 = 0$, więc $2x = 6$ i $x = 3$.',
    steps: ['Zapisz $f(x) = 0$.', 'Rozwiąż $2x = 6$: $x = 3$.'],
  },
  {
    id: 'fn-02',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-wlasnosci',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Funkcja $f(x) = x^{2} - 9$ ma dwa miejsca zerowe $x_1$ i $x_2$ ($x_1 < x_2$). Podaj wartość $x_1$.',
    answer: '-3',
    acceptedAnswers: ['-3', '−3', '-3,0'],
    tags: ['miejsca-zerowe'],
    skills: ['funkcje-miejsca-zerowe'],
    hints: ['$x^2 - 9 = (x-3)(x+3)$', 'Rozwiąż $(x-3)(x+3) = 0$.'],
    solution: '$x^{2} - 9 = 0 \\iff (x-3)(x+3) = 0$, więc $x = 3$ lub $x = -3$. Mniejsze: $x_1 = -3$.',
    steps: ['Rozłóż na czynniki: różnica kwadratów.', 'Wybierz mniejszy pierwiastek: $-3$.'],
  },
  {
    id: 'fn-03',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-wlasnosci',
    type: 'text',
    difficulty: 2,
    points: 1,
    prompt: 'Podaj dziedzinę funkcji $f(x) = \\frac{x+1}{x-4}$. Zapisz w formacie: R\\{a\\} albo słownie „x rozne od a”.',
    answer: 'R\\{4\\}',
    acceptedAnswers: ['R\\{4\\}', 'R bez {4}', 'x rozne od 4', 'x!=4', 'x \\neq 4'],
    tags: ['dziedzina'],
    skills: ['funkcje-dziedzina-wzor'],
    hints: ['Mianownik nie może być zerem.', 'Rozwiąż $x - 4 \\neq 0$.'],
    solution: 'Warunek: $x - 4 \\neq 0$, czyli $x \\neq 4$. Dziedzina: $\\mathbb{R} \\setminus \\{4\\}$.',
    steps: ['Zapisz warunek $x - 4 \\neq 0$.', 'Wniosek: $x \\neq 4$.'],
  },
  {
    id: 'fn-04',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-wlasnosci',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Dziedzina funkcji $f(x) = \\sqrt{2x - 6}$ to:',
    options: ['$[3, +\\infty)$', '$(3, +\\infty)$', '$\\mathbb{R}$', '$[6, +\\infty)$'],
    answer: '$[3, +\\infty)$',
    tags: ['dziedzina', 'pierwiastek'],
    skills: ['funkcje-dziedzina-wzor'],
    hints: ['Wyrażenie pod pierwiastkiem musi być nieujemne.', '$2x - 6 \\geq 0$.'],
    solution: '$2x - 6 \\geq 0 \\iff x \\geq 3$. Dziedzina: $[3, +\\infty)$ — nawias kwadratowy, bo $x = 3$ jest dozwolone (pierwiastek z zera istnieje).',
    steps: ['Zapisz $2x - 6 \\geq 0$.', 'Rozwiąż: $x \\geq 3$.', 'Zapisz przedział domknięty w $3$.'],
  },
  {
    id: 'fn-05',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-liniowa',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Funkcja liniowa $f$ ma miejsce zerowe $x = 4$ oraz $f(0) = -8$. Podaj współczynnik $a$ we wzorze $f(x) = ax + b$.',
    answer: '2',
    acceptedAnswers: ['2', '2,0'],
    tags: ['liniowa'],
    skills: ['funkcje-liniowa'],
    hints: ['$f(0) = b$, więc $b = -8$.', 'Podstaw $f(4) = 0$: $4a - 8 = 0$.'],
    solution: 'Z $f(0) = -8$ mamy $b = -8$. Z miejsca zerowego: $4a - 8 = 0$, więc $a = 2$. Wzór: $f(x) = 2x - 8$.',
    steps: ['Odczytaj $b = -8$.', 'Rozwiąż $4a - 8 = 0$: $a = 2$.'],
  },
  {
    id: 'fn-06',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-liniowa',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Prosta będąca wykresem funkcji liniowej $f$ przechodzi przez punkty $(1, 3)$ i $(3, 11)$. Podaj wartość $f(5)$.',
    answer: '19',
    acceptedAnswers: ['19', '19,0'],
    tags: ['liniowa', 'wzory'],
    skills: ['funkcje-liniowa'],
    hints: ['Najpierw oblicz $a = \\frac{\\Delta y}{\\Delta x}$.', '$a = \\frac{11-3}{3-1} = 4$, potem znajdź $b$.'],
    solution: '$a = \\frac{11 - 3}{3 - 1} = 4$. Z punktu $(1,3)$: $3 = 4 + b$, więc $b = -1$. Wzór: $f(x) = 4x - 1$. Stąd $f(5) = 20 - 1 = 19$.',
    steps: ['Oblicz $a = 4$.', 'Wyznacz $b = -1$.', 'Oblicz $f(5) = 19$.'],
  },
  {
    id: 'fn-07',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-liniowa',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Opłata za przewóz to $15$ zł startowo plus $3$ zł za kilometr. Ile zapłacimy za $8$ km?',
    options: ['$39$ zł', '$24$ zł', '$45$ zł', '$118$ zł'],
    answer: '$39$ zł',
    tags: ['liniowa', 'praktyczne'],
    skills: ['funkcje-liniowa'],
    hints: ['Zapisz wzór: $c(k) = 3k + 15$.', 'Podstaw $k = 8$.'],
    solution: 'Koszt: $c(k) = 3k + 15$. Dla $k = 8$: $c(8) = 24 + 15 = 39$ zł.',
    steps: ['Zapisz wzór kosztu.', 'Podstaw $k = 8$: $39$ zł.'],
  },
  {
    id: 'fn-08',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-logarytmy',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Oblicz wartość logarytmu $\\log_3 81$.',
    answer: '4',
    acceptedAnswers: ['4', '4,0'],
    tags: ['logarytmy'],
    skills: ['funkcje-logarytmy'],
    hints: ['Pytanie: $3$ do której potęgi daje $81$?', '$81 = 3^{4}$'],
    solution: '$\\log_3 81 = 4$, bo $3^{4} = 81$.',
    steps: ['Zapisz $81$ jako potęgę trójki.', 'Odczytaj wykładnik: $4$.'],
  },
  {
    id: 'fn-09',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-logarytmy',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Oblicz $\\log_2 40 - \\log_2 5$.',
    answer: '3',
    acceptedAnswers: ['3', '3,0'],
    tags: ['logarytmy', 'prawa'],
    skills: ['funkcje-logarytmy'],
    hints: ['Użyj prawa: $\\log_a x - \\log_a y = \\log_a \\frac{x}{y}$.', '$\\frac{40}{5} = 8$'],
    solution: '$\\log_2 40 - \\log_2 5 = \\log_2 \\frac{40}{5} = \\log_2 8 = 3$.',
    steps: ['Połącz w jeden logarytm ilorazu.', '$\\log_2 8 = 3$.'],
  },
  {
    id: 'fn-10',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-logarytmy',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Jeżeli $\\log_2 6 = m$, to $\\log_2 24$ jest równe:',
    options: ['$m + 2$', '$2m$', '$m + 4$', '$3m$'],
    answer: '$m + 2$',
    tags: ['logarytmy', 'prawa'],
    skills: ['funkcje-logarytmy'],
    hints: ['$24 = 4 \\cdot 6$', 'Zastosuj prawo o iloczynie i oblicz $\\log_2 4$.'],
    solution: '$\\log_2 24 = \\log_2 (4 \\cdot 6) = \\log_2 4 + \\log_2 6 = 2 + m$.',
    steps: ['Rozłóż $24 = 4 \\cdot 6$.', 'Dodaj $\\log_2 4 = 2$: wynik $m + 2$.'],
  },
  {
    id: 'fn-11',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-logarytmy',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Rozwiąż równanie $2^{x+1} = 32$. Podaj $x$.',
    answer: '4',
    acceptedAnswers: ['4', '4,0'],
    tags: ['wykladnicze'],
    skills: ['funkcje-wykladnicza'],
    hints: ['Zapisz $32$ jako potęgę dwójki.', '$32 = 2^{5}$, więc $x + 1 = 5$.'],
    solution: '$2^{x+1} = 2^{5} \\iff x + 1 = 5$, więc $x = 4$.',
    steps: ['Zapisz $32 = 2^5$.', 'Porównaj wykładniki: $x = 4$.'],
  },
  {
    id: 'fn-12',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-logarytmy',
    type: 'numeric',
    difficulty: 3,
    points: 1,
    prompt: 'Rozwiąż równanie $\\left(\\frac{1}{3}\\right)^{x} = 81$. Podaj $x$.',
    answer: '-4',
    acceptedAnswers: ['-4', '−4', '-4,0'],
    tags: ['wykladnicze'],
    skills: ['funkcje-wykladnicza'],
    hints: ['$\\frac{1}{3} = 3^{-1}$', '$81 = 3^{4}$'],
    solution: '$\\left(\\frac{1}{3}\\right)^{x} = 3^{-x} = 3^{4}$, więc $-x = 4$ i $x = -4$.',
    steps: ['Zamień podstawy na $3$: $3^{-x} = 3^4$.', 'Porównaj wykładniki: $x = -4$.'],
  },
  {
    id: 'fn-13',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-wlasnosci',
    type: 'open',
    difficulty: 3,
    points: 3,
    prompt: 'Funkcja $f$ jest określona wzorem $f(x) = \\frac{2x - 4}{x + 1}$ dla $x \\neq -1$. Wyznacz wszystkie wartości $x$, dla których $f(x) = 2$.',
    answer: 'brak rozwiązań',
    acceptedAnswers: ['brak rozwiazan', 'brak', 'zbior pusty'],
    tags: ['wymierne', 'rownania'],
    skills: ['funkcje-miejsca-zerowe', 'funkcje-dziedzina-wzor'],
    hints: ['Podstaw $f(x) = 2$ i pomnóż obie strony przez $x + 1$.', 'Zobacz, co zostaje z równania.'],
    solution: '$\\frac{2x-4}{x+1} = 2$, mnożymy obie strony przez $x+1$ (przy $x \\neq -1$): $2x - 4 = 2x + 2$, co po redukcji daje $-4 = 2$ — sprzeczność. Równanie nie ma rozwiązań.',
    steps: ['Pomnóż przez $x + 1$.', 'Otrzymujesz $-4 = 2$ — sprzeczność.', 'Wniosek: brak rozwiązań.'],
    rubric: [
      { criterion: 'Poprawne przekształcenie równania (mnożenie przez $x+1$)', points: 1 },
      { criterion: 'Wykrycie sprzeczności $-4 = 2$', points: 1 },
      { criterion: 'Jawny wniosek o braku rozwiązań', points: 1 },
    ],
  },
  {
    id: 'fn-14',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-logarytmy',
    type: 'open',
    difficulty: 4,
    points: 4,
    prompt: 'Wykaż, że dla każdej liczby rzeczywistej $x > 0$ zachodzi równość $\\log_{\\frac{1}{2}} x = -\\log_2 x$, a następnie zapisz iloczyn $\\log_2 x \\cdot \\log_{\\frac{1}{2}} x$ w prostszej postaci.',
    answer: '-(log_2 x)^{2}',
    acceptedAnswers: ['-(log_2 x)^2', '-(\\log_2 x)^{2}', 'minus (log_2 x)^2'],
    tags: ['logarytmy', 'prawa'],
    skills: ['funkcje-logarytmy'],
    hints: ['Zapisz $\\log_{\\frac{1}{2}} x$ przez podstawę $2$: $\\log_{\\frac{1}{2}} x = \\frac{\\log_2 x}{\\log_2 \\frac{1}{2}}$.', 'Oblicz $\\log_2 \\frac{1}{2} = -1$.'],
    solution: 'Z własności zamiany podstawy: $\\log_{\\frac{1}{2}} x = \\frac{\\log_2 x}{\\log_2 \\frac{1}{2}} = \\frac{\\log_2 x}{-1} = -\\log_2 x$ (dla $x > 0$). Zatem $\\log_2 x \\cdot \\log_{\\frac{1}{2}} x = \\log_2 x \\cdot \\left(-\\log_2 x\\right) = -\\left(\\log_2 x\\right)^{2}$.',
    steps: ['Zamień podstawę: mianownik $\\log_2 \\frac{1}{2} = -1$.', 'Wniosek: $\\log_{1/2} x = -\\log_2 x$.', 'Iloczyn: $-(\\log_2 x)^2$.'],
    rubric: [
      { criterion: 'Zamiana podstawy i wyznaczenie $\\log_{\\frac{1}{2}} x = -\\log_2 x$', points: 2 },
      { criterion: 'Zapis iloczynu w postaci $-(\\log_2 x)^2$', points: 2 },
    ],
  },
  {
    id: 'fn-15',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-wlasnosci',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Na rysunku przedstawiono wykres funkcji $f$. Podaj najmniejszą wartość funkcji $f$.',
    figure: {
      kind: 'plot',
      xMin: -4,
      xMax: 4,
      yMin: -5.5,
      yMax: 6,
      xLabel: 'x',
      yLabel: 'y',
      caption: 'Wykres funkcji f.',
      curves: [{ expr: 'x^2-4', label: 'f', color: 'violet' }],
    },
    answer: '-4',
    acceptedAnswers: ['-4', '-4,0'],
    tags: ['odczyt-wykresu', 'wartosci'],
    skills: ['funkcje-odczyt-wykresu'],
    hints: ['Najmniejsza wartość to rzędna najniższego punktu wykresu.', 'Najniższy punkt leży na osi $OY$ — odczytaj jego drugą współrzędną.'],
    solution: 'Najniższy punkt wykresu to wierzchołek paraboli $(0, -4)$, więc najmniejsza wartość funkcji wynosi $-4$.',
    steps: ['Znajdź na wykresie najniższy punkt.', 'Odczytaj jego drugą współrzędną: $y = -4$.', 'Odpowiedź: $-4$.'],
  },
  {
    id: 'fn-16',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-wlasnosci',
    type: 'open',
    difficulty: 3,
    points: 4,
    prompt: 'Na rysunku przedstawiono wykres funkcji $f$. Opisz na jego podstawie: dziedzinę, zbiór wartości, miejsca zerowe oraz przedziały monotoniczności.',
    figure: {
      kind: 'plot',
      xMin: -4,
      xMax: 4,
      yMin: -5.5,
      yMax: 6,
      xLabel: 'x',
      yLabel: 'y',
      caption: 'Wykres funkcji f.',
      curves: [{ expr: 'x^2-4', label: 'f', color: 'violet' }],
    },
    answer: 'dziedzina: R; zbiór wartości: [-4, ∞); miejsca zerowe: -2 i 2; maleje na (-∞, 0], rośnie na [0, ∞)',
    tags: ['odczyt-wykresu', 'monotonicznosc'],
    skills: ['funkcje-odczyt-wykresu'],
    hints: ['Dziedzina to rzut wykresu na oś $OX$, zbiór wartości — na oś $OY$.', 'Miejsca zerowe odczytujesz tam, gdzie wykres przecina oś $OX$.', 'Monotoniczność czytaj od lewej do prawej.'],
    solution: 'Funkcja jest określona dla wszystkich liczb rzeczywistych, więc dziedzina to $\\mathbb{R}$. Wykres przyjmuje wartości od $-4$ w górę, więc zbiór wartości to $[-4, \\infty)$. Wykres przecina oś $OX$ dla $x = -2$ i $x = 2$ — to miejsca zerowe. Do wierzchołka $(0, -4)$ funkcja maleje, a dalej rośnie: maleje na $(-\\infty, 0]$, rośnie na $[0, \\infty)$.',
    steps: ['Odczytaj rzut wykresu na oś $OX$ — dziedzina.', 'Odczytaj rzut na oś $OY$ — zbiór wartości.', 'Znajdź punkty przecięcia z osią $OX$ — miejsca zerowe.', 'Podaj przedziały, na których wykres opada i rośnie.'],
    rubric: [
      { criterion: 'Dziedzina (wszystkie liczby rzeczywiste)', points: 1 },
      { criterion: 'Zbiór wartości $[-4, \\infty)$', points: 1 },
      { criterion: 'Miejsca zerowe $-2$ i $2$', points: 1 },
      { criterion: 'Przedziały monotoniczności', points: 1 },
    ],
  },
  {
    id: 'fn-17',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-odwrotna',
    type: 'numeric',
    level: 'extended',
    difficulty: 2,
    points: 1,
    prompt: 'Funkcja $f(x) = 2x + 3$ jest różnowartościowa. Oblicz $f^{-1}(7)$.',
    answer: '2',
    tags: ['odwrotna'],
    skills: ['funkcje-odwrotna'],
    hints: ['$f^{-1}(7)$ to argument, dla którego $f(x) = 7$.', 'Rozwiąż $2x + 3 = 7$.'],
    solution: 'Szukamy $x$, dla którego $f(x) = 7$: $2x + 3 = 7$, stąd $x = 2$. Zatem $f^{-1}(7) = 2$. (Wzór: $f^{-1}(x) = \\frac{x-3}{2}$, więc $f^{-1}(7) = 2$.)',
    steps: ['Zapisz warunek $2x + 3 = 7$.', 'Rozwiąż: $x = 2$.', 'Odpowiedz: $f^{-1}(7) = 2$.'],
  },
  {
    id: 'fn-18',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-odwrotna',
    type: 'single_choice',
    level: 'extended',
    difficulty: 2,
    points: 1,
    prompt: 'Funkcja odwrotna do $f(x) = x - 4$ ma wzór:',
    options: ['$f^{-1}(x) = x + 4$', '$f^{-1}(x) = \\frac{1}{x-4}$', '$f^{-1}(x) = x - 4$', '$f^{-1}(x) = 4 - x$'],
    answer: '$f^{-1}(x) = x + 4$',
    tags: ['odwrotna'],
    skills: ['funkcje-odwrotna'],
    hints: ['Rozwiąż $y = x - 4$ względem $x$.', '$f^{-1}$ to nie $\\frac{1}{f}$.'],
    solution: 'Z $y = x - 4$ mamy $x = y + 4$, więc po zamianie zmiennych $f^{-1}(x) = x + 4$. Sprawdzenie: $f^{-1}(f(1)) = f^{-1}(-3) = 1$ — zgadza się.',
    steps: ['Wyznacz $x$ z $y = x - 4$.', 'Zamień zmienne i wskaż $x + 4$.'],
  },
  {
    id: 'fn-19',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-odwrotna',
    type: 'text',
    level: 'extended',
    difficulty: 3,
    points: 2,
    prompt: 'Wyznacz wzór funkcji odwrotnej do $f(x) = 3x - 1$.',
    answer: '(x+1)/3',
    acceptedAnswers: ['(x+1)/3', '\\frac{x+1}{3}', 'x/3+1/3', '(x + 1)/3'],
    tags: ['odwrotna'],
    skills: ['funkcje-odwrotna'],
    hints: ['Napisz $y = 3x - 1$ i wyznacz $x$.', 'Podziel przez $3$ po dodaniu $1$.'],
    solution: 'Z $y = 3x - 1$ mamy $3x = y + 1$, więc $x = \\frac{y+1}{3}$. Po zamianie zmiennych $f^{-1}(x) = \\frac{x+1}{3}$.',
    steps: ['Zapisz $y = 3x - 1$.', 'Wyznacz $x = \\frac{y+1}{3}$.', 'Zamień zmienne: $f^{-1}(x) = \\frac{x+1}{3}$.'],
  },
  {
    id: 'fn-20',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-odwrotna',
    type: 'numeric',
    level: 'extended',
    difficulty: 3,
    points: 1,
    prompt: 'Dla $f(x) = x^{2}$ i $g(x) = x + 1$ oblicz $f\\bigl(g(2)\\bigr)$.',
    answer: '9',
    tags: ['zlozenie'],
    skills: ['funkcje-zlozenie'],
    hints: ['Najpierw oblicz $g(2)$.', 'Potem podstaw wynik do $f$.'],
    solution: '$g(2) = 2 + 1 = 3$, więc $f(g(2)) = f(3) = 3^{2} = 9$.',
    steps: ['Oblicz $g(2) = 3$.', 'Oblicz $f(3) = 9$.'],
  },
  {
    id: 'fn-21',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-przeksztalcenia',
    type: 'single_choice',
    level: 'extended',
    difficulty: 2,
    points: 1,
    prompt: 'Wykres $y = f(x - 3) + 1$ powstaje z wykresu $y = f(x)$ przez przesunięcie o wektor:',
    options: ['$[3, 1]$', '$[-3, 1]$', '$[3, -1]$', '$[1, 3]$'],
    answer: '$[3, 1]$',
    tags: ['przeksztalcenia'],
    skills: ['funkcje-przeksztalcenia'],
    hints: ['$f(x - p)$ przesuwa w prawo o $p$.', '$f(x) + q$ przesuwa w górę o $q$.'],
    solution: '$f(x - 3)$ to przesunięcie w prawo o $3$, a $+1$ — w górę o $1$. Łącznie wektor $[3, 1]$.',
    steps: ['Odczytaj przesunięcie poziome: $3$ w prawo.', 'Odczytaj przesunięcie pionowe: $1$ w górę.', 'Zapisz wektor $[3, 1]$.'],
  },
  {
    id: 'fn-22',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-przeksztalcenia',
    type: 'text',
    level: 'extended',
    difficulty: 3,
    points: 2,
    prompt: 'Wykres funkcji $f(x) = x^{2}$ przesunięto o $2$ jednostki w prawo i $3$ w górę. Podaj wzór otrzymanej funkcji $g$.',
    answer: '(x-2)^2+3',
    acceptedAnswers: ['(x-2)^2+3', '(x - 2)^2 + 3', 'x^2-4x+7'],
    tags: ['przeksztalcenia'],
    skills: ['funkcje-przeksztalcenia'],
    hints: ['Przesunięcie o wektor $[2, 3]$ daje $g(x) = f(x - 2) + 3$.', 'Podstaw $f(u) = u^{2}$.'],
    solution: 'Przesunięcie o wektor $[2, 3]$: $g(x) = f(x - 2) + 3 = (x-2)^{2} + 3$. Rozwinięta postać to $x^{2} - 4x + 7$; obie są poprawne.',
    steps: ['Zapisz $g(x) = f(x-2) + 3$.', 'Podstaw $f(x-2) = (x-2)^{2}$.', 'Wynik: $(x-2)^{2} + 3$.'],
  },
  {
    id: 'fn-23',
    topicSlug: 'funkcje',
    lessonSlug: 'funkcje-przeksztalcenia',
    type: 'open',
    level: 'extended',
    difficulty: 4,
    points: 3,
    prompt: 'Wykres funkcji $f(x) = 2^{x}$ odbito symetrycznie względem osi $OX$, a następnie przesunięto o $1$ jednostkę w górę. Podaj wzór otrzymanej funkcji i jej zbiór wartości.',
    answer: 'g(x)=-2^x+1; zbiór wartości (-∞,1)',
    tags: ['przeksztalcenia'],
    skills: ['funkcje-przeksztalcenia'],
    hints: ['Odbicie przez oś $OX$: $y = -f(x)$.', 'Potem przesunięcie pionowe: $+1$.'],
    solution: 'Odbicie przez oś $OX$ daje $y = -2^{x}$, a przesunięcie w górę o $1$: $g(x) = -2^{x} + 1$. Ponieważ $2^{x} > 0$, mamy $-2^{x} < 0$ i $g(x) < 1$; funkcja przyjmuje wartości dowolnie bliskie $1$ od dołu, więc zbiór wartości to $(-\\infty, 1)$.',
    steps: ['Odbij: $y = -2^{x}$.', 'Przesuń w górę o $1$: $g(x) = -2^{x} + 1$.', 'Wyznacz zbiór wartości: $(-\\infty, 1)$.'],
    rubric: [
      { criterion: 'Poprawne odbicie przez oś $OX$', points: 1 },
      { criterion: 'Poprawne przesunięcie w górę', points: 1 },
      { criterion: 'Poprawny zbiór wartości $(-\\infty, 1)$', points: 1 },
    ],
  },
]
