import type { ContentTask } from '@/content/types'

/**
 * Bank zadań do działu „Geometria analityczna”. Kody `ge-*` są stabilnym kluczem importu.
 */
export const geometriaTasks: ContentTask[] = [
  {
    id: 'ge-01',
    topicSlug: 'geometria',
    lessonSlug: 'geometria-proste',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Oblicz współczynnik kierunkowy prostej przechodzącej przez punkty $A(1, 2)$ i $B(4, 8)$.',
    answer: '2',
    acceptedAnswers: ['2', '2,0'],
    tags: ['rownanie-prostej'],
    skills: ['geometria-prosta'],
    hints: ['Użyj wzoru na współczynnik kierunkowy z dwóch punktów.', '$k = \\frac{y_{2} - y_{1}}{x_{2} - x_{1}}$'],
    solution: '$k = \\frac{8 - 2}{4 - 1} = \\frac{6}{3} = 2$.',
    steps: ['Oblicz różnicę rzędnych: $8 - 2 = 6$.', 'Oblicz różnicę odciętych: $4 - 1 = 3$.', 'Współczynnik kierunkowy: $k = \\frac{6}{3} = 2$.'],
  },
  {
    id: 'ge-02',
    topicSlug: 'geometria',
    lessonSlug: 'geometria-proste',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Proste $y = 3x + 1$ i $y = 3x - 5$ są:',
    options: ['równoległe', 'prostopadłe', 'przebiegające w jednym punkcie', 'tożsame'],
    answer: 'równoległe',
    tags: ['polozenie-prostych'],
    skills: ['geometria-prosta'],
    hints: ['Porównaj współczynniki kierunkowe obu prostych.', 'Dla równoległości wystarczy równość współczynników kierunkowych.'],
    solution: 'Oba współczynniki kierunkowe wynoszą $3$, a wyrazy wolne są różne, więc proste są różne, lecz równoległe: $y = 3x + 1$ i $y = 3x - 5$ nigdy się nie przecinają.',
    steps: ['Porównaj współczynniki kierunkowe: $3 = 3$.', 'Sprawdź wyrazy wolne: $1 \\neq -5$.', 'Wniosek: proste są równoległe.'],
  },
  {
    id: 'ge-03',
    topicSlug: 'geometria',
    lessonSlug: 'geometria-proste',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Prosta przechodząca przez punkty $A(1, 3)$ i $B(3, 7)$ ma współczynnik kierunkowy równy $k$. Wyznacz współczynnik kierunkowy prostej prostopadłej do niej.',
    answer: '-1/2',
    acceptedAnswers: ['-1/2', '−1/2', '-0,5', '-0.5'],
    tags: ['prostopadlosc'],
    skills: ['geometria-prosta'],
    hints: ['Najpierw oblicz $k$ z dwóch punktów.', 'Dla prostopadłości iloczyn współczynników musi być równy $-1$.'],
    solution: '$k = \\frac{7 - 3}{3 - 1} = 2$. Iloczyn współczynników prostopadłych prostych wynosi $-1$, więc $k_{2} = \\frac{-1}{2} = -\\frac{1}{2}$.',
    steps: ['Oblicz $k = \\frac{4}{2} = 2$.', 'Skorzystaj z warunku $k \\cdot k_{2} = -1$.', 'Oblicz $k_{2} = -\\frac{1}{2}$.'],
  },
  {
    id: 'ge-04',
    topicSlug: 'geometria',
    lessonSlug: 'geometria-punkty',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Oblicz odległość między punktami $A(-1, 3)$ i $B(4, -1)$.',
    answer: '√41',
    acceptedAnswers: ['√41', 'sqrt(41)', '6,4', '6.4'],
    tags: ['odleglosc-punktow'],
    skills: ['geometria-odleglosc'],
    hints: ['Zastosuj wzór na odległość dwóch punktów.', 'Najpierw oblicz różnice współrzędnych: $\\Delta x = 5$, $\\Delta y = -4$.'],
    solution: '$|AB| = \\sqrt{(4 - (-1))^{2} + (-1 - 3)^{2}} = \\sqrt{5^{2} + (-4)^{2}} = \\sqrt{25 + 16} = \\sqrt{41} \\approx 6{,}4$.',
    steps: ['Oblicz różnice: $\\Delta x = 5$, $\\Delta y = -4$.', 'Kwadraty: $25$ i $16$.', 'Suma: $41$, więc $|AB| = \\sqrt{41}$.'],
  },
  {
    id: 'ge-05',
    topicSlug: 'geometria',
    lessonSlug: 'geometria-punkty',
    type: 'numeric',
    difficulty: 1,
    points: 2,
    prompt: 'Wyznacz środek odcinka $AB$, gdzie $A(2, -4)$ i $B(6, 2)$, a następnie podaj sumę jego współrzędnych.',
    answer: '3',
    acceptedAnswers: ['3'],
    tags: ['srodek-odcinka'],
    skills: ['geometria-odleglosc'],
    hints: ['Współrzędne środka to średnie arytmetyczne współrzędnych końców.', '$x_{S} = \\frac{2 + 6}{2}$, $y_{S} = \\frac{-4 + 2}{2}$'],
    solution: '$x_{S} = \\frac{2 + 6}{2} = 4$, $y_{S} = \\frac{-4 + 2}{2} = -1$. Środek to $S(4, -1)$, suma współrzędnych wynosi $4 + (-1) = 3$.',
    steps: ['Oblicz $x_{S} = \\frac{2 + 6}{2} = 4$.', 'Oblicz $y_{S} = \\frac{-4 + 2}{2} = -1$.', 'Dodaj: $4 + (-1) = 3$.'],
  },
  {
    id: 'ge-06',
    topicSlug: 'geometria',
    lessonSlug: 'geometria-proste',
    type: 'open',
    difficulty: 3,
    points: 3,
    prompt: 'Wyznacz równanie prostej przechodzącej przez punkt $A(1, -2)$ i prostopadłej do prostej $y = 2x + 5$.',
    answer: 'y = -1/2 x - 3/2',
    acceptedAnswers: ['y = -1/2 x - 3/2', 'y = -0,5x - 1,5', 'x + 2y + 3 = 0', '2x + 4y + 6 = 0'],
    tags: ['rownanie-prostej', 'prostopadlosc'],
    skills: ['geometria-prosta'],
    hints: ['Współczynnik kierunkowy prostej danej to $k = 2$.', 'Dla prostopadłości $k_{2} \\cdot 2 = -1$, czyli $k_{2} = -\\frac{1}{2}$.'],
    solution: 'Współczynnik kierunkowy prostej $y = 2x + 5$ wynosi $2$, więc prosta prostopadła ma $k_{2} = -\\frac{1}{2}$. Równanie przechodzące przez $A(1, -2)$ w postaci punktowo-kierunkowej: $y + 2 = -\\frac{1}{2}(x - 1)$. Po uproszczeniu: $y = -\\frac{1}{2}x - \\frac{3}{2}$. Równoważnie $x + 2y + 3 = 0$.',
    steps: ['Oblicz współczynnik kierunkowy prostej prostopadłej: $k_{2} = -\\frac{1}{2}$.', 'Zapisz postać punktowo-kierunkową: $y + 2 = -\\frac{1}{2}(x - 1)$.', 'Uprość do $y = -\\frac{1}{2}x - \\frac{3}{2}$.'],
    rubric: [
      { criterion: 'Wyznaczenie współczynnika kierunkowego prostej prostopadłej', points: 1 },
      { criterion: 'Zapisanie postaci punktowo-kierunkowej z użyciem punktu $A$', points: 1 },
      { criterion: 'Poprawne uproszczenie do postaci ogólnej lub kierunkowej', points: 1 },
    ],
  },
  {
    id: 'ge-07',
    topicSlug: 'geometria',
    lessonSlug: 'geometria-punkty',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'Oblicz odległość punktu $P(3, 4)$ od prostej $2x - y - 7 = 0$.',
    answer: '√5',
    acceptedAnswers: ['√5', 'sqrt(5)', '2,24', '2.24'],
    tags: ['odleglosc-od-prostej'],
    skills: ['geometria-odleglosc'],
    hints: ['Zastosuj wzór $d = \\frac{|Ax_{0} + By_{0} + C|}{\\sqrt{A^{2} + B^{2}}}$.', 'Nie zapomnij o wartości bezwzględnej w liczniku.'],
    solution: '$d = \\frac{|2 \\cdot 3 - 4 - 7|}{\\sqrt{2^{2} + (-1)^{2}}} = \\frac{|-5|}{\\sqrt{5}} = \\frac{5}{\\sqrt{5}} = \\sqrt{5} \\approx 2{,}24$.',
    steps: ['Podstaw do wzoru: $A = 2$, $B = -1$, $C = -7$.', 'Oblicz licznik: $|6 - 4 - 7| = 5$.', 'Oblicz mianownik: $\\sqrt{5}$ i uprość: $d = \\sqrt{5}$.'],
  },
  {
    id: 'ge-08',
    topicSlug: 'geometria',
    lessonSlug: 'geometria-punkty',
    type: 'open',
    level: 'extended',
    difficulty: 4,
    points: 4,
    prompt: 'Wyznacz odległość punktu $P(6, 1)$ od prostej przechodzącej przez punkty $A(0, 2)$ i $B(4, -2)$.',
    answer: '5√2/2',
    acceptedAnswers: ['5√2/2', '5/√2', '3,54', '3.54', '≈3,54'],
    tags: ['odleglosc-od-prostej', 'rownanie-prostej'],
    skills: ['geometria-odleglosc'],
    hints: ['Najpierw wyznacz równanie prostej przechodzącej przez $A$ i $B$.', 'Prosta ma współczynnik kierunkowy $-1$ i przecina oś $y$ w punkcie $2$.'],
    solution: 'Współczynnik kierunkowy prostej: $k = \\frac{-2 - 2}{4 - 0} = -1$. Równanie: $y = -x + 2$, czyli $x + y - 2 = 0$. Odległość punktu $P(6, 1)$ od tej prostej: $d = \\frac{|6 + 1 - 2|}{\\sqrt{1 + 1}} = \\frac{5}{\\sqrt{2}} = \\frac{5\\sqrt{2}}{2} \\approx 3{,}54$.',
    steps: ['Oblicz współczynnik kierunkowy prostej $AB$: $k = -1$.', 'Zapisz ją w postaci ogólnej: $x + y - 2 = 0$.', 'Zastosuj wzór na odległość: $d = \\frac{5}{\\sqrt{2}}$.', 'Usuń niewymierność: $d = \\frac{5\\sqrt{2}}{2}$.'],
    rubric: [
      { criterion: 'Wyznaczenie równania prostej przechodzącej przez $A$ i $B$', points: 1 },
      { criterion: 'Zastosowanie wzoru na odległość punktu od prostej', points: 2 },
      { criterion: 'Uproszczenie wyniku do $\\frac{5\\sqrt{2}}{2}$', points: 1 },
    ],
  },
  {
    id: 'ge-09',
    topicSlug: 'geometria',
    lessonSlug: 'geometria-okrag-analityczny',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'Okrąg ma równanie $x^{2} + y^{2} - 4x + 2y - 4 = 0$. Oblicz jego promień.',
    answer: '3',
    acceptedAnswers: ['3'],
    tags: ['rownanie-okregu', 'promien'],
    skills: ['geometria-okrag'],
    hints: ['Uzupełnij do postaci środkowej: $(x - p)^{2} + (y - q)^{2} = r^{2}$.', 'Dodaj do obu stron wartość $p^{2} + q^{2}$ i odejmij wyraz wolny.'],
    solution: 'Uzupełnienie: $(x - 2)^{2} - 4 + (y + 1)^{2} - 1 = 4$, czyli $(x - 2)^{2} + (y + 1)^{2} = 9$. Promień to $r = 3$.',
    steps: ['Dopełnij kwadraty: $(x - 2)^{2} + (y + 1)^{2} = 9$.', 'Odczytaj promień: $r = \\sqrt{9}$.', 'Odpowiedź: $r = 3$.'],
  },
  {
    id: 'ge-10',
    topicSlug: 'geometria',
    lessonSlug: 'geometria-okrag-analityczny',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Środek okręgu o równaniu $x^{2} + y^{2} - 8x + 6y = 0$ to punkt:',
    options: ['$(4, -3)$', '$(-4, 3)$', '$(4, 3)$', '$(-4, -3)$'],
    answer: '$(4, -3)$',
    tags: ['rownanie-okregu', 'srodek'],
    skills: ['geometria-okrag'],
    hints: ['Środek ma współrzędne $(-\\frac{A}{2}, -\\frac{B}{2})$.', 'Tutaj $A = -8$ i $B = 6$.'],
    solution: 'Środek to $\\left(-\\frac{-8}{2}, -\\frac{6}{2}\\right) = (4, -3)$.',
    steps: ['Weź współczynnik przy $x$: $A = -8$, więc $-\\frac{A}{2} = 4$.', 'Weź współczynnik przy $y$: $B = 6$, więc $-\\frac{B}{2} = -3$.', 'Środek: $(4, -3)$.'],
  },
  {
    id: 'ge-11',
    topicSlug: 'geometria',
    lessonSlug: 'geometria-okrag-analityczny',
    type: 'open',
    level: 'extended',
    difficulty: 3,
    points: 3,
    prompt: 'Wyznacz punkty przecięcia prostej $y = 2$ z okręgiem $x^{2} + y^{2} = 13$.',
    answer: '(-3, 2) i (3, 2)',
    acceptedAnswers: ['(-3, 2) i (3, 2)', '(3,2) i (-3,2)', '(-3,2), (3,2)', 'x = ±3, y = 2'],
    tags: ['przeciecia', 'rownanie-okregu'],
    skills: ['geometria-przeciecia', 'geometria-okrag'],
    hints: ['Podstaw $y = 2$ do równania okręgu.', 'Po podstawieniu zostanie równanie $x^{2} = 9$.'],
    solution: 'Podstawiamy $y = 2$: $x^{2} + 2^{2} = 13$, czyli $x^{2} = 9$, więc $x = 3$ lub $x = -3$. Punkty przecięcia to $(3, 2)$ i $(-3, 2)$.',
    steps: ['Podstaw $y = 2$ do równania okręgu.', 'Oblicz $x^{2} = 13 - 4 = 9$.', 'Podaj oba punkty: $(3, 2)$ i $(-3, 2)$.'],
    rubric: [
      { criterion: 'Podstawienie $y = 2$ do równania okręgu', points: 1 },
      { criterion: 'Rozwiązanie równania $x^{2} = 9$', points: 1 },
      { criterion: 'Podanie obu punktów przecięcia', points: 1 },
    ],
  },
  {
    id: 'ge-12',
    topicSlug: 'geometria',
    lessonSlug: 'geometria-okrag-analityczny',
    type: 'open',
    level: 'extended',
    difficulty: 4,
    points: 4,
    prompt: 'Wyznacz punkty przecięcia prostej $y = x + 1$ z okręgiem $x^{2} + y^{2} = 5$.',
    answer: '(1, 2) i (-2, -1)',
    acceptedAnswers: ['(1, 2) i (-2, -1)', '(1,2) i (-2,-1)', '(-2,-1), (1,2)'],
    tags: ['przeciecia', 'rownanie-okregu', 'uklad'],
    skills: ['geometria-przeciecia', 'geometria-okrag'],
    hints: ['Zamiast rozwiązywać układ, wyraź $y$ przez $x$ i podstaw do równania okręgu.', 'Dostaniesz równanie kwadratowe: $2x^{2} + 2x - 4 = 0$.'],
    solution: 'Podstawiamy $y = x + 1$: $x^{2} + (x + 1)^{2} = 5$, czyli $2x^{2} + 2x + 1 = 5$, więc $2x^{2} + 2x - 4 = 0$. Dzieląc przez $2$: $x^{2} + x - 2 = 0$, stąd $(x + 2)(x - 1) = 0$. Zatem $x = -2$ albo $x = 1$. Odpowiadające wartości $y$: dla $x = -2$ mamy $y = -1$, dla $x = 1$ mamy $y = 2$. Punkty: $(-2, -1)$ i $(1, 2)$.',
    steps: ['Podstaw $y = x + 1$ do równania okręgu.', 'Otrzymaj i uprość równanie: $x^{2} + x - 2 = 0$.', 'Zrób rozkład na czynniki: $(x + 2)(x - 1) = 0$.', 'Oblicz $y$ dla obu wartości $x$ i podaj punkty.'],
    rubric: [
      { criterion: 'Sprowadzenie zadania do równania kwadratowego', points: 2 },
      { criterion: 'Rozwiązanie równania kwadratowego', points: 1 },
      { criterion: 'Wyznaczenie współrzędnych obu punktów', points: 1 },
    ],
  },
]
