import type { ContentTask } from '@/content/types'

export const graniceTasks: ContentTask[] = [
  { id: 'gr-01', topicSlug: 'granice', lessonSlug: 'granice-obliczanie', type: 'numeric', difficulty: 1, points: 1, prompt: 'Oblicz $\\lim_{x\\to2}3x+1$.', answer: '7', tags: ['granica'], skills: ['granice-obliczanie'], hints: ['Funkcja jest ciągła.'], solution: '$\\lim_{x\\to2}(3x+1)=3\\cdot2+1=7$.', steps: ['Podstaw 2.', 'Oblicz wynik.'] },
  { id: 'gr-02', topicSlug: 'granice', lessonSlug: 'granice-obliczanie', type: 'numeric', difficulty: 2, points: 1, prompt: 'Oblicz $\\lim_{x\\to1}\\frac{x^2-1}{x-1}$.', answer: '2', tags: ['skracanie'], skills: ['granice-obliczanie'], hints: ['Rozkład licznik.', 'Skróć czynnik $x-1$.'], solution: '$\\lim_{x\\to1}\\frac{(x-1)(x+1)}{x-1}=\\lim_{x\\to1}(x+1)=2$.', steps: ['Rozkład różnicę kwadratów.', 'Skróć czynnik.', 'Podstaw 1.'] },
  { id: 'gr-03', topicSlug: 'granice', lessonSlug: 'granice-obliczanie', type: 'single_choice', difficulty: 2, points: 1, prompt: 'Jaka jest granica $\\lim_{x\\to3}\\frac{9-x^2}{x-3}$?', options: ['$0$', '$3$', '$-6$', 'nie istnieje'], answer: '$-6$', tags: ['granica'], skills: ['granice-obliczanie'], hints: ['Rozkład $9-x^2$.'], solution: '$9-x^2=-(x-3)(x+3)$, więc po skróceniu granica wynosi $-\\lim_{x\\to3}(x+3)=-6$.', steps: ['Rozkład licznik.', 'Skróć $x-3$.', 'Oblicz.'] },
  { id: 'gr-04', topicSlug: 'granice', lessonSlug: 'granice-obliczanie', type: 'numeric', difficulty: 3, points: 2, prompt: 'Oblicz $\\lim_{x\\to0}\\frac{\\sin 2x}{x}$.', answer: '2', tags: ['trygonometria'], skills: ['granice-obliczanie'], hints: ['Zastosuj $\\lim_{u\\to0}\\frac{\\sin u}{u}=1$.'], solution: '$\\frac{\\sin2x}{x}=2\\frac{\\sin2x}{2x}$, więc granica to $2$.', steps: ['Zapisz iloczyn 2.', 'Zastosuj granicę podstawową.'] },
  { id: 'gr-05', topicSlug: 'granice', lessonSlug: 'granice-obliczanie', type: 'single_choice', difficulty: 3, points: 1, prompt: 'Który warunek opisuje ciągłość funkcji w punkcie?', options: ['$f(a)$ istnieje, granica istnieje i są równe', 'tylko $f(a)$ istnieje', 'tylko mianownik jest różny od zera', 'funkcja jest nieograniczona'], answer: '$f(a)$ istnieje, granica istnieje i są równe', tags: ['ciaglosc'], skills: ['granice-ciaglosc'], hints: ['Porównaj wartość i granicę.'], solution: 'Ciągłość oznacza $\\lim_{x\\to a}f(x)=f(a)$, przy czym punkt należy do dziedziny.', steps: ['Sprawdź dziedzinę.', 'Porównaj granicę i wartość.'] },
  { id: 'gr-06', topicSlug: 'granice', lessonSlug: 'granice-obliczanie', type: 'open', difficulty: 3, points: 3, prompt: 'Oblicz $\\lim_{x\\to-1}\\frac{x^2+2x+1}{x+1}$.', answer: '0', tags: ['granica'], skills: ['granice-obliczanie'], hints: ['Licznik to kwadrat $x+1$.'], solution: '$\\frac{(x+1)^2}{x+1}=x+1$ dla $x\\neq-1$, stąd granica wynosi $0$.', steps: ['Rozkład licznik.', 'Skróć.', 'Podstaw $-1$.'], rubric: [{ criterion: 'Rozkład i skrócenie', points: 1 }, { criterion: 'Obliczenie granicy', points: 1 }, { criterion: 'Zapis wyniku', points: 1 }] },
  { id: 'gr-07', topicSlug: 'granice', lessonSlug: 'granice-ciaglosc', type: 'open', difficulty: 4, points: 4, prompt: 'Zbadaj ciągłość $f(x)=\\frac{x+1}{x-2}$ na $\\mathbb R$ i podaj jej dziedzinę.', answer: 'ciągła na R\\setminus{2}', tags: ['ciaglosc', 'dziedzina'], skills: ['granice-ciaglosc'], hints: ['Najpierw wyznacz dziedzinę.', 'Funkcje różnicowe są ciągłe w punktach dziedziny.'], solution: '$D_f=\\mathbb R\\setminus\\{2\\}$. W każdym punkcie dziedziny mianownik jest różny od zera, więc funkcja jest ciągła na swojej dziedzinie.', steps: ['Wyznacz $x\\neq2$.', 'Zastosuj ciągłość iloroku.', 'Sformułuj wniosek.'], rubric: [{ criterion: 'Dziedzina', points: 1 }, { criterion: 'Uzasadnienie ciągłości', points: 2 }, { criterion: 'Poprawny wniosek', points: 1 }] },
  { id: 'gr-08', topicSlug: 'granice', lessonSlug: 'granice-obliczanie', type: 'single_choice', difficulty: 4, points: 1, prompt: 'Co robisz bezpośrednim podstawieniem, gdy otrzymujesz $\\frac00$?', options: ['upraszczasz wyrażenie', 'kończysz zadanie', 'zamieniasz mianownik przez zero', 'zmieniasz znak nierówności'], answer: 'upraszczasz wyrażenie', tags: ['granica'], skills: ['granice-obliczanie'], hints: ['Forma $0/0$ nie przesądza o granicy.'], solution: 'Trzeba skrócić wspólny czynnik lub zastosować inny rachunek graniczny.', steps: ['Rozpoznaj formę $0/0$.', 'Uprość wyrażenie.'] },
]
