import type { ContentTask } from '@/content/types'

/**
 * Bank zadań do działu „Kombinatoryka”. Kody `kb-*` są stabilnym kluczem importu.
 */
export const kombinatorykaTasks: ContentTask[] = [
  {
    id: 'kb-01',
    topicSlug: 'kombinatoryka',
    lessonSlug: 'kombinatoryka-mnozenie',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'W sklepie jest $5$ rodzajów bluzek i $4$ rodzaje spodni. Ile różnych kompletów „bluzka i spodnie” można złożyć?',
    answer: '20',
    acceptedAnswers: ['20'],
    tags: ['regula-mnozenia'],
    skills: ['kombinatoryka-mnozenie'],
    hints: ['Każdą bluzkę można połączyć z każdą parą spodni.', 'To kolejny, niezależny wybór — zastosuj regułę mnożenia.'],
    solution: 'Dla każdej z $5$ bluzek mamy $4$ możliwości spodni, więc liczba kompletów to $5 \\cdot 4 = 20$.',
    steps: ['Wybór bluzki: $5$ możliwości.', 'Wybór spodni: $4$ możliwości.', 'Reguła mnożenia: $5 \\cdot 4 = 20$.'],
  },
  {
    id: 'kb-02',
    topicSlug: 'kombinatoryka',
    lessonSlug: 'kombinatoryka-mnozenie',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'W sklepie jest $3$ rodzaje długopisów żelowych i $2$ rodzaje długopisów kulkowych. Kupujemy dokładnie jeden długopis. Ile jest możliwości wyboru?',
    answer: '5',
    acceptedAnswers: ['5'],
    tags: ['regula-dodawania'],
    skills: ['kombinatoryka-mnozenie'],
    hints: ['To dwa rozłączne przypadki: wybierasz długopis żelowy albo kulkowy.', 'Gdy zbiory możliwości się nie nakładają, liczby dodajemy.'],
    solution: 'Kupujący wybiera jeden z $3$ długopisów żelowych albo jeden z $2$ długopisów kulkowych. Zbiory są rozłączne, więc możliwości jest $3 + 2 = 5$.',
    steps: ['Rozpoznaj dwa rozłączne przypadki.', 'Zastosuj regułę dodawania: $3 + 2$.', 'Wynik: $5$ możliwości.'],
  },
  {
    id: 'kb-03',
    topicSlug: 'kombinatoryka',
    lessonSlug: 'kombinatoryka-mnozenie',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Ile trzycyfrowych liczb można utworzyć z cyfr $0, 1, 2, 3, 4, 5, 6, 7, 8, 9$, jeśli wszystkie cyfry w liczbie muszą być różne?',
    answer: '648',
    acceptedAnswers: ['648'],
    tags: ['regula-mnozenia', 'cyfry'],
    skills: ['kombinatoryka-mnozenie'],
    hints: ['Pierwsza cyfra nie może być zerem — są $9$ możliwości.', 'Na drugie miejsce zostaje $9$ cyfr, na trzecie $8$.'],
    solution: 'Liczby trzycyfrowe z różnymi cyframi: na pierwszym miejscu $9$ możliwości (bez zera), na drugim $9$ (zostaje $8$ cyfr, w tym zero), na trzecim $8$. Razem $9 \\cdot 9 \\cdot 8 = 648$.',
    steps: ['Pierwsza cyfra: $9$ wyborów (nie może być $0$).', 'Druga cyfra: $9$ wyborów.', 'Trzecia cyfra: $8$ wyborów.', 'Iloczyn: $9 \\cdot 9 \\cdot 8 = 648$.'],
  },
  {
    id: 'kb-04',
    topicSlug: 'kombinatoryka',
    lessonSlug: 'kombinatoryka-wzory',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Ile różnych dwuosobowych drużyn można wybrać z $6$ zawodników?',
    options: ['15', '30', '36', '16'],
    answer: '15',
    tags: ['kombinacje'],
    skills: ['kombinatoryka-wzory'],
    hints: ['Kolejność zawodników w drużynie nie ma znaczenia — to kombinacja, nie wariacja.', 'Zastosuj wzór: $C_{6}^{2} = \\frac{6!}{2! \\cdot 4!}$'],
    solution: 'To kombinacja, ponieważ kolejność zawodników w drużynie nie ma znaczenia: $C_{6}^{2} = \\frac{6!}{2! \\cdot 4!} = \\frac{6 \\cdot 5}{2} = 15$.',
    steps: ['Zastosuj wzór na kombinacje: $C_{6}^{2} = \\frac{6!}{2! \\cdot 4!}$.', 'Uprość: $\\frac{30}{2} = 15$.', 'Odpowiedź: $15$ drużyn.'],
  },
  {
    id: 'kb-05',
    topicSlug: 'kombinatoryka',
    lessonSlug: 'kombinatoryka-wzory',
    type: 'numeric',
    difficulty: 3,
    points: 3,
    prompt: 'Ile różnych sześcioliterowych ciągów można utworzyć z liter słowa MATURA? (Litery mogą się powtarzać tylko tak, jak w tym słowie — litera A występuje dwa razy.)',
    answer: '360',
    acceptedAnswers: ['360'],
    tags: ['permutacje', 'powtorzenia'],
    skills: ['kombinatoryka-wzory'],
    hints: ['Gdyby wszystkie litery były różne, byłooby to $6!$.', 'Dwie identyczne litery A „zajmują się miejscami”, więc dzielimy wynik przez $2!$.'],
    solution: 'Słowo MATURA ma $6$ liter, w tym dwie litery A. Permutacje z powtórzeniem dzielimy przez $2!$: $\\frac{6!}{2!} = \\frac{720}{2} = 360$.',
    steps: ['Policz permutacje 6 różnych liter: $6! = 720$.', 'Zidentyfikuj powtórzenie: litera A występuje $2$ razy.', 'Podziel przez $2!$: $360$.'],
  },
  {
    id: 'kb-06',
    topicSlug: 'kombinatoryka',
    lessonSlug: 'kombinatoryka-wzory',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'W zawodach biegowych bierze udział $5$ zawodników. Ile różnych par zawodników można ustawić na pierwszym i drugim miejscu? (Kolejność ma znaczenie.)',
    answer: '20',
    acceptedAnswers: ['20'],
    tags: ['wariacje'],
    skills: ['kombinatoryka-wzory'],
    hints: ['Kolejność ma znaczenie — to wariacja, nie kombinacja.', 'Na pierwsze miejsce: $5$ zawodników, na drugie: $4$ z pozostałych.'],
    solution: 'To wariacja: $V_{5}^{2} = 5 \\cdot 4 = 20$. Reguła mnożenia daje ten sam wynik — wybór pierwszego zawodnika jest niezależny od wyboru drugiego.',
    steps: ['Zastosuj wzór na wariacje: $V_{5}^{2}$.', 'Oblicz: $V_{5}^{2} = \\frac{5!}{3!} = \\frac{120}{6} = 20$.', 'Sprawdź: $5 \\cdot 4 = 20$.'],
  },
  {
    id: 'kb-07',
    topicSlug: 'kombinatoryka',
    lessonSlug: 'kombinatoryka-wzory',
    type: 'open',
    difficulty: 3,
    points: 3,
    prompt: 'Ile jest liczb trzycyfrowych o różnych cyfrach, w których nie występuje cyfra $0$?',
    answer: '504',
    acceptedAnswers: ['504'],
    tags: ['wylaczenia', 'cyfry'],
    skills: ['kombinatoryka-ograniczenia'],
    hints: ['Wszystkich liczb trzycyfrowych o różnych cyfrach jest $9 \\cdot 9 \\cdot 8$.', 'Policz, ile z nich zawiera zero: zero może stać na drugim albo na trzecim miejscu.'],
    solution: 'Wszystkich liczb trzycyfrowych o różnych cyfrach jest $9 \\cdot 9 \\cdot 8 = 648$. Liczb zawierających zero jest $2 \\cdot 9 \\cdot 8 = 144$ (zero na drugim albo trzecim miejscu, na pierwszym jedna z $9$ cyfr, na ostatnim jedna z $8$). Liczby bez zera: $648 - 144 = 504$. Bezpośrednio: $9 \\cdot 8 \\cdot 7 = 504$.',
    steps: ['Policz wszystkie liczby trzycyfrowe o różnych cyfrach: $648$.', 'Policz liczby zawierające zero: $2 \\cdot 9 \\cdot 8 = 144$.', 'Odejmij: $504$ (kontrolnie $9 \\cdot 8 \\cdot 7 = 504$).'],
    rubric: [
      { criterion: 'Obliczenie liczby wszystkich ciągów trzycyfrowych z różnymi cyframi', points: 1 },
      { criterion: 'Obliczenie liczby ciągów z zerem na pierwszym miejscu', points: 1 },
      { criterion: 'Odejęcie i wynik $576$', points: 1 },
    ],
  },
  {
    id: 'kb-08',
    topicSlug: 'kombinatoryka',
    lessonSlug: 'kombinatoryka-wzory',
    type: 'open',
    level: 'extended',
    difficulty: 4,
    points: 4,
    prompt: 'W klasie jest $10$ chłopców i $8$ dziewcząt. Ile trzyosobowych komitełów można wybrać tak, aby w komitecie znalazła się co najmniej jedna dziewczyna?',
    answer: '696',
    acceptedAnswers: ['696'],
    tags: ['wylaczenia', 'kombinacje', 'ograniczenia'],
    skills: ['kombinatoryka-ograniczenia', 'kombinatoryka-wzory'],
    hints: ['Najpierw policz wszystkie komitety trzyosobowe z całej klasy.', 'Od nich odejmij komitety złożone wyłącznie z chłopców.'],
    solution: 'Wszystkich komitetów trzyosobowych z $18$ osób: $C_{18}^{3} = \\frac{18 \\cdot 17 \\cdot 16}{6} = 816$. Komitetów z samych chłopców (bez dziewcząt): $C_{10}^{3} = \\frac{10 \\cdot 9 \\cdot 8}{6} = 120$. Szukane komitety: $816 - 120 = 696$.',
    steps: ['Oblicz $C_{18}^{3} = 816$ (wszystkie komitety).', 'Oblicz $C_{10}^{3} = 120$ (komitety bez dziewcząt).', 'Odejmij: $696$.'],
    rubric: [
      { criterion: 'Obliczenie liczby wszystkich komitetów $C_{18}^{3}$', points: 1 },
      { criterion: 'Obliczenie liczby komitetów bez dziewcząt $C_{10}^{3}$', points: 2 },
      { criterion: 'Odejęcie i wynik $696$', points: 1 },
    ],
  },
  {
    id: 'kb-09',
    topicSlug: 'kombinatoryka',
    lessonSlug: 'kombinatoryka-wzory',
    type: 'single_choice',
    level: 'extended',
    difficulty: 3,
    points: 1,
    prompt: 'Ile różnych trójek $(x, y, z)$ z różnych liczb $1, 2, 3, 4, 5, 6$ można utworzyć? Kolejność w trójce ma znaczenie.',
    options: ['120', '20', '60', '216'],
    answer: '120',
    tags: ['wariacje'],
    skills: ['kombinatoryka-wzory'],
    hints: ['Kolejność ma znaczenie — to wariacja $V_{6}^{3}$.', 'Możesz liczyć regułą mnożenia: $6 \\cdot 5 \\cdot 4$.'],
    solution: 'To wariacja: $V_{6}^{3} = \\frac{6!}{3!} = \\frac{720}{6} = 120$. Reguła mnożenia daje $6 \\cdot 5 \\cdot 4 = 120$.',
    steps: ['Zastosuj wzór na wariacje: $V_{6}^{3}$.', 'Oblicz: $\\frac{6!}{3!} = 120$.', 'Potwierdź regułą mnożenia: $6 \\cdot 5 \\cdot 4 = 120$.'],
  },
  {
    id: 'kb-10',
    topicSlug: 'kombinatoryka',
    lessonSlug: 'kombinatoryka-wzory',
    type: 'open',
    level: 'extended',
    difficulty: 4,
    points: 4,
    prompt: 'Ile ciągów długości $5$ złożonych z liter A, B i C zawiera co najmniej jedną literę A?',
    answer: '211',
    acceptedAnswers: ['211'],
    tags: ['wylaczenia', 'ciagi', 'ograniczenia'],
    skills: ['kombinatoryka-ograniczenia'],
    hints: ['Policz wszystkie ciągi długości 5 z trzech liter.', 'Od nich odejmij ciągi złożone wyłącznie z liter B i C.'],
    solution: 'Wszystkich ciągów długości $5$ z liter A, B, C: $3^{5} = 243$ (reguła mnożenia, $3$ wybory na każdym miejscu). Ciągów bez litery A, czyli złożonych tylko z B i C: $2^{5} = 32$. Szukane ciągi: $243 - 32 = 211$.',
    steps: ['Policz wszystkie ciągi: $3^{5} = 243$.', 'Policz ciągi bez A: $2^{5} = 32$.', 'Odejmij: $243 - 32 = 211$.'],
    rubric: [
      { criterion: 'Obliczenie liczby wszystkich ciągów $3^{5}$', points: 1 },
      { criterion: 'Obliczenie liczby ciągów bez litery A ($2^{5}$)', points: 1 },
      { criterion: 'Zastosowanie metody wyłączeń', points: 1 },
      { criterion: 'Wynik $211$', points: 1 },
    ],
  },
]
