import type { ContentTask } from '@/content/types'

/**
 * Bank zadań do działu „Funkcja kwadratowa”.
 * Kody `kw-*` są stabilnym kluczem importu — nie zmieniaj ich przy edycji treści.
 */
export const kwadratowaTasks: ContentTask[] = [
  {
    id: 'kw-01',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-postacie',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Funkcja $f(x) = (x-2)^{2} - 9$ jest zadana w postaci kanonicznej. Podaj odciętą wierzchołka jej wykresu.',
    answer: '2',
    acceptedAnswers: ['2', '2,0'],
    tags: ['kanoniczna', 'wierzcholek'],
    skills: ['kwadratowa-wierzcholek'],
    hints: ['W postaci $a(x-p)^2 + q$ wierzchołek to $(p, q)$.', 'Porównaj z $(x-2)^2 - 9$.'],
    solution: 'W postaci kanonicznej $f(x) = (x-2)^2 - 9$ wierzchołek to $(2, -9)$, więc odcięta wierzchołka $p = 2$.',
    steps: ['Rozpoznaj postać kanoniczną $a(x-p)^2 + q$.', 'Odczytaj $p = 2$.'],
  },
  {
    id: 'kw-02',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-postacie',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Wyznacz współrzędną $p$ wierzchołka paraboli będącej wykresem funkcji $f(x) = 2x^{2} - 8x + 3$.',
    answer: '2',
    acceptedAnswers: ['2', '2,0'],
    tags: ['wierzcholek'],
    skills: ['kwadratowa-wierzcholek'],
    hints: ['Użyj wzoru $p = -\\frac{b}{2a}$.', 'Tu $a = 2$, $b = -8$.'],
    solution: '$p = -\\frac{b}{2a} = -\\frac{-8}{2 \\cdot 2} = \\frac{8}{4} = 2$.',
    steps: ['Zidentyfikuj $a = 2$, $b = -8$.', 'Oblicz $p = -\\frac{-8}{4} = 2$.'],
  },
  {
    id: 'kw-03',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-postacie',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Funkcja $f(x) = -2(x+1)^{2} + 5$ przyjmuje wartość największą równą:',
    options: ['$5$', '$-5$', '$1$', '$-1$'],
    answer: '$5$',
    tags: ['kanoniczna', 'max'],
    skills: ['kwadratowa-postacie'],
    hints: ['Sprawdź znak $a$ — od niego zależy, czy wierzchołek daje max czy min.', 'Wierzchołek to $(-1, 5)$.'],
    solution: '$a = -2 < 0$, ramiona w dół, więc funkcja przyjmuje wartość największą w wierzchołku. Z postaci kanonicznej wierzchołek to $(-1, 5)$, więc $f_{max} = 5$.',
    steps: ['Sprawdź znak $a$: ujemny → maksimum.', 'Odczytaj $q = 5$ z postaci kanonicznej.'],
  },
  {
    id: 'kw-04',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-postacie',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Miejscami zerowymi funkcji $f(x) = (x-3)(x+5)$ są liczby $x_1$ i $x_2$. Podaj odciętą wierzchołka paraboli będącej wykresem tej funkcji.',
    answer: '-1',
    acceptedAnswers: ['-1', '−1', '-1,0'],
    tags: ['iloczynowa', 'wierzcholek'],
    skills: ['kwadratowa-postacie', 'kwadratowa-wierzcholek'],
    hints: ['Z postaci iloczynowej odczytaj miejsca zerowe.', 'Wierzchołek leży w połowie między nimi: $p = \\frac{x_1+x_2}{2}$.'],
    solution: 'Miejsca zerowe: $x_1 = 3$, $x_2 = -5$. Wierzchołek: $p = \\frac{3 + (-5)}{2} = \\frac{-2}{2} = -1$.',
    steps: ['Odczytaj $x_1 = 3$ i $x_2 = -5$.', 'Oblicz $p = \\frac{3-5}{2} = -1$.'],
  },
  {
    id: 'kw-05',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-postacie',
    type: 'single_choice',
    difficulty: 3,
    points: 1,
    prompt: 'Wykresem funkcji $f(x) = x^{2} - 6x + 5$ jest parabola o wierzchołku $W$. Punkt $W$ ma współrzędne:',
    options: ['$(3, -4)$', '$(-3, 4)$', '$(3, 4)$', '$(6, 5)$'],
    answer: '$(3, -4)$',
    tags: ['wierzcholek', 'kanoniczna'],
    skills: ['kwadratowa-wierzcholek'],
    hints: ['Oblicz $p = -\\frac{b}{2a}$, potem $q = f(p)$.', '$p = 3$, a $q = 9 - 18 + 5$.'],
    solution: '$p = -\\frac{-6}{2} = 3$. $q = f(3) = 9 - 18 + 5 = -4$. Wierzchołek $W = (3, -4)$.',
    steps: ['Oblicz $p = 3$.', 'Podstaw $x = 3$: $q = -4$.'],
  },
  {
    id: 'kw-06',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-postacie',
    type: 'text',
    difficulty: 2,
    points: 1,
    prompt: 'Podaj zbiór wartości funkcji $f(x) = 3(x-1)^{2} + 7$. Zapisz w formacie: [a, nieskonczonosc] lub [-nieskonczonosc, a].',
    answer: '[7, +\\infty)',
    acceptedAnswers: ['[7,+\\infty)', '[7, nieskonczonosc]', '[7,+nieskonczonosc]', '[7,\\infty)'],
    tags: ['zbior-wartosci'],
    skills: ['kwadratowa-postacie'],
    hints: ['$a = 3 > 0$, więc ramiona w górę.', 'Zbiór wartości zaczyna się w $q$ i biegnie do $+\\infty$.'],
    solution: 'Ponieważ $a = 3 > 0$, funkcja przyjmuje wszystkie wartości nie mniejsze niż $q = 7$: zbiór wartości to $[7, +\\infty)$.',
    steps: ['Sprawdź znak $a > 0$.', 'Odczytaj $q = 7$ i zapisz $[7, +\\infty)$.'],
  },
  {
    id: 'kw-07',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-delta',
    type: 'single_choice',
    difficulty: 1,
    points: 1,
    prompt: 'Delta trójmianu $x^{2} - 6x + 9$ jest równa:',
    options: ['$0$', '$4$', '$-4$', '$36$'],
    answer: '$0$',
    tags: ['delta'],
    skills: ['kwadratowa-delta'],
    hints: ['$\\Delta = b^2 - 4ac$', '$\\Delta = 36 - 36 = 0$'],
    solution: '$\\Delta = (-6)^2 - 4 \\cdot 1 \\cdot 9 = 36 - 36 = 0$. Rzeczywiście: $x^2-6x+9 = (x-3)^2$ ma jedno miejsce zerowe $x = 3$.',
    steps: ['Zapisz $\\Delta = b^2 - 4ac$.', 'Oblicz $36 - 36 = 0$.'],
  },
  {
    id: 'kw-08',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-delta',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Równanie $x^{2} - 7x + 10 = 0$ ma dwa rozwiązania $x_1$ i $x_2$ (przyjmij $x_1 < x_2$). Podaj liczbę $x_2 - x_1$.',
    answer: '3',
    acceptedAnswers: ['3', '3,0'],
    tags: ['miejsca-zerowe'],
    skills: ['kwadratowa-delta'],
    hints: ['Oblicz $\\Delta$ i $\\sqrt{\\Delta}$.', '$x_{1,2} = \\frac{7 \\mp 3}{2}$.'],
    solution: '$\\Delta = 49 - 40 = 9$, $\\sqrt{\\Delta} = 3$. $x_1 = \\frac{7-3}{2} = 2$, $x_2 = \\frac{7+3}{2} = 5$. Różnica $x_2 - x_1 = 3$.',
    steps: ['$\\Delta = 9$, $\\sqrt{\\Delta} = 3$.', '$x_1 = 2$, $x_2 = 5$.', 'Oblicz różnicę $3$.'],
  },
  {
    id: 'kw-09',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-delta',
    type: 'text',
    difficulty: 2,
    points: 1,
    prompt: 'Podaj zbiór rozwiązań nierówności $x^{2} - 3x - 4 > 0$. Zapisz przedziałami, np.: (-nieskonczonosc, a) lub (a, b) lub (a, b) suma (c, d).',
    answer: '(-\\infty,-1)\\cup(4,+\\infty)',
    acceptedAnswers: ['(-\\infty,-1) suma (4,+\\infty)', '(-nieskonczonosc,-1) suma (4,+nieskonczonosc)', '(-\\infty, -1) ∪ (4, +\\infty)', '(-nieskonczonosc,-1)lub(4,nieskonczonosc)'],
    tags: ['nierownosci'],
    skills: ['kwadratowa-nierownosci'],
    hints: ['Znajdź miejsca zerowe trójmianu.', 'Ramiona w górę: dodatni poza pierwiastkami.'],
    solution: '$\\Delta = 9 + 16 = 25$, $\\sqrt{\\Delta} = 5$. Miejsca zerowe: $x_1 = \\frac{3-5}{2} = -1$, $x_2 = \\frac{3+5}{2} = 4$. Ramiona w górę, więc trójmian jest dodatni poza przedziałem $(-1, 4)$: zbiór rozwiązań $(-\\infty, -1) \\cup (4, +\\infty)$.',
    steps: ['$\\Delta = 25$, pierwiastki $-1$ i $4$.', 'Ramiona w górę → dodatni poza $(-1,4)$.', 'Zapisz sumę przedziałów.'],
  },
  {
    id: 'kw-10',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-delta',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Zbiorem rozwiązań nierówności $-x^{2} + 4x - 5 > 0$ jest:',
    options: ['zbiór pusty', '$\\mathbb{R}$', '$(2 - \\sqrt{6}, 2 + \\sqrt{6})$', '$(-\\infty, 0) \\cup (4, +\\infty)$'],
    answer: 'zbiór pusty',
    tags: ['nierownosci', 'delta-ujemna'],
    skills: ['kwadratowa-nierownosci'],
    hints: ['Pomnóż obie strony przez $-1$.', 'Zbadaj deltę trójmianu $x^2 - 4x + 5$.'],
    solution: 'Po pomnożeniu przez $-1$: $x^{2} - 4x + 5 < 0$. Delta: $\\Delta = 16 - 20 = -4 < 0$, a $a = 1 > 0$ — trójmian jest zawsze dodatni, więc nigdy nie jest ujemny. Zbiór rozwiązań jest pusty.',
    steps: ['Zamień na $x^2 - 4x + 5 < 0$.', '$\\Delta = -4 < 0$, $a > 0$ → zawsze dodatni.', 'Nierówność sprzeczna → zbiór pusty.'],
  },
  {
    id: 'kw-11',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-delta',
    type: 'open',
    difficulty: 3,
    points: 3,
    prompt: 'Rozwiąż nierówność $2x^{2} - 8x + 6 < 0$ i zapisz zbiór rozwiązań.',
    answer: '(1,3)',
    acceptedAnswers: ['(1, 3)', '(1;3)', 'x\\in(1,3)'],
    tags: ['nierownosci', 'otwarte'],
    skills: ['kwadratowa-nierownosci'],
    hints: ['Podziel obie strony przez $2$.', 'Znajdź pierwiastki trójmianu $x^2 - 4x + 3$.'],
    solution: 'Dzielimy przez $2$: $x^{2} - 4x + 3 < 0$. Delta: $\\Delta = 16 - 12 = 4$, $\\sqrt{\\Delta} = 2$. Pierwiastki: $x_1 = \\frac{4-2}{2} = 1$, $x_2 = \\frac{4+2}{2} = 3$. Ramiona w górę — ujemny między pierwiastkami. Zbiór rozwiązań: $(1, 3)$.',
    steps: ['Podziel przez $2$: $x^2 - 4x + 3 < 0$.', '$\\Delta = 4$, pierwiastki $1$ i $3$.', 'Odpowiedź: $(1, 3)$.'],
    rubric: [
      { criterion: 'Podzielenie nierówności przez $2$ lub poprawne badanie oryginalnej', points: 1 },
      { criterion: 'Poprawne wyznaczenie pierwiastków $x_1 = 1$, $x_2 = 3$', points: 1 },
      { criterion: 'Zapis zbioru rozwiązań $(1,3)$ z poprawnymi nawiasami', points: 1 },
    ],
  },
  {
    id: 'kw-12',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-delta',
    type: 'proof',
    difficulty: 4,
    points: 3,
    prompt: 'Uzasadnij, że dla każdej liczby rzeczywistej $x$ zachodzi nierówność $x^{2} - 4x + 5 > 0$.',
    answer: '(x-2)^{2}+1 > 0',
    acceptedAnswers: ['(x-2)^2+1>0', '(x - 2)^2 + 1 > 0'],
    tags: ['dowod', 'kanoniczna'],
    skills: ['kwadratowa-nierownosci', 'kwadratowa-postacie'],
    hints: ['Doprowadź wyrażenie do postaci kanonicznej.', 'Wykorzystaj, że kwadrat liczby rzeczywistej jest nieujemny.'],
    solution: 'Postać kanoniczna: $x^{2} - 4x + 5 = (x^{2} - 4x + 4) + 1 = (x-2)^{2} + 1$. Dla każdej liczby rzeczywistej $x$ mamy $(x-2)^{2} \\geq 0$, więc $(x-2)^{2} + 1 \\geq 1 > 0$. Zatem nierówność zachodzi dla każdego $x \\in \\mathbb{R}$.',
    steps: ['Grupuj: $x^2 - 4x + 4 + 1$.', 'Zapisz $(x-2)^2 + 1$.', 'Użyj $(x-2)^2 \\geq 0$, więc wyrażenie $\\geq 1 > 0$.'],
    rubric: [
      { criterion: 'Przekształcenie do postaci $(x-2)^2 + 1$', points: 1 },
      { criterion: 'Zastosowanie własności $(x-2)^2 \\geq 0$ dla każdego $x$', points: 1 },
      { criterion: 'Pełne zakończenie: wyrażenie $\\geq 1 > 0$, więc nierówność prawdziwa dla każdego $x$', points: 1 },
    ],
  },
  {
    id: 'kw-13',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-zastosowania',
    type: 'open',
    difficulty: 4,
    points: 4,
    prompt: 'W trójkąt prostokątny o przyprostokątnych $6$ i $8$ wpisano prostokąt tak, że dwa jego boki leżą na przyprostokątnych, a jeden z wierzchołków na przeciwprostokątnej. Wyznacz długości boków tego prostokąta, dla których jego pole jest największe.',
    answer: '3 i 4',
    acceptedAnswers: ['3 i 4', '3,4', '3x4', '3\\times4'],
    tags: ['optymalizacja', 'geometria'],
    skills: ['kwadratowa-optymalizacja'],
    hints: ['Oznacz boki prostokąta: $x$ (leżący na boku $6$) i $y$. Z podobieństwa trójkątów wyraź $y$ przez $x$.', 'Z podobieństwa: $\\frac{y}{8} = \\frac{6-x}{6}$, więc $y = 8 - \\frac{4}{3}x$.'],
    solution: `Oznaczmy $x$ — bok leżący na przyprostokątnej $6$, $y$ — bok leżący na przyprostokątnej $8$. Pole: $P(x) = xy$.

Z podobieństwa trójkątów (trójkąt nad prostokątem jest podobny do całego): $\\frac{y}{8} = \\frac{6-x}{6}$, więc $y = 8 - \\frac{4}{3}x$.

$$P(x) = x\\left(8 - \\frac{4}{3}x\\right) = 8x - \\frac{4}{3}x^{2}, \\quad x \\in (0, 6)$$

To funkcja kwadratowa z $a = -\\frac{4}{3} < 0$ — maksimum w wierzchołku:
$$x = -\\frac{8}{2 \\cdot (-\\frac{4}{3})} = \\frac{8}{\\frac{8}{3}} = 3$$
Wtedy $y = 8 - \\frac{4}{3} \\cdot 3 = 4$.

**Odpowiedź:** pole jest największe dla prostokąta o bokach $3$ i $4$ (pole równe $12$).`,
    steps: ['Oznacz boki $x$ i $y$; zapisz pole $P = xy$.', 'Z podobieństwa: $y = 8 - \\frac{4}{3}x$.', '$P(x) = 8x - \\frac{4}{3}x^2$, dziedzina $(0,6)$.', 'Wierzchołek: $x = 3$, $y = 4$.', 'Odpowiedź z jednostkami.'],
    rubric: [
      { criterion: 'Poprawne oznaczenia i zapis pola $P = xy$', points: 1 },
      { criterion: 'Wyznaczenie zależności $y = 8 - \\frac{4}{3}x$ z podobieństwa trójkątów', points: 1 },
      { criterion: 'Zapis funkcji $P(x)$ z dziedziną i wyznaczenie wierzchołka $x = 3$', points: 1 },
      { criterion: 'Obliczenie $y = 4$ i pełna odpowiedź (boki $3$ i $4$)', points: 1 },
    ],
  },
  {
    id: 'kw-14',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-zastosowania',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Na parkingu zaparkowano $60$ samochodów, każdy płaci $10$ zł. Za każde $2$ zł podwyżki opłaty liczba parkujących maleje o $5$. Ilu podwyżek (po $2$ zł) należy dokonać, aby dzienny przychód parkingu był największy?',
    options: ['$3$ lub $4$', '$2$', '$5$', '$7$'],
    answer: '$3$ lub $4$',
    tags: ['optymalizacja', 'przychod'],
    skills: ['kwadratowa-optymalizacja'],
    hints: ['Oznacz liczbę podwyżek przez $x$ i zapisz przychód: $W(x) = (10 + 2x)(60 - 5x)$.', 'Wierzchołek paraboli wypada w $x = 3{,}5$ — sprawdź sąsiednie liczby całkowite.'],
    solution: `Przychód: $W(x) = (10 + 2x)(60 - 5x) = -10x^{2} + 70x + 600$. Wierzchołek: $x = -\\frac{70}{2 \\cdot (-10)} = 3{,}5$. Liczba podwyżek musi być całkowita, więc sprawdzamy $x = 3$ i $x = 4$: $W(3) = 16 \\cdot 45 = 720$ oraz $W(4) = 18 \\cdot 40 = 720$ — przychód jest taki sam i maksymalny. Odpowiedź: $3$ albo $4$ podwyżki.`,
    steps: ['Zapisz $W(x) = (10+2x)(60-5x)$.', 'Wyznacz wierzchołek: $x = 3{,}5$.', 'Sprawdź $x = 3$ i $x = 4$ — oba dają $720$ zł.'],
  },
  {
    id: 'kw-15',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-zastosowania',
    type: 'numeric',
    difficulty: 3,
    points: 1,
    prompt: 'Firma sprzedaje zabawki po $c$ zł za sztukę i sprzedaje wtedy $n(c) = 1200 - 30c$ zabawek tygodniowo. Podaj cenę $c$ (w zł), która maksymalizuje tygodniowy przychód.',
    answer: '20',
    acceptedAnswers: ['20', '20 zł', '20,0'],
    tags: ['optymalizacja', 'przychod'],
    skills: ['kwadratowa-optymalizacja'],
    hints: ['Przychód: $R(c) = c(1200 - 30c)$.', 'Wierzchołek: $c = -\\frac{1200}{2 \\cdot (-30)}$.'],
    solution: '$R(c) = 1200c - 30c^{2}$ — funkcja kwadratowa z $a = -30 < 0$. Wierzchołek: $c = -\\frac{1200}{2 \\cdot (-30)} = \\frac{1200}{60} = 20$. Przy cenie $20$ zł przychód jest maksymalny ($R = 12000$ zł).',
    steps: ['Zapisz $R(c) = c(1200-30c)$.', 'Wyznacz wierzchołek: $c = 20$.'],
  },
  {
    id: 'kw-16',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-zastosowania',
    type: 'numeric',
    difficulty: 3,
    points: 1,
    prompt: 'Piłka wykopana przez bramkarza porusza się tak, że jej wysokość (w metrach) po czasie $t$ (w sekundach) wynosi $h(t) = -5t^{2} + 20t$. Po ilu sekundach piłka osiąga maksymalną wysokość?',
    answer: '2',
    acceptedAnswers: ['2', '2 s', '2,0'],
    tags: ['optymalizacja', 'fizyka'],
    skills: ['kwadratowa-optymalizacja'],
    hints: ['Wierzchołek: $t = -\\frac{b}{2a}$.', '$a = -5$, $b = 20$.'],
    solution: '$t = -\\frac{b}{2a} = -\\frac{20}{2 \\cdot (-5)} = 2$ — piłka osiąga maksimum po $2$ s (na wysokości $20$ m).',
    steps: ['Zastosuj wzór na odciętą wierzchołka.', '$t = 2$ s.'],
  },
  {
    id: 'kw-17',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-zastosowania',
    type: 'numeric',
    difficulty: 3,
    points: 1,
    prompt: 'Dla jakich wartości parametru $m$ równanie $x^{2} + mx + 9 = 0$ ma dokładnie jedno rozwiązanie? Podaj sumę wszystkich takich wartości $m$.',
    answer: '0',
    acceptedAnswers: ['0', '0,0'],
    tags: ['parametr', 'delta'],
    skills: ['kwadratowa-parametr'],
    hints: ['Dokładnie jedno rozwiązanie: $\\Delta = 0$.', '$\\Delta = m^{2} - 36 = 0$'],
    solution: '$\\Delta = m^{2} - 36 = 0 \\iff m = 6$ lub $m = -6$. Suma: $6 + (-6) = 0$.',
    steps: ['Zapisz warunek $\\Delta = 0$.', 'Rozwiąż $m^2 = 36$.', 'Suma rozwiązań: $0$.'],
  },
  {
    id: 'kw-18',
    topicSlug: 'kwadratowa',
    lessonSlug: 'kwadratowa-zastosowania',
    type: 'proof',
    difficulty: 5,
    points: 4,
    prompt: 'Wykaż, że dla każdej liczby rzeczywistej $x$ wyrażenie $3x^{2} - 6x + 4$ jest dodatnie.',
    answer: '3(x-1)^{2}+1 > 0',
    acceptedAnswers: ['3(x-1)^2+1>0', '3(x - 1)^2 + 1 > 0'],
    tags: ['dowod', 'kanoniczna'],
    skills: ['kwadratowa-postacie'],
    hints: ['Wyłącz $3$ przed nawias przy wyrazach z $x$.', 'Wykorzystaj nieujemność kwadratu.'],
    solution: '$3x^{2} - 6x + 4 = 3(x^{2} - 2x) + 4 = 3\\left[(x-1)^{2} - 1\\right] + 4 = 3(x-1)^{2} + 1$. Dla każdego $x$: $(x-1)^{2} \\geq 0$, więc $3(x-1)^{2} \\geq 0$ i $3(x-1)^{2} + 1 \\geq 1 > 0$. Zatem wyrażenie jest zawsze dodatnie. (Alternatywnie: $\\Delta = 36 - 48 = -12 < 0$ i $a = 3 > 0$.)',
    steps: ['Wyłącz $3$: $3(x^2 - 2x) + 4$.', 'Dokończ kwadrat: $3(x-1)^2 + 1$.', 'Użyj $(x-1)^2 \\geq 0$ i zakończ wniosek.'],
    rubric: [
      { criterion: 'Poprawne przekształcenie do postaci $3(x-1)^2 + 1$', points: 2 },
      { criterion: 'Zastosowanie nieujemności kwadratu i pełny wniosek o dodatniości', points: 2 },
    ],
  },
]
