import type { ContentTask } from '@/content/types'

export const optymalizacjaTasks: ContentTask[] = [
  { id: 'op-01', topicSlug: 'optymalizacja', lessonSlug: 'optymalizacja-model', type: 'numeric', difficulty: 2, points: 1, prompt: 'Prostokąt ma obwód $20$. Jeśli jedna krawędź ma długość $6$, ile wynosi druga?', answer: '4', tags: ['prostokat'], skills: ['optymalizacja-model'], hints: ['Obwód to dwukrotna suma krawędzi.'], solution: '$2(6+b)=20$, więc $b=4$.', steps: ['Zapisz równanie obwodu.', 'Wyznacz $b$.'] },
  { id: 'op-02', topicSlug: 'optymalizacja', lessonSlug: 'optymalizacja-model', type: 'text', difficulty: 2, points: 1, prompt: 'Pole prostokąta o bokach $x$ i $10-x$ zapisz jako funkcję $P(x)$.', answer: '10x-x^2', acceptedAnswers: ['x(10-x)', 'x*(10-x)', '10x - x^2', '-x^2+10x'], tags: ['model'], skills: ['optymalizacja-model'], hints: ['Pole to iloczyn boków.'], solution: '$P(x)=x(10-x)=10x-x^2$.', steps: ['Zapisz iloczyn.', 'Wymień na $10x-x^2$.'] },
  { id: 'op-03', topicSlug: 'optymalizacja', lessonSlug: 'optymalizacja-pochodna', type: 'numeric', difficulty: 3, points: 2, prompt: 'Jaka jest największa wartość $P(x)=10x-x^2$ dla $0\\le x\\le10$?', answer: '25', tags: ['maximum'], skills: ['optymalizacja-pochodna'], hints: ['Oblicz $P\'(x)=10-2x$.'], solution: 'Krytyczny punkt to $x=5$, a $P(5)=25$. Na końcach $P=0$.', steps: ['Oblicz pochodną.', 'Znajdź $x=5$.', 'Porównaj wartości.'] },
  { id: 'op-04', topicSlug: 'optymalizacja', lessonSlug: 'optymalizacja-pochodna', type: 'single_choice', difficulty: 3, points: 1, prompt: 'W optimum funkcji różniczkowalnej na przedziale zamkniętym:', options: ['może wystąpić punkt krytyczny', 'tylko w nieskończoności', 'zawsze w zerze', 'nie trzeba badać wartości'], answer: 'może wystąpić punkt krytyczny', tags: ['optymalizacja'], skills: ['optymalizacja-pochodna'], hints: ['Porównaj punkty krytyczne i końce.'], solution: 'Maksimum lub minimum może wystąpić w punkcie krytycznym albo na końcu przedziału.', steps: ['Wymień możliwe miejsca.', 'Porównaj wartości.'] },
  { id: 'op-05', topicSlug: 'optymalizacja', lessonSlug: 'optymalizacja-model', type: 'open', difficulty: 3, points: 3, prompt: 'Z drutu długości $12$ zbuduj prostokąt, którego obwód wynosi $12$. Zapisz funkcję pola, jeśli $x$ oznacza długość jednej krawędzi.', answer: 'P(x)=x(6-x), 0<x<6', tags: ['model'], skills: ['optymalizacja-model'], hints: ['Druga krawędź to $(12-2x)/2$.'], solution: 'Druga krawędź to $6-x$, zatem $P(x)=x(6-x)$ dla $0<x<6$.', steps: ['Wyznacz drugi bok.', 'Zapisz pole i dziedzinę.'], rubric: [{ criterion: 'Wyznaczenie drugiego boku', points: 1 }, { criterion: 'Funkcja pola', points: 1 }, { criterion: 'Dziedzina', points: 1 }] },
  { id: 'op-06', topicSlug: 'optymalizacja', lessonSlug: 'optymalizacja-pochodna', type: 'open', difficulty: 3, points: 3, prompt: 'Maksymalizuj $P(x)=x(6-x)$ na przedziale $[0,6]$. Podaj wartość i argument maksimum.', answer: '9 dla x=3', tags: ['maximum'], skills: ['optymalizacja-pochodna'], hints: ['Oblicz $P\'(x)=6-2x$.'], solution: '$P\'(x)=6-2x$, więc $x=3$ i $P(3)=9$. Wartości na końcach wynoszą $0$.', steps: ['Wyznacz punkt krytyczny.', 'Oblicz wartość.', 'Porównaj końce.'], rubric: [{ criterion: 'Pochodna', points: 1 }, { criterion: 'Punkt krytyczny', points: 1 }, { criterion: 'Maksimum 9', points: 1 }] },
  { id: 'op-07', topicSlug: 'optymalizacja', lessonSlug: 'optymalizacja-pochodna', type: 'single_choice', difficulty: 4, points: 1, prompt: 'Funkcja $f(x)=x^2+1$ na $\\mathbb R$ ma:', options: ['minimum $1$ dla $x=0$', 'maksimum $1$ dla $x=0$', 'brak ekstremum', 'minimum $0$ dla $x=1$'], answer: 'minimum $1$ dla $x=0$', tags: ['minimum'], skills: ['optymalizacja-pochodna'], hints: ['Oblicz $f\'(x)$ i sprawdź znak pochodnej przed i po zerze.'], solution: '$f\'(x)=2x$, więc pochodna zeruje się dla $x=0$ i zmienia znak z ujemnego na dodatni — to minimum. Jego wartość to $f(0)=1$.', steps: ['Oblicz pochodną: $f\'(x)=2x$.', 'Zbadaj znak pochodnej: minimum dla $x=0$.', 'Podaj wartość: $1$.'] },
  { id: 'op-08', topicSlug: 'optymalizacja', lessonSlug: 'optymalizacja-model', type: 'open', difficulty: 4, points: 4,    prompt: 'W prostokącie suma długości dwóch sąsiednich boków wynosi $5$. Wyznacz największe możliwe pole.', answer: '6,25', tags: ['tekstowe'], skills: ['optymalizacja-model', 'optymalizacja-pochodna'], hints: ['Niech jedna krawędź to $x$.', 'Druga wynosi $5-x$.'], solution: 'Pole $P(x)=x(5-x)$, maksimum po pochodnej jest dla $x=2{,}5$ i wynosi $6{,}25$.', steps: ['Zbuduj funkcję pola.', 'Znajdź maksimum $6{,}25$.'], rubric: [{ criterion: 'Model pola', points: 1 }, { criterion: 'Pochodna i punkt krytyczny', points: 2 }, { criterion: 'Maksimum $6{,}25$', points: 1 }] },
  { id: 'op-09', topicSlug: 'optymalizacja', lessonSlug: 'optymalizacja-pochodna', type: 'single_choice', difficulty: 4, points: 1, prompt: 'Jeżeli $f\'(x)>0$ na przedziale, to $f$ jest:', options: ['rosnąca', 'malejąca', 'stała', 'nieciągła'], answer: 'rosnąca', tags: ['monotonicznosc'], skills: ['optymalizacja-pochodna'], hints: ['Znak pochodnej opisuje monotoniczność.'], solution: 'Dodatnia pochodna oznacza wzrost funkcji na przedziale.', steps: ['Przypomnij związek.', 'Wybierz rosnąca.'] },
  { id: 'op-10', topicSlug: 'optymalizacja', lessonSlug: 'optymalizacja-pochodna', type: 'open', difficulty: 5, points: 5, prompt: 'Dla $f(x)=\\frac1x$ wyznacz najmniejszą wartość bezwzględną $|f(x)|$ dla $x\\in\\mathbb R$.', answer: 'nie ma minimum; infimum 0', tags: ['granica'], skills: ['optymalizacja-pochodna'], hints: ['Funkcja nigdy nie jest zerowa.', 'Rozważ $|x|$ rosnące.'], solution: 'Dla $x\\neq0$ mamy $|1/x|>0$, ale wartość zbliża się do $0$ przy $|x|\\to\\infty$. Nie ma osiągniętego minimum; infimum wynosi $0$.', steps: ['Sprawdź, czy zero jest osiągalne.', 'Zbadaj zachowanie dla dużego $|x|$.'], rubric: [{ criterion: 'Brak minimum', points: 2 }, { criterion: 'Infimum 0', points: 2 }, { criterion: 'Uzasadnienie granicą', points: 1 }] },
]
