import type { ContentTask } from '@/content/types'

export const parametryTasks: ContentTask[] = [
  { id: 'pa-01', topicSlug: 'parametry', lessonSlug: 'parametry-rownania', type: 'single_choice', difficulty: 1, points: 1, prompt: 'Dla jakiej wartości $a$ równanie $ax=4$ nie ma rozwiązań?', options: ['$a=0$', '$a=2$', '$a=-2$', '$a=4$'], answer: '$a=0$', tags: ['parametr'], skills: ['parametry-rownania'], hints: ['Rozważ przypadek $a=0$.'], solution: 'Dla $a=0$ otrzymujemy $0=4$, czyli sprzeczność.', steps: ['Sprawdź $a=0$.', 'Zapisz sprzeczność.'] },
  { id: 'pa-02', topicSlug: 'parametry', lessonSlug: 'parametry-rownania', type: 'numeric', difficulty: 2, points: 1, prompt: 'Dla $a\\neq0$ rozwiąż $ax=12$. Podaj $x$ jako wyrażenie z $a$.', answer: '12/a', tags: ['parametr'], skills: ['parametry-rownania'], hints: ['Podziel obie strony przez $a$.'], solution: '$x=12/a$ dla $a\\neq0$.', steps: ['Zapisz $a\\neq0$.', 'Podziel przez $a$.'] },
  { id: 'pa-03', topicSlug: 'parametry', lessonSlug: 'parametry-rownania', type: 'numeric', difficulty: 2, points: 1, prompt: 'Dla ilu wartości $a$ równanie $a^2x+1=0$ nie ma rozwiązania?', answer: '1', tags: ['liczba-rozwiazan'], skills: ['parametry-rownania'], hints: ['Równanie nie ma rozwiązania, gdy współczynnik przy $x$ jest zerowy.'], solution: 'Gdy $a=0$, równanie ma postać $1=0$, więc istnieje jedna taka wartość $a$.', steps: ['Wyznacz warunek $a^2=0$.', 'Policz wartość.'] },
  { id: 'pa-04', topicSlug: 'parametry', lessonSlug: 'parametry-rownania', type: 'open', difficulty: 3, points: 3, prompt: 'Rozwiąż $a+x=5$ i wyraź $x$ przez $a$.', answer: 'x=5-a', tags: ['rownanie'], skills: ['parametry-rownania'], hints: ['Odejmij $a$ od obu stron.'], solution: '$x=5-a$.', steps: ['Odejmij $a$.', 'Zapisz wynik.'], rubric: [{ criterion: 'Poprawne przekształcenie', points: 2 }, { criterion: 'Zapis odpowiedzi', points: 1 }] },
  { id: 'pa-05', topicSlug: 'parametry', lessonSlug: 'parametry-rownania', type: 'single_choice', difficulty: 3, points: 1, prompt: 'Równanie $(a-2)x=0$ ma nieskończenie wiele rozwiązań, gdy:', options: ['$a\\neq2$', '$a=2$', '$a=0$', '$a>0$'], answer: '$a=2$', tags: ['tozsamosc'], skills: ['parametry-rownania'], hints: ['Dla tożsamości obie strony muszą być zerowe.'], solution: 'Dla $a=2$ równanie staje się $0=0$.', steps: ['Ustaw współczynnik przy $x$ na zero.', 'Sprawdź wyraz wolny.'] },
  { id: 'pa-06', topicSlug: 'parametry', lessonSlug: 'parametry-rownania', type: 'numeric', difficulty: 3, points: 2, prompt: 'Dla ilu wartości $a$ równanie $(a-2)x=4$ ma dwa różne rozwiązania?', answer: '0', tags: ['liczba-rozwiazan'], skills: ['parametry-rownania'], hints: ['Równanie liniowe ma jedno rozwiązanie dla $a\\neq2$.', 'Dla $a=2$ jest sprzeczne.'], solution: 'Dla $a\\neq2$ istnieje dokładnie jedno rozwiązanie $x=4/(a-2)$, a dla $a=2$ nie ma rozwiązań. Zatem nie ma żadnej wartości $a$ dającej dwa rozwiązania.', steps: ['Rozważ $a=2$.', 'Dla $a\\neq2$ rozwiązanie jest jedno.', 'Wynik: brak wartości, czyli $0$.'], },
  { id: 'pa-07', topicSlug: 'parametry', lessonSlug: 'parametry-pochodna', type: 'numeric', difficulty: 4, points: 2, prompt: 'Dla $f(x)=x^2-2ax$ wyznacz wartość $a$, dla której minimum w $x=a$ wynosi $-4$.', answer: 'a=±2', tags: ['minimum'], skills: ['parametry-pochodna'], hints: ['Oblicz $f(a)=a^2-2a^2$.'], solution: '$f(a)=a^2-2a^2=-a^2$. Warunek $-a^2=-4$ daje $a=2$ lub $a=-2$; dla obu wartości druga pochodna $f\'\'(x)=2>0$ potwierdza minimum.', steps: ['Zapisz f(a).', 'Rozwiąż $-a^2=-4$.', 'Podaj $a=\\pm2$.'] },
  { id: 'pa-08', topicSlug: 'parametry', lessonSlug: 'parametry-pochodna', type: 'single_choice', difficulty: 4, points: 1, prompt: 'Funkcja $f(x)=x^2+ax$ ma minimum w $x=0$, gdy:', options: ['$a=0$', '$a>0$', '$a<0$', 'nie ma znaczenia'], answer: '$a=0$', tags: ['minimum'], skills: ['parametry-pochodna'], hints: ['Warunek minimum to $f\'(0)=0$.'], solution: '$f\'(x)=2x+a$, więc $f\'(0)=a=0$.', steps: ['Oblicz pochodną.', 'Podstaw $x=0$.'] },
  { id: 'pa-09', topicSlug: 'parametry', lessonSlug: 'parametry-pochodna', type: 'open', difficulty: 5, points: 4, prompt: 'Wyznacz wartości $a$, dla których funkcja $f(x)=x^3-3ax^2$ ma punkt stacjonarny w $x=1$.', answer: '1/2', tags: ['stacjonarny'], skills: ['parametry-pochodna'], hints: ['Oblicz $f\'(x)=3x^2-6ax$.', 'Podstaw $x=1$ i przyrównaj do zera.'], solution: '$f\'(1)=3-6a=0$, stąd $a=\\frac12$.', steps: ['Oblicz pochodną.', 'Rozwiąż $3-6a=0$.'], rubric: [{ criterion: 'Poprawna pochodna', points: 1 }, { criterion: 'Warunek $f\'(1)=0$', points: 2 }, { criterion: 'Poprawny wynik $1/2$', points: 1 }] },
  { id: 'pa-10', topicSlug: 'parametry', lessonSlug: 'parametry-rownania', type: 'open', difficulty: 3, points: 3, prompt: 'Dla jakich wartości $a$ równanie $a x+3=0$ ma rozwiązanie?', answer: 'a≠0', tags: ['dziedzina'], skills: ['parametry-rownania'], hints: ['Rozważ $a=0$ osobno.'], solution: 'Dla $a\\neq0$ mamy $x=-3/a$. Dla $a=0$ dostajemy $3=0$, więc przypadek ten jest wykluczony.', steps: ['Rozważ $a=0$.', 'Dla pozostałych wartości wyznacz $x$.'], rubric: [{ criterion: 'Rozpatrzenie $a=0$', points: 1 }, { criterion: 'Warunek $a\\neq0$', points: 1 }, { criterion: 'Warunek na rozwiązanie', points: 1 }] },
]
