import type { ContentTask } from '@/content/types'

/**
 * Bank zadań do działu „Planimetria”. Kody `pl-*` są stabilnym kluczem importu.
 */
export const planimetriaTasks: ContentTask[] = [
  {
    id: 'pl-01',
    topicSlug: 'planimetria',
    lessonSlug: 'planimetria-trojkaty',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'W trójkącie kąty przy podstawie mają miary $35^{\\circ}$ i $85^{\\circ}$. Ile wynosi miara kąta przy wierzchołku?',
    answer: '60',
    acceptedAnswers: ['60', '60°'],
    tags: ['suma-katow'],
    skills: ['planimetria-wlasnosci'],
    hints: ['Suma kątów w trójkącie wynosi $180^{\\circ}$.', 'Odejmij od $180^{\\circ}$ sumę kątów przy podstawie.'],
    solution: '$180^{\\circ} - (35^{\\circ} + 85^{\\circ}) = 180^{\\circ} - 120^{\\circ} = 60^{\\circ}$.',
    steps: ['Zsumuj kąty przy podstawie: $35^{\\circ} + 85^{\\circ} = 120^{\\circ}$.', 'Odejmij od sumy kątów trójkąta.', 'Otrzymujesz $60^{\\circ}$.'],
  },
  {
    id: 'pl-02',
    topicSlug: 'planimetria',
    lessonSlug: 'planimetria-trojkaty',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'W trójkącie $ABC$ punkt $M$ jest środkiem boku $BC$. Przez $M$ poprowadzono prostą równoległą do $AB$, która przecina $AC$ w punkcie $N$. Jeśli $AC = 14$ cm, jaka jest długość $AN$?',
    answer: '7',
    acceptedAnswers: ['7', '7 cm'],
    tags: ['podobnosc', 'rownolegle'],
    skills: ['planimetria-podobnosc'],
    hints: ['Zauważ podobieństwo trójkątów $CMN$ i $CBA$.', 'Stosunek podobieństwa to $\\frac{CM}{CB} = \\frac{1}{2}$.'],
    solution: 'Trójkąty $CMN$ i $CBA$ są podobne (kąty naprzemienne), więc $\\frac{CN}{CA} = \\frac{CM}{CB} = \\frac{1}{2}$. Zatem $CN = \\frac{1}{2} \\cdot 14 = 7$ cm oraz $AN = 14 - 7 = 7$ cm.',
    steps: ['Zapisz podobieństwo: $\\triangle CMN \\sim \\triangle CBA$.', 'Oblicz $CN = \\frac{1}{2} AC = 7$ cm.', 'Odejmij: $AN = AC - CN = 7$ cm.'],
  },
  {
    id: 'pl-03',
    topicSlug: 'planimetria',
    lessonSlug: 'planimetria-pola',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Trójkąt prostokątny ma przyprostokątne długości $9$ i $12$. Oblicz długość przeciwprostokątnej.',
    answer: '15',
    acceptedAnswers: ['15'],
    tags: ['pitagoras'],
    skills: ['planimetria-pitagoras'],
    hints: ['Skorzystaj z twierdzenia Pitagorasa.', '$c = \\sqrt{9^{2} + 12^{2}}$'],
    solution: '$c = \\sqrt{81 + 144} = \\sqrt{225} = 15$.',
    steps: ['Zapisz: $a^{2} + b^{2} = c^{2}$.', 'Podstaw: $c^{2} = 81 + 144 = 225$.', 'Oblicz $c = 15$.'],
  },
  {
    id: 'pl-04',
    topicSlug: 'planimetria',
    lessonSlug: 'planimetria-pola',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Boki trójkąta mają długości $8$, $15$ i $17$. Trójkąt ten jest:',
    options: ['prostokątny', 'ostry', 'rozwarty', 'nie można tego określić'],
    answer: 'prostokątny',
    tags: ['pitagoras', 'odwrotnosc'],
    skills: ['planimetria-pitagoras'],
    hints: ['Sprawdź, czy najdłuższy bok spełnia warunek $a^{2} + b^{2} = c^{2}$.', 'Dla trójkąta prostokątnego suma kwadratów krótszych boków równa się kwadratowi najdłuższego.'],
    solution: '$8^{2} + 15^{2} = 64 + 225 = 289 = 17^{2}$. Na mocy odwrotności twierdzenia Pitagorasa trójkąt jest prostokątny.',
    steps: ['Oblicz kwadraty boków: $64$ i $225$.', 'Porównaj sumę $289$ z $17^{2}$.', 'Z równości wniosek: trójkąt jest prostokątny.'],
  },
  {
    id: 'pl-05',
    topicSlug: 'planimetria',
    lessonSlug: 'planimetria-pola',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'Trójkąt ma dwa boki o długości $6$ i $8$, a kąt między nimi ma miarę $30^{\\circ}$. Oblicz pole tego trójkąta.',
    answer: '12',
    acceptedAnswers: ['12'],
    tags: ['pole-trojkata', 'sinus'],
    skills: ['planimetria-pola'],
    hints: ['Skorzystaj ze wzoru $P = \\frac{1}{2} ab \\sin \\gamma$.', '$\\sin 30^{\\circ} = \\frac{1}{2}$'],
    solution: '$P = \\frac{1}{2} \\cdot 6 \\cdot 8 \\cdot \\sin 30^{\\circ} = 24 \\cdot \\frac{1}{2} = 12$.',
    steps: ['Zapisz wzór na pole z dwoma bokami i sinusem kąta.', 'Podstaw dane: $P = \\frac{1}{2} \\cdot 6 \\cdot 8 \\cdot \\frac{1}{2}$.', 'Oblicz $P = 12$.'],
  },
  {
    id: 'pl-06',
    topicSlug: 'planimetria',
    lessonSlug: 'planimetria-pola',
    type: 'open',
    level: 'extended',
    difficulty: 3,
    points: 3,
    prompt: 'Dwa boki trójkąta mają długości $5$ i $8$, a kąt między nimi ma miarę $60^{\\circ}$. Oblicz długość trzeciego boku.',
    answer: '7',
    acceptedAnswers: ['7'],
    tags: ['twierdzenie-o-cosinusach'],
    skills: ['planimetria-sinusy-cosinusy'],
    hints: ['Zastosuj twierdzenie o cosinusach: $c^{2} = a^{2} + b^{2} - 2ab\\cos \\gamma$.', 'Pamiętaj, że $\\cos 60^{\\circ} = \\frac{1}{2}$.'],
    solution: 'Z twierdzenia o cosinusach: $c^{2} = 5^{2} + 8^{2} - 2 \\cdot 5 \\cdot 8 \\cdot \\cos 60^{\\circ} = 25 + 64 - 80 \\cdot \\frac{1}{2} = 89 - 40 = 49$. Zatem $c = 7$.',
    steps: ['Zapisz wzór: $c^{2} = a^{2} + b^{2} - 2ab\\cos\\gamma$.', 'Podstaw dane: $25 + 64 - 80 \\cdot \\frac{1}{2}$.', 'Oblicz $c^{2} = 49$, czyli $c = 7$.'],
    rubric: [
      { criterion: 'Zastosowanie twierdzenia o cosinusach', points: 1 },
      { criterion: 'Poprawne podstawienie danych i wartości $\\cos 60^{\\circ}$', points: 1 },
      { criterion: 'Wynik $c = 7$ z wyjaśnieniem', points: 1 },
    ],
  },
  {
    id: 'pl-07',
    topicSlug: 'planimetria',
    lessonSlug: 'planimetria-pola',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Romb ma przekątne długości $6$ cm i $8$ cm. Oblicz jego pole.',
    answer: '24',
    acceptedAnswers: ['24'],
    tags: ['pole-rombu'],
    skills: ['planimetria-pola'],
    hints: ['Pole rombu liczymy z przekątnych, a nie z podstawy i wysokości.', '$P = \\frac{d_{1} d_{2}}{2}$'],
    solution: '$P = \\frac{6 \\cdot 8}{2} = 24$ cm².',
    steps: ['Zastosuj wzór na pole rombu.', 'Podstaw przekątne: $P = \\frac{6 \\cdot 8}{2}$.', 'Oblicz $24$ cm².'],
  },
  {
    id: 'pl-08',
    topicSlug: 'planimetria',
    lessonSlug: 'planimetria-okrag',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Kąt środkowy w okręgu ma miarę $100^{\\circ}$. Kąt wpisany oparty na tym samym łuku ma miarę:',
    options: ['$50^{\\circ}$', '$100^{\\circ}$', '$25^{\\circ}$', '$200^{\\circ}$'],
    answer: '$50^{\\circ}$',
    tags: ['katy-okregu'],
    skills: ['planimetria-katy-okregu'],
    hints: ['Kąt wpisany to połowa kąta środkowego na ten sam łuk.', 'Oblicz połowę z $100^{\\circ}$.'],
    solution: 'Kąt wpisany oparty na danym łarcu ma miarę równą połowie kąta środkowego: $\\frac{1}{2} \\cdot 100^{\\circ} = 50^{\\circ}$.',
    steps: ['Przypomnij zasadę: kąt wpisany to połowa kąta środkowego.', 'Oblicz: $100^{\\circ} : 2$.', 'Odpowiedź: $50^{\\circ}$.'],
  },
  {
    id: 'pl-09',
    topicSlug: 'planimetria',
    lessonSlug: 'planimetria-okrag',
    type: 'open',
    difficulty: 3,
    points: 3,
    prompt: 'Dwie cięciwy przecinają się wewnątrz okręgu. Kąt między nimi ma miarę $70^{\\circ}$. Ile wynosi miara kąta wpisanego opartego na łuku, który wyznacza druga para końców cięciw?',
    answer: '110',
    acceptedAnswers: ['110', '110°'],
    tags: ['katy-okregu', 'czworokat-wpisany'],
    skills: ['planimetria-katy-okregu'],
    hints: ['Kąty przeciwległe czworokąta wpisanego sumują się do $180^{\\circ}$.', 'Szukany kąt jest kątem wpisanym opartym na łuku wyznaczonym przez końce cięciw.'],
    solution: 'Czworokąt utworzony przez cztery końce cięciw jest czworokątem wpisanym, więc suma kątów przeciwległych wynosi $180^{\\circ}$. Szukany kąt: $180^{\\circ} - 70^{\\circ} = 110^{\\circ}$.',
    steps: ['Zauważ czworokąt wpisany powstały z czterech końców cięciw.', 'Zastosuj sumę kątów przeciwległych: $180^{\\circ}$.', 'Oblicz: $180^{\\circ} - 70^{\\circ} = 110^{\\circ}$.'],
    rubric: [
      { criterion: 'Rozpoznanie czworokąta wpisanego i sumy kątów przeciwległych', points: 1 },
      { criterion: 'Wykorzystanie zależności $180^{\\circ} - 70^{\\circ}$', points: 1 },
      { criterion: 'Wynik $110^{\\circ}$', points: 1 },
    ],
  },
  {
    id: 'pl-10',
    topicSlug: 'planimetria',
    lessonSlug: 'planimetria-okrag',
    type: 'numeric',
    level: 'extended',
    difficulty: 3,
    points: 2,
    prompt: 'Trójkąt prostokątny ma przyprostokątne $3$ i $4$. Oblicz promień okręgu wpisanego w ten trójkąt.',
    answer: '1',
    acceptedAnswers: ['1'],
    tags: ['okreg-wpisany', 'promien'],
    skills: ['planimetria-okregi'],
    hints: ['Najpierw wyznacz przeciwprostokątną i pole trójkąta.', 'Promień okręgu wpisanego to $r = \\frac{P}{s}$, gdzie $s$ to półobwód.'],
    solution: 'Przeciwprostokątna $c = 5$, pole $P = \\frac{1}{2} \\cdot 3 \\cdot 4 = 6$, obwód $12$, więc $s = 6$. Zatem $r = \\frac{P}{s} = \\frac{6}{6} = 1$.',
    steps: ['Wyznacz: $c = 5$, $P = 6$, $s = 6$.', 'Zastosuj wzór: $r = \\frac{P}{s}$.', 'Oblicz $r = 1$.'],
  },
  {
    id: 'pl-11',
    topicSlug: 'planimetria',
    lessonSlug: 'planimetria-okrag',
    type: 'single_choice',
    level: 'extended',
    difficulty: 3,
    points: 1,
    prompt: 'Trójkąt ma boki $13$, $14$ i $15$ oraz pole $84$. Promień okręgu opisanego ma długość:',
    options: ['$8{,}125$', '$7{,}5$', '$10$', '$14$'],
    answer: '$8{,}125$',
    tags: ['okreg-opisany', 'promien'],
    skills: ['planimetria-okregi'],
    hints: ['Użyj wzoru $R = \\frac{abc}{4P}$.', 'Wstaw $a = 13$, $b = 14$, $c = 15$ i $P = 84$.'],
    solution: '$R = \\frac{13 \\cdot 14 \\cdot 15}{4 \\cdot 84} = \\frac{2730}{336} = 8{,}125$.',
    steps: ['Zapisz wzór: $R = \\frac{abc}{4P}$.', 'Podstaw: $R = \\frac{13 \\cdot 14 \\cdot 15}{4 \\cdot 84}$.', 'Oblicz: $R = 8{,}125$.'],
  },
  {
    id: 'pl-12',
    topicSlug: 'planimetria',
    lessonSlug: 'planimetria-okrag',
    type: 'open',
    level: 'extended',
    difficulty: 4,
    points: 4,
    prompt: 'Trójkąt ma boki $10$ cm, $10$ cm i $12$ cm. Oblicz promień okręgu wpisanego w ten trójkąt.',
    answer: '3',
    acceptedAnswers: ['3', '3 cm'],
    tags: ['okreg-wpisany', 'pole-trojkata'],
    skills: ['planimetria-okregi'],
    hints: ['Trójkąt jest równoramienny — wysokość dzieli podstawę na dwie części po $6$.', 'Najpierw policz pole i półobwód, potem zastosuj $r = \\frac{P}{s}$.'],
    solution: 'Wysokość poprowadzona do podstawy $12$ dzieli ją na $6$ i $6$, więc $h = \\sqrt{10^{2} - 6^{2}} = \\sqrt{64} = 8$. Pole: $P = \\frac{1}{2} \\cdot 12 \\cdot 8 = 48$. Półobwód: $s = \\frac{10 + 10 + 12}{2} = 16$. Promień okręgu wpisanego: $r = \\frac{P}{s} = \\frac{48}{16} = 3$ cm.',
    steps: ['Wyznacz wysokość w trójkącie równoramiennym: $h = \\sqrt{10^{2} - 6^{2}} = 8$.', 'Oblicz pole $P = \\frac{1}{2} \\cdot 12 \\cdot 8 = 48$.', 'Oblicz półobwód $s = 16$.', 'Zastosuj $r = \\frac{P}{s}$ i podaj $3$ cm.'],
    rubric: [
      { criterion: 'Obliczenie wysokości trójkąta równoramiennego', points: 1 },
      { criterion: 'Obliczenie pola i półobwodu', points: 2 },
      { criterion: 'Zastosowanie wzoru $r = \\frac{P}{s}$ i wynik $3$ cm', points: 1 },
    ],
  },
]
