import type { ContentTask } from '@/content/types'

export const pochodneTasks: ContentTask[] = [
  { id: 'po-01', topicSlug: 'pochodne', lessonSlug: 'pochodne-obliczanie', type: 'text', difficulty: 1, points: 1, prompt: 'Oblicz pochodną $f(x)=x^3$.', answer: '3x^2', acceptedAnswers: ['3x^2', '3x²', '3*x^2', '3 x^2'], tags: ['pochodna'], skills: ['pochodne-obliczanie'], hints: ['Użyj reguły $(x^n)\'=nx^{n-1}$.'], solution: '$f\'(x)=3x^2$.', steps: ['Zastosuj wzór potęgi.', 'Zapisz wynik.'] },
  { id: 'po-02', topicSlug: 'pochodne', lessonSlug: 'pochodne-obliczanie', type: 'text', difficulty: 2, points: 1, prompt: 'Oblicz $f\'(x)$ dla $f(x)=x^2+4x$.', answer: '2x+4', acceptedAnswers: ['2x+4', '2x + 4', '4+2x'], tags: ['pochodna'], skills: ['pochodne-obliczanie'], hints: ['Pochodujemy każdy składnik osobno.'], solution: '$f\'(x)=2x+4$.', steps: ['Pochoduj $x^2$.', 'Pochoduj $4x$.'] },
  { id: 'po-03', topicSlug: 'pochodne', lessonSlug: 'pochodne-obliczanie', type: 'text', difficulty: 2, points: 1, prompt: 'Oblicz $f\'(x)$ dla $f(x)=x^3-6x$.', answer: '3x^2-6', acceptedAnswers: ['3x^2-6', '3x²-6', '-6+3x^2', '3*x^2-6'], tags: ['pochodna'], skills: ['pochodne-obliczanie'], hints: ['Pochoduj sumę.'], solution: '$f\'(x)=3x^2-6$.', steps: ['Pochoduj składniki.', 'Połącz wyniki.'] },
  { id: 'po-04', topicSlug: 'pochodne', lessonSlug: 'pochodne-obliczanie', type: 'single_choice', difficulty: 2, points: 1, prompt: 'Pochodna $f(x)=\\sin x$ to:', options: ['$\\cos x$', '$-\\cos x$', '$\\sin x$', '$x\\cos x$'], answer: '$\\cos x$', tags: ['trygonometria'], skills: ['pochodne-obliczanie'], hints: ['Znajdź podstawową pochodną sinusa.'], solution: 'Podstawowa reguła mówi, że $(\\sin x)\'=\\cos x$.', steps: ['Zastosuj regułę.', 'Wybierz $\\cos x$.'] },
  { id: 'po-05', topicSlug: 'pochodne', lessonSlug: 'pochodne-obliczanie', type: 'text', difficulty: 3, points: 1, prompt: 'Oblicz $f\'(x)$ dla $f(x)=x^2\\sin x$.', answer: '2x sin x + x^2 cos x', acceptedAnswers: ['2xsinx+x^2cosx', '2x sinx + x^2 cosx', '2x\\sin x+x^2\\cos x'], tags: ['iloczyn'], skills: ['pochodne-obliczanie'], hints: ['Zastosuj regułę iloczynu.'], solution: '$(x^2\\sin x)\'=2x\\sin x+x^2\\cos x$.', steps: ['Pochoduj $x^2$ i $\\sin x$.', 'Zastosuj iloczyn.'] },
  { id: 'po-06', topicSlug: 'pochodne', lessonSlug: 'pochodne-obliczanie', type: 'numeric', difficulty: 3, points: 1, prompt: 'Oblicz $f\'(1)$ dla $f(x)=x^2+3x$.', answer: '5', tags: ['wartosc-pochodnej'], skills: ['pochodne-obliczanie'], hints: ['Najpierw wyznacz $f\'(x)$.'], solution: '$f\'(x)=2x+3$, więc $f\'(1)=5$.', steps: ['Oblicz pochodną.', 'Podstaw 1.'] },
  { id: 'po-07', topicSlug: 'pochodne', lessonSlug: 'pochodne-monotonicznosc', type: 'numeric', difficulty: 2, points: 1, prompt: 'Wyznacz minimum funkcji $f(x)=x^2-4x$.', answer: '-4', tags: ['minimum'], skills: ['pochodne-monotonicznosc'], hints: ['Znajdź $f\'(x)=0$ i policz wartość.'], solution: '$f\'(x)=2x-4$, więc $x=2$ i $f(2)=-4$.', steps: ['Oblicz zero pochodnej.', 'Oblicz wartość funkcji.'] },
  { id: 'po-08', topicSlug: 'pochodne', lessonSlug: 'pochodne-monotonicznosc', type: 'text', difficulty: 2, points: 1, prompt: 'Podaj przedział, na którym $f(x)=x^2-2x+1$ jest malejąca.', answer: '(-infinity,1)', acceptedAnswers: ['(-infinity,1)', '(-nieskonczonosc,1)', '(-\\infty,1)', '(-∞,1)'], tags: ['monotonicznosc'], skills: ['pochodne-monotonicznosc'], hints: ['Oblicz $f\'(x)=2x-2$.'], solution: 'Pochodna jest ujemna dla $x<1$, więc funkcja jest malejąca na $(-\\infty,1)$.', steps: ['Oblicz pochodną.', 'Rozwiąż $f\'<0$.'] },
  { id: 'po-09', topicSlug: 'pochodne', lessonSlug: 'pochodne-monotonicznosc', type: 'open', difficulty: 3, points: 3, prompt: 'Zbadaj monotoniczność $f(x)=x^3-3x$ na $\\mathbb R$.', answer: 'rosnąca (-∞,-1) i (1,∞); malejąca (-1,1)', tags: ['monotonicznosc'], skills: ['pochodne-monotonicznosc'], hints: ['Oblicz $f\'(x)=3x^2-3$.'], solution: 'Krytyczne punkty to $x=-1,1$. Pochodna jest dodatnia na $(-\\infty,-1)$ i $(1,\\infty)$ oraz ujemna na $(-1,1)$.', steps: ['Wyznacz punkty krytyczne.', 'Zbadaj znak pochodnej.', 'Zapisz przedziały.'], rubric: [{ criterion: 'Punkty krytyczne', points: 1 }, { criterion: 'Znak pochodnej', points: 1 }, { criterion: 'Przedziały monotoniczności', points: 1 }] },
  { id: 'po-10', topicSlug: 'pochodne', lessonSlug: 'pochodne-monotonicznosc', type: 'single_choice', difficulty: 3, points: 1, prompt: 'Jeżeli pochodna zmienia znak z ujemnego na dodatni, to funkcja ma:', options: ['maksimum', 'minimum', 'punkt przegięcia', 'asymptotę'], answer: 'minimum', tags: ['ekstremum'], skills: ['pochodne-monotonicznosc'], hints: ['Obserwuj zmianę monotoniczności.'], solution: 'Zmiana malejąco na rosnąco oznacza minimum lokalne.', steps: ['Porównaj znaki.', 'Wybierz minimum.'] },
  { id: 'po-11', topicSlug: 'pochodne', lessonSlug: 'pochodne-styczna', type: 'numeric', difficulty: 3, points: 2, prompt: 'Oblicz współczynnik kierunkowy stycznej do $f(x)=x^2$ w punkcie $x_0=2$.', answer: '4', tags: ['styczna'], skills: ['pochodne-styczna'], hints: ['Współczynnik to $f\'(2)$.'], solution: '$f\'(x)=2x$, więc $f\'(2)=4$.', steps: ['Oblicz pochodną.', 'Podstaw 2.'] },
  { id: 'po-12', topicSlug: 'pochodne', lessonSlug: 'pochodne-styczna', type: 'open', difficulty: 4, points: 4, prompt: 'Wyznacz równanie stycznej do $f(x)=x^2$ w punkcie $(1,1)$.', answer: 'y=2x-1', tags: ['styczna'], skills: ['pochodne-styczna'], hints: ['Użyj $y-f(1)=f\'(1)(x-1)$.'], solution: '$f(1)=1$ i $f\'(1)=2$, więc $y-1=2(x-1)$, czyli $y=2x-1$.', steps: ['Oblicz wartość i pochodną.', 'Podstaw do równania stycznej.', 'Uprość.'], rubric: [{ criterion: 'Obliczenie współczynnika kierunkowego', points: 1 }, { criterion: 'Równanie stycznej', points: 2 }, { criterion: 'Poprawna postać $y=2x-1$', points: 1 }] },
  { id: 'po-13', topicSlug: 'pochodne', lessonSlug: 'pochodne-obliczanie', type: 'open', difficulty: 4, points: 4, prompt: 'Oblicz pochodną $f(x)=\\frac{x^2+1}{x}$ dla $x\\neq0$ i uprość wynik.', answer: '1-1/x^2', tags: ['iloraz'], skills: ['pochodne-obliczanie'], hints: ['Najpierw zapisz jako $x+1/x$.'], solution: '$f(x)=x+\\frac1x$, więc $f\'(x)=1-\\frac1{x^2}$ dla $x\\neq0$.', steps: ['Rozbij funkcję na sumę.', 'Pochoduj każdy składnik.'], rubric: [{ criterion: 'Zapis sumy', points: 1 }, { criterion: 'Pochodna $1-1/x^2$', points: 2 }, { criterion: 'Dziedzina', points: 1 }] },
  { id: 'po-14', topicSlug: 'pochodne', lessonSlug: 'pochodne-monotonicznosc', type: 'open', difficulty: 4, points: 4, prompt: 'Wyznacz wartość $a$, dla której $f(x)=x^3-3ax$ ma minimum w $x=1$.', answer: 'a=1', tags: ['parametr', 'minimum'], skills: ['pochodne-monotonicznosc'], hints: ['Warunek to $f\'(1)=0$.'], solution: '$f\'(x)=3x^2-3a$, więc $f\'(1)=3-3a=0$ i $a=1$.', steps: ['Oblicz pochodną.', 'Podstaw 1.', 'Rozwiąż warunek.'], rubric: [{ criterion: 'Pochodna', points: 1 }, { criterion: 'Warunek $f\'(1)=0$', points: 1 }, { criterion: 'Wynik $a=1$', points: 2 }] },
]
