import type { ContentTask } from '@/content/types'

/**
 * Bank zadań do działu „Prawdopodobieństwo”. Kody `pr-*` są stabilnym kluczem importu.
 */
export const prawdopodobienstwoTasks: ContentTask[] = [
  {
    id: 'pr-01',
    topicSlug: 'prawdopodobienstwo',
    lessonSlug: 'prawdopodobienstwo-klasyczne',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Rzucamy raz kostką sześcienną. Oblicz prawdopodobieństwo, że wypadnie więcej niż $4$.',
    answer: '1/3',
    acceptedAnswers: ['1/3', '2/6', '0,33', '0.33'],
    tags: ['prawdopodobienstwo-klasyczne'],
    skills: ['prawdopodobienstwo-klasyczne'],
    hints: ['Wyniki sprzyjające to $5$ i $6$.', 'Liczba wszystkich wyników to $6$.'],
    solution: '$P = \\frac{2}{6} = \\frac{1}{3}$.',
    steps: ['Wypisz wyniki sprzyjające: $5$, $6$ (czyli $2$ wyniki).', 'Liczba wszystkich wyników: $6$.', 'Oblicz: $P = \\frac{2}{6} = \\frac{1}{3}$.'],
  },
  {
    id: 'pr-02',
    topicSlug: 'prawdopodobienstwo',
    lessonSlug: 'prawdopodobienstwo-klasyczne',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Z woreczka, w którym są $4$ białe i $6$ czarnych kół, losujemy jedno kółko. Oblicz prawdopodobieństwo, że wyciągniemy czarne kółko.',
    answer: '3/5',
    acceptedAnswers: ['3/5', '0,6', '0.6'],
    tags: ['prawdopodobienstwo-klasyczne'],
    skills: ['prawdopodobienstwo-klasyczne'],
    hints: ['Liczba wyników sprzyjających: $6$.', 'Liczba wszystkich kółek: $4 + 6 = 10$.'],
    solution: '$P = \\frac{6}{10} = \\frac{3}{5}$.',
    steps: ['Policz czarne kółka: $6$.', 'Policz wszystkie: $10$.', 'Oblicz: $P = \\frac{6}{10} = \\frac{3}{5}$.'],
  },
  {
    id: 'pr-03',
    topicSlug: 'prawdopodobienstwo',
    lessonSlug: 'prawdopodobienstwo-klasyczne',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Rzucamy dwiema kostkami sześciennymi jednocześnie. Oblicz prawdopodobieństwo, że suma wyników jest większa niż $10$.',
    answer: '1/6',
    acceptedAnswers: ['1/6', '3/18', '0,17', '0.17'],
    tags: ['prawdopodobienstwo-klasyczne', 'dwie-kostki'],
    skills: ['prawdopodobienstwo-klasyczne'],
    hints: ['Łącznie jest $6 \\cdot 6 = 36$ równie prawdopodobnych wyników.', 'Suma większa niż $10$: $(5,6)$, $(6,5)$, $(6,6)$ — czyli $3$ wyniki.'],
    solution: 'Sprzyjające wyniki to $(5, 6)$, $(6, 5)$, $(6, 6)$ — razem $3$. Wszystkich wyników jest $36$, więc $P = \\frac{3}{36} = \\frac{1}{6}$.',
    steps: ['Wypisz wyniki, których suma przekracza $10$.', 'Policz sprzyjające: $3$ wyniki.', 'Oblicz: $P = \\frac{3}{36} = \\frac{1}{6}$.'],
  },
  {
    id: 'pr-04',
    topicSlug: 'prawdopodobienstwo',
    lessonSlug: 'prawdopodobienstwo-klasyczne',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Z $52$ kart losujemy jedną. Prawdopodobieństwo wyciągnięcia asów lub królowej wynosi:',
    options: ['$\\frac{1}{4}$', '$\\frac{1}{13}$', '$\\frac{2}{13}$', '$\\frac{1}{2}$'],
    answer: '$\\frac{2}{13}$',
    tags: ['prawdopodobienstwo-klasyczne', 'karty'],
    skills: ['prawdopodobienstwo-klasyczne'],
    hints: ['Asów jest $4$, królowych $4$ — łącznie $8$ kart.', 'Prawdopodobieństwo to $\\frac{8}{52}$.'],
    solution: 'Sprzyjające karty to $4$ asy i $4$ królowe, czyli $8$ kart. $P = \\frac{8}{52} = \\frac{2}{13}$.',
    steps: ['Policz sprzyjające karty: $4 + 4 = 8$.', 'Wszystkich kart: $52$.', 'Oblicz: $P = \\frac{8}{52} = \\frac{2}{13}$.'],
  },
  {
    id: 'pr-05',
    topicSlug: 'prawdopodobienstwo',
    lessonSlug: 'prawdopodobienstwo-klasyczne',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'W urnie jest $5$ kul białych i $3$ czarne. Losujemy dwie kule bez zwracania. Oblicz prawdopodobieństwo, że obie wylosowane kule są czarne.',
    answer: '3/28',
    acceptedAnswers: ['3/28', '0,107', '0.107'],
    tags: ['losowanie-bez-zwracania', 'kombinacje'],
    skills: ['prawdopodobienstwo-klasyczne'],
    hints: ['Wszystkich par kul: $C_{8}^{2} = 28$.', 'Par czarnych kul: $C_{3}^{2} = 3$.'],
    solution: 'Wszystkich możliwych par (bez zwracania) jest $C_{8}^{2} = 28$. Par złożonych z dwóch czarnych kul: $C_{3}^{2} = 3$. Stąd $P = \\frac{3}{28}$.',
    steps: ['Policz wszystkie pary: $C_{8}^{2} = 28$.', 'Policz pary złożone z czarnych: $C_{3}^{2} = 3$.', 'Oblicz: $P = \\frac{3}{28}$.'],
  },
  {
    id: 'pr-06',
    topicSlug: 'prawdopodobienstwo',
    lessonSlug: 'prawdopodobienstwo-klasyczne',
    type: 'open',
    difficulty: 3,
    points: 3,
    prompt: 'Losujemy dwie kule z urny, w której są $3$ białe, $4$ zielone i $5$ niebieskich. Oblicz prawdopodobieństwo, że wylosujemy kule różnych kolorów.',
    answer: '47/66',
    acceptedAnswers: ['47/66', '0,71', '0.71'],
    tags: ['losowanie-bez-zwracania', 'kombinacje'],
    skills: ['prawdopodobienstwo-klasyczne'],
    hints: ['Łącznie kul: $3 + 4 + 5 = 12$.', 'Policz pary różnych kolorów jako sumę: biała–zielona, biała–niebieska, zielona–niebieska.'],
    solution: 'Wszystkich par: $C_{12}^{2} = 66$. Pary różnych kolorów: $(3 \\cdot 4) + (3 \\cdot 5) + (4 \\cdot 5) = 12 + 15 + 20 = 47$. Prawdopodobieństwo wynosi zatem $\\frac{47}{66} \\approx 0{,}71$.',
    steps: ['Policz wszystkie pary: $C_{12}^{2} = 66$.', 'Zsumuj pary różnych kolorów: $12 + 15 + 20 = 47$.', 'Oblicz: $P = \\frac{47}{66} \\approx 0{,}712$.'],
    rubric: [
      { criterion: 'Obliczenie liczby wszystkich par', points: 1 },
      { criterion: 'Policzenie par różnych kolorów w trzech kategoriach', points: 1 },
      { criterion: 'Poprawny wynik $\\frac{47}{66}$', points: 1 },
    ],
  },
  {
    id: 'pr-07',
    topicSlug: 'prawdopodobienstwo',
    lessonSlug: 'prawdopodobienstwo-warunkowe',
    type: 'single_choice',
    difficulty: 3,
    points: 1,
    prompt: 'Z talii $52$ kart losujemy jedną i wiemy, że jest figurą (walet, dama lub król). Prawdopodobieństwo, że jest królem, wynosi:',
    options: ['$\\frac{1}{13}$', '$\\frac{1}{4}$', '$\\frac{1}{3}$', '$\\frac{1}{12}$'],
    answer: '$\\frac{1}{3}$',
    tags: ['prawdopodobienstwo-warunkowe'],
    skills: ['prawdopodobienstwo-warunkowe'],
    hints: ['Z warunkiem „figura” ograniczamy przestrzeń do figur — jest ich $4 \\cdot 3 = 12$.', 'W talii są $4$ króle, po jednym w każdym kolorze.'],
    solution: 'Figur jest $4 \\cdot 3 = 12$ (walety, damy i króle w czterech kolorach). Wśród nich są $4$ króle, zatem $P(\\text{król} \\mid \\text{figura}) = \\frac{4}{12} = \\frac{1}{3}$.',
    steps: ['Ustal liczbę figur: $4 \\cdot 3 = 12$.', 'Policz króle: $4$ (po jednym w każdym kolorze).', 'Oblicz: $P = \\frac{4}{12} = \\frac{1}{3}$.'],
  },
  {
    id: 'pr-08',
    topicSlug: 'prawdopodobienstwo',
    lessonSlug: 'prawdopodobienstwo-warunkowe',
    type: 'numeric',
    level: 'extended',
    difficulty: 3,
    points: 3,
    prompt: 'Z urny, w której jest $6$ białych i $4$ czarne kule, losujemy dwie kule bez zwracania. Oblicz prawdopodobieństwo, że druga wylosowana kula jest biała, jeśli wiemy, że pierwsza była czarna.',
    answer: '2/3',
    acceptedAnswers: ['2/3', '0,67', '0.67'],
    tags: ['prawdopodobienstwo-warunkowe', 'losowanie-bez-zwracania'],
    skills: ['prawdopodobienstwo-warunkowe'],
    hints: ['Po wyciągnięciu czarnej kuli w urnie zostaje $6$ białych i $3$ czarne.', 'To jest zwykły stosunek: sprzyjające do wszystkich w nowej urnie.'],
    solution: 'Po losowaniu czarnej kuli pozostaje $6$ białych i $3$ czarne, czyli $9$ kul. Prawdopodobieństwo, że następna jest biała: $\\frac{6}{9} = \\frac{2}{3}$.',
    steps: ['Zaktualizuj zawartość urny: $6$ białych, $3$ czarne.', 'Policz łączną liczbę: $9$.', 'Oblicz: $P = \\frac{6}{9} = \\frac{2}{3}$.'],
  },
  {
    id: 'pr-09',
    topicSlug: 'prawdopodobienstwo',
    lessonSlug: 'prawdopodobienstwo-warunkowe',
    type: 'open',
    level: 'extended',
    difficulty: 4,
    points: 4,
    prompt: 'Z dwóch urn losujemy jedną: pierwszą z prawdopodobieństwem $\\frac{2}{3}$, drugą z prawdopodobieństwem $\\frac{1}{3}$. Pierwsza urna zawiera $3$ białe i $5$ czarne kule, druga $1$ białą i $9$ czarnych. Oblicz prawdopodobieństwo wylosowania białej kuli.',
    answer: '17/60',
    acceptedAnswers: ['17/60', '0,28', '0.283'],
    tags: ['prawdopodobienstwo-calkowite', 'warunkowe'],
    skills: ['prawdopodobienstwo-warunkowe'],
    hints: ['To wzór na prawdopodobieństwo całkowite — sumuj po obu urnach.', 'Dla każdej urny: prawdopodobieństwo wyboru urny razy prawdopodobieństwo białej kuli.'],
    solution: 'Z prawdopodobieństwem całkowitym: $P(\\text{biała}) = \\frac{2}{3} \\cdot \\frac{3}{8} + \\frac{1}{3} \\cdot \\frac{1}{10} = \\frac{1}{4} + \\frac{1}{30} = \\frac{15}{60} + \\frac{2}{60} = \\frac{17}{60}$.',
    steps: ['Rozłóż zdarzenie na dwa rozłączne przypadki: wybrano urnę 1 albo urnę 2.', 'Oblicz produkty: $\\frac{2}{3} \\cdot \\frac{3}{8} = \\frac{1}{4}$ oraz $\\frac{1}{3} \\cdot \\frac{1}{10} = \\frac{1}{30}$.', 'Zsumuj: $\\frac{1}{4} + \\frac{1}{30} = \\frac{17}{60}$.'],
    rubric: [
      { criterion: 'Rozłożenie zdarzenia na rozłączne przypadki', points: 1 },
      { criterion: 'Obliczenie iloczynów dla obu urn', points: 2 },
      { criterion: 'Suma i wynik $\\frac{17}{60}$', points: 1 },
    ],
  },
  {
    id: 'pr-10',
    topicSlug: 'prawdopodobienstwo',
    lessonSlug: 'prawdopodobienstwo-warunkowe',
    type: 'numeric',
    level: 'extended',
    difficulty: 3,
    points: 3,
    prompt: 'Rzucamy monetą $3$ razy. Oblicz prawdopodobieństwo, że wypadnie dokładnie dwa orły.',
    answer: '3/8',
    acceptedAnswers: ['3/8', '0,375', '0.375'],
    tags: ['schemat-bernoulliego', 'rozklad-dwumianowy'],
    skills: ['prawdopodobienstwo-bernoulli'],
    hints: ['Zastosuj rozkład dwumianowy: $\\binom{n}{k} p^{k} (1 - p)^{n - k}$.', 'Współczynnik $\\binom{3}{2} = 3$ odpowiada liczbie sposobów ustawienia dwóch orłów.'],
    solution: '$P(X = 2) = \\binom{3}{2} \\left(\\frac{1}{2}\\right)^{2} \\left(\\frac{1}{2}\\right)^{1} = 3 \\cdot \\frac{1}{4} \\cdot \\frac{1}{2} = \\frac{3}{8}$.',
    steps: ['Zastosuj wzór: $P(X = k) = \\binom{n}{k} p^{k}(1-p)^{n-k}$.', 'Podstaw $n = 3$, $k = 2$, $p = \\frac{1}{2}$.', 'Oblicz: $3 \\cdot \\frac{1}{4} \\cdot \\frac{1}{2} = \\frac{3}{8}$.'],
  },
  {
    id: 'pr-11',
    topicSlug: 'prawdopodobienstwo',
    lessonSlug: 'prawdopodobienstwo-warunkowe',
    type: 'open',
    level: 'extended',
    difficulty: 4,
    points: 4,
    prompt: 'W losowaniu z urny trafienie ma prawdopodobieństwo $0{,}2$ przy każdym losowaniu. Oblicz prawdopodobieństwo, że przy czterech niezależnych losowaniach trafisz dokładnie trzy razy.',
    answer: '16/625',
    acceptedAnswers: ['16/625', '0,0256', '0.0256'],
    tags: ['schemat-bernoulliego', 'rozklad-dwumianowy'],
    skills: ['prawdopodobienstwo-bernoulli'],
    hints: ['Zastosuj rozkład dwumianowy dla $n = 4$ i $k = 3$.', 'Nie zapomnij o czynniku $\\binom{4}{3} = 4$.'],
    solution: '$P(X = 3) = \\binom{4}{3} (0{,}2)^{3} (0{,}8)^{1} = 4 \\cdot 0{,}008 \\cdot 0{,}8 = 0{,}0256 = \\frac{16}{625}$.',
    steps: ['Zapisz wzór: $P(X = 3) = \\binom{4}{3} p^{3}(1 - p)^{1}$.', 'Podstaw $p = 0{,}2$ oraz $(1 - p) = 0{,}8$.', 'Oblicz: $4 \\cdot 0{,}008 \\cdot 0{,}8 = 0{,}0256$.'],
    rubric: [
      { criterion: 'Zastosowanie wzoru na rozkład dwumianowy', points: 1 },
      { criterion: 'Uwzględnienie współczynnika $\\binom{4}{3}$', points: 1 },
      { criterion: 'Obliczenie iloczynu $4 \\cdot 0{,}008 \\cdot 0{,}8$', points: 1 },
      { criterion: 'Poprawny wynik $\\frac{16}{625}$', points: 1 },
    ],
  },
  {
    id: 'pr-12',
    topicSlug: 'prawdopodobienstwo',
    lessonSlug: 'prawdopodobienstwo-warunkowe',
    type: 'open',
    level: 'extended',
    difficulty: 5,
    points: 5,
    prompt: 'Tenisista rozegra dwa kolejne serwisy. W pierwszym serwuje on i wygrywa go z prawdopodobieństwem $0{,}6$, a w drugim serwuje rywal i tenisista wygrywa ten serwis z prawdopodobieństwem $0{,}4$. Serwisy są od siebie niezależne. Oblicz prawdopodobieństwo, że tenisista wygra przynajmniej jeden z nich.',
    answer: '0,76',
    acceptedAnswers: ['0,76', '0.76', '76%', '19/25'],
    tags: ['prawdopodobienstwo-calkowite', 'dopełnienie-zdarzenia'],
    skills: ['prawdopodobienstwo-warunkowe', 'prawdopodobienstwo-klasyczne'],
    hints: ['Łatwiej obliczyć zdarzenie przeciwne: tenisista przegra oba serwisy.', 'Skorzystaj z niezależności serwisów.'],
    solution: 'Oba serwisy przegrane: $(1 - 0{,}6) \\cdot (1 - 0{,}4) = 0{,}4 \\cdot 0{,}6 = 0{,}24$. Zatem prawdopodobieństwo wygrania przynajmniej jednego serwisu to $1 - 0{,}24 = 0{,}76$.',
    steps: ['Rozważ zdarzenie przeciwne: przegranie obu serwisów.', 'Oblicz: $0{,}4 \\cdot 0{,}6 = 0{,}24$.', 'Odejmij od $1$: $1 - 0{,}24 = 0{,}76$.'],
    rubric: [
      { criterion: 'Rozpoznanie zdarzenia przeciwnego (przegranie obu serwisów)', points: 2 },
      { criterion: 'Obliczenie iloczynu prawdopodobieństw', points: 2 },
      { criterion: 'Odejęcie od $1$ i wynik', points: 1 },
    ],
  },
]
