import type { ContentTask } from '@/content/types'

/**
 * Bank zadań do działu „Liczby rzeczywiste” (poziom podstawowy).
 * Każde zadanie ma kod `id`, którego używa importer jako stabilnego klucza.
 */
export const realneTasks: ContentTask[] = [
  {
    id: 'rr-01',
    topicSlug: 'realne',
    lessonSlug: 'realne-zadania',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Oblicz: $2^{3}\\cdot 2^{-5}\\cdot 2^{4}$',
    answer: '4',
    acceptedAnswers: ['4', '4,0'],
    tags: ['potegi', 'zamkniete'],
    skills: ['realne-potegi'],
    hints: ['Przy mnożeniu potęg o tej samej podstawie dodajemy wykładniki.', 'Wykładniki to 3, -5 i 4.'],
    solution: 'Dodajemy wykładniki: $3 + (-5) + 4 = 2$, więc wynik to $2^{2} = 4$.',
    steps: ['Zastosuj $a^{m}\\cdot a^{n} = a^{m+n}$.', 'Suma wykładników wynosi 2.', 'Odpowiedź: $4$.'],
  },
  {
    id: 'rr-02',
    topicSlug: 'realne',
    lessonSlug: 'realne-zadania',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Oblicz: $\\left(\\frac{1}{3}\\right)^{-2}$',
    answer: '9',
    acceptedAnswers: ['9', '9,0'],
    tags: ['potegi', 'wykladnik-ujemny'],
    skills: ['realne-potegi'],
    hints: ['Ujemny wykładnik odwraca podstawę.', '$a^{-n} = \\frac{1}{a^{n}}$.'],
    solution: '$\\left(\\frac{1}{3}\\right)^{-2} = 3^{2} = 9$.',
    steps: ['Zamień wykładnik ujemny na dodatni, odwracając podstawę.', '$3^{2} = 9$.'],
  },
  {
    id: 'rr-03',
    topicSlug: 'realne',
    lessonSlug: 'realne-zadania',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Oblicz: $\\sqrt{49\\cdot 25}$',
    answer: '35',
    acceptedAnswers: ['35', '35,0'],
    tags: ['pierwiastki'],
    skills: ['realne-pierwiastki'],
    hints: ['Pierwiastek iloczynu to iloczyn pierwiastków.', '$\\sqrt{49} = 7$, $\\sqrt{25} = 5$.'],
    solution: '$\\sqrt{49\\cdot 25} = \\sqrt{49}\\cdot\\sqrt{25} = 7\\cdot 5 = 35$.',
    steps: ['Rozdziel pierwiastek na iloczyn pierwiastków.', 'Wymnaż 7 i 5.'],
  },
  {
    id: 'rr-04',
    topicSlug: 'realne',
    lessonSlug: 'realne-zadania',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Oblicz: $(\\sqrt{50}-\\sqrt{18})\\cdot\\sqrt{2}$',
    answer: '4',
    acceptedAnswers: ['4', '4,0'],
    tags: ['pierwiastki', 'wyciaganie-czynnika'],
    skills: ['realne-pierwiastki'],
    hints: ['Wyłącz kwadraty przed pierwiastek: $\\sqrt{50} = 5\\sqrt{2}$.', 'Po uproszczeniu w nawiasie zostaje $2\\sqrt{2}$.'],
    solution: '$\\sqrt{50} = 5\\sqrt{2}$, $\\sqrt{18} = 3\\sqrt{2}$, więc w nawiasie mamy $2\\sqrt{2}$. Następnie $2\\sqrt{2}\\cdot\\sqrt{2} = 2\\cdot 2 = 4$.',
    steps: ['Uprość oba pierwiastki.', 'Zredukuj wyrazy podobne.', 'Pomnóż przez $\\sqrt{2}$.'],
  },
  {
    id: 'rr-05',
    topicSlug: 'realne',
    lessonSlug: 'realne-zadania',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Oblicz: $|3-8| + |-5|$',
    answer: '10',
    acceptedAnswers: ['10', '10,0'],
    tags: ['wartosc-bezwzgledna'],
    skills: ['realne-wartosc-bezwzgledna'],
    hints: ['Najpierw policz wartość pod pierwszym modułem.', '$3-8 = -5$, a $|-5| = 5$.'],
    solution: '$|3-8| = |-5| = 5$, $|-5| = 5$, czyli suma wynosi $10$.',
    steps: ['Oblicz wyrażenie wewnątrz modułu.', 'Zamień na wartość nieujemną.', 'Dodaj oba wyniki.'],
  },
  {
    id: 'rr-06',
    topicSlug: 'realne',
    lessonSlug: 'realne-zadania',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Oblicz: $5^{0} + \\left(\\frac{1}{5}\\right)^{-1}$',
    answer: '6',
    acceptedAnswers: ['6', '6,0'],
    tags: ['potegi', 'wykladnik-zero'],
    skills: ['realne-potegi'],
    hints: ['Każda liczba różna od zera podniesiona do potęgi 0 daje 1.', 'Ujemny wykładnik odwraca podstawę: $\\left(\\frac{1}{5}\\right)^{-1} = 5$.'],
    solution: '$5^{0} = 1$ oraz $\\left(\\frac{1}{5}\\right)^{-1} = 5$. Suma wynosi $6$.',
    steps: ['Zamień $5^{0}$ na 1.', 'Odwróć podstawę przy wykładniku ujemnym.', 'Dodaj wyniki.'],
  },
  {
    id: 'rr-07',
    topicSlug: 'realne',
    lessonSlug: 'realne-zadania',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Oblicz: $\\sqrt{2^{6}}$',
    answer: '8',
    acceptedAnswers: ['8', '8,0'],
    tags: ['pierwiastki', 'potegi'],
    skills: ['realne-pierwiastki', 'realne-potegi'],
    hints: ['Pierwiastek kwadratowy to potęga o wykładniku $\\frac{1}{2}$.', '$\\left(2^{6}\\right)^{\\frac{1}{2}} = 2^{3}$.'],
    solution: '$\\sqrt{2^{6}} = \\left(2^{6}\\right)^{\\frac{1}{2}} = 2^{6\\cdot\\frac{1}{2}} = 2^{3} = 8$.',
    steps: ['Zapisz pierwiastek jako potęgę $\\frac{1}{2}$.', 'Pomnóż wykładniki.', 'Oblicz $2^{3}$.'],
  },
  {
    id: 'rr-08',
    topicSlug: 'realne',
    lessonSlug: 'realne-zadania',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Oblicz: $\\left(\\sqrt[3]{27}\\right)^{-1}\\cdot 3^{3}$',
    answer: '9',
    acceptedAnswers: ['9', '9,0'],
    tags: ['pierwiastki', 'potegi'],
    skills: ['realne-pierwiastki', 'realne-potegi'],
    hints: ['$\\sqrt[3]{27} = 3$ — pierwiastek sześcienny nie jest ujemny.', 'Zostaje $3^{-1}\\cdot 3^{3}$.'],
    solution: '$\\sqrt[3]{27} = 3$, więc $3^{-1}\\cdot 3^{3} = 3^{-1+3} = 3^{2} = 9$.',
    steps: ['Policz pierwiastek sześcienny.', 'Dodaj wykładniki przy tej samej podstawie.'],
  },
  {
    id: 'rr-09',
    topicSlug: 'realne',
    lessonSlug: 'realne-zadania',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Cenę pewnego towaru równą 200 zł podniesiono o 15%, a następnie obniżono o 10%. Jaka jest cena końcowa (w złotych)?',
    answer: '207',
    acceptedAnswers: ['207', '207,0', '207 zł'],
    tags: ['procenty', 'kontekst'],
    skills: ['realne-procenty', 'realne-liczby-wymierne'],
    hints: ['Podwyżka o 15% to mnożenie przez $1{,}15$.', 'Obniżka o 10% to mnożenie przez $0{,}9$.'],
    solution: '$200\\cdot 1{,}15 = 230$, następnie $230\\cdot 0{,}9 = 207$. Cena końcowa to 207 zł.',
    steps: ['Pomnóż cenę przez $1{,}15$.', 'Pomnóż wynik przez $0{,}9$.'],
  },
  {
    id: 'rr-10',
    topicSlug: 'realne',
    lessonSlug: 'realne-zadania',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Jakim procentem liczby 160 jest liczba 40?',
    answer: '25',
    acceptedAnswers: ['25', '25%', '25,0'],
    tags: ['procenty'],
    skills: ['realne-procenty'],
    hints: ['Podziel część przez całość.', '$\\frac{40}{160} = 0{,}25$.'],
    solution: '$\\frac{40}{160} = \\frac{1}{4} = 0{,}25$, czyli 25%.',
    steps: ['Podziel 40 przez 160.', 'Zamień ułamek na procenty.'],
  },
  {
    id: 'rr-11',
    topicSlug: 'realne',
    lessonSlug: 'realne-zadania',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Dla $x = -3$ oblicz wartość wyrażenia $|x+5| - |x|$.',
    answer: '-1',
    acceptedAnswers: ['-1', '-1,0'],
    tags: ['wartosc-bezwzgledna'],
    skills: ['realne-wartosc-bezwzgledna'],
    hints: ['Podstaw $x = -3$ do obu modułów.', '$|-3+5| = 2$ oraz $|-3| = 3$.'],
    solution: '$|-3+5| = |2| = 2$ i $|-3| = 3$, więc $2 - 3 = -1$.',
    steps: ['Podstaw wartość $x$.', 'Policz oba moduły.', 'Odejmij.'],
  },
  {
    id: 'rr-12',
    topicSlug: 'realne',
    lessonSlug: 'realne-fundamenty',
    type: 'single_choice',
    difficulty: 1,
    points: 1,
    prompt: 'Która z liczb jest niewymierna?',
    options: ['$0{,}(3)$', '$\\sqrt{9}$', '$\\sqrt{7}$', '$\\frac{22}{7}$'],
    answer: '$\\sqrt{7}$',
    acceptedAnswers: ['sqrt(7)', '√7'],
    tags: ['zbiory-liczbowe', 'zamkniete'],
    skills: ['realne-zbiory-liczbowe', 'realne-liczby-wymierne'],
    hints: ['Liczba wymierna ma rozwinięcie skończone lub okresowe.', '$\\sqrt{9} = 3$ jest całkowita.'],
    solution: '$0{,}(3) = \\frac{1}{3}$ jest wymierna, $\\sqrt{9} = 3$ jest całkowita, a $\\frac{22}{7}$ to ułamek. Niewymierny jest tylko $\\sqrt{7}$.',
    steps: ['Sprawdź, czy liczbę można zapisać jako ułamek.', 'Wybierz liczbę o nieskończonym, nieokresowym rozwinięciu.'],
  },
  {
    id: 'rr-13',
    topicSlug: 'realne',
    lessonSlug: 'realne-matura',
    type: 'numeric',
    difficulty: 3,
    points: 3,
    prompt: 'Oblicz: $(\\sqrt{2}+\\sqrt{8})^{2}$',
    answer: '18',
    acceptedAnswers: ['18', '18,0'],
    tags: ['pierwiastki', 'otwarte'],
    skills: ['realne-pierwiastki', 'realne-oszacowanie'],
    hints: ['Najpierw uprość $\\sqrt{8} = 2\\sqrt{2}$.', 'Suma w nawiasie to $3\\sqrt{2}$.'],
    solution: '$\\sqrt{8} = 2\\sqrt{2}$, więc $\\sqrt{2}+\\sqrt{8} = 3\\sqrt{2}$. Podnosząc do kwadratu: $(3\\sqrt{2})^{2} = 9\\cdot 2 = 18$.',
    steps: ['Uprość drugi pierwiastek.', 'Zredukuj wyrazy podobne.', 'Podnieś do kwadratu: kwadrat iloczynu.'],
  },
  {
    id: 'rr-14',
    topicSlug: 'realne',
    lessonSlug: 'realne-matura',
    type: 'proof',
    difficulty: 3,
    points: 3,
    prompt: 'Wykaż, że dla każdej liczby rzeczywistej $x$ zachodzi nierówność $x^{2}+4x+5 > 0$.',
    answer: 'x^2+4x+5 = (x+2)^2+1 > 0, bo (x+2)^2 >= 0',
    acceptedAnswers: ['(x+2)^2+1', 'suma kwadratu i jedynki'],
    tags: ['dowod', 'otwarte'],
    skills: ['realne-dowodzenie-nierownosci'],
    hints: ['Uzupełnij wyrażenie do pełnego kwadratu.', 'Zauważ, że $x^{2}+4x = (x+2)^{2}-4$.'],
    solution: 'Przekształcamy lewą stronę: $x^{2}+4x+5 = (x^{2}+4x+4)+1 = (x+2)^{2}+1$. Ponieważ $(x+2)^{2} \\geq 0$ dla każdego $x$, mamy $(x+2)^{2}+1 \\geq 1 > 0$, co kończy dowód.',
    steps: ['Dodaj i odejmij $4$, aby uzyskać pełny kwadrat.', 'Zapisz wyrażenie jako $(x+2)^{2}+1$.', 'Uzasadnij znak: kwadrat nieujemny plus 1.'], rubric: [{ criterion: 'Dokończenie do kwadratu', points: 1 }, { criterion: 'Uzasadnienie nieujemności kwadratu', points: 1 }, { criterion: 'Wniosek $x^2+4x+5>0$', points: 1 }],
  },
  {
    id: 'rr-15',
    topicSlug: 'realne',
    lessonSlug: 'realne-matura',
    type: 'numeric',
    difficulty: 3,
    points: 3,
    prompt: 'Oblicz sumę wszystkich liczb całkowitych $x$ spełniających nierówność $|x-1| \\leq 2$.',
    answer: '5',
    acceptedAnswers: ['5', '5,0'],
    tags: ['wartosc-bezwzgledna', 'otwarte'],
    skills: ['realne-wartosc-bezwzgledna'],
    hints: ['Odległość $x$ od 1 jest nie większa niż 2.', 'Zapisz przedział: $x \\in [-1, 3]$.'],
    solution: 'Z nierówności $|x-1| \\leq 2$ wynika $-2 \\leq x-1 \\leq 2$, czyli $-1 \\leq x \\leq 3$. Liczby całkowite w tym przedziale to $-1, 0, 1, 2, 3$, a ich suma wynosi $5$.',
    steps: ['Rozpisz moduł jako podwójną nierówność.', 'Wyznacz przedział rozwiązań.', 'Zsumuj liczby całkowite z przedziału.'],
  },
  {
    id: 'rr-16',
    topicSlug: 'realne',
    lessonSlug: 'realne-matura',
    type: 'proof',
    difficulty: 3,
    points: 3,
    prompt: 'Wykaż, że $\\sqrt{7+4\\sqrt{3}} = 2+\\sqrt{3}$.',
    answer: '(2+sqrt(3))^2 = 7+4sqrt(3)',
    acceptedAnswers: ['(2+√3)^2 = 7+4√3'],
    tags: ['dowod', 'pierwiastki', 'otwarte'],
    skills: ['realne-dowodzenie-nierownosci', 'realne-pierwiastki'],
    hints: ['Podnieś prawą stronę do kwadratu.', 'Użyj wzoru $(a+b)^{2} = a^{2}+2ab+b^{2}$.'],
    solution: 'Podnosimy prawą stronę do kwadratu: $(2+\\sqrt{3})^{2} = 4 + 4\\sqrt{3} + 3 = 7 + 4\\sqrt{3}$. Liczba $2+\\sqrt{3}$ jest dodatnia, więc z równości kwadratów wynika $\\sqrt{7+4\\sqrt{3}} = 2+\\sqrt{3}$, co kończy dowód.',
    steps: ['Oblicz $(2+\\sqrt{3})^{2}$.', 'Uzasadnij, że prawa strona jest dodatnia.', 'Wyciągnij pierwiastek z obu stron.'], rubric: [{ criterion: 'Obliczenie kwadratu', points: 1 }, { criterion: 'Dodatniość prawej strony', points: 1 }, { criterion: 'Wniosek z równości', points: 1 }],
  },
  {
    id: 'rr-17',
    topicSlug: 'realne',
    lessonSlug: 'realne-matura',
    type: 'proof',
    difficulty: 3,
    points: 3,
    prompt: 'Wykaż, że różnica kwadratów dwóch kolejnych liczb nieparzystych jest podzielna przez 8.',
    answer: '8n',
    acceptedAnswers: ['8k', 'podzielna przez 8'],
    tags: ['dowod', 'podzielnosc', 'otwarte'],
    skills: ['realne-dowodzenie-nierownosci'],
    hints: ['Zapisz kolejne liczby nieparzyste jako $2n+1$ i $2n-1$.', 'Skorzystaj ze wzoru na różnicę kwadratów.'],
    solution: 'Niech kolejne liczby nieparzyste to $2n+1$ oraz $2n-1$ dla $n$ całkowitego. Wtedy $(2n+1)^{2}-(2n-1)^{2} = \\big((2n+1)-(2n-1)\\big)\\big((2n+1)+(2n-1)\\big) = 2\\cdot 4n = 8n$, a liczba $8n$ jest podzielna przez $8$.',
    steps: ['Oznacz liczby jako $2n+1$ i $2n-1$.', 'Zastosuj $a^{2}-b^{2}=(a-b)(a+b)$.', 'Odczytaj czynnik 8.'], rubric: [{ criterion: 'Zapis liczb nieparzystych', points: 1 }, { criterion: 'Rozłożenie różnicy kwadratów', points: 1 }, { criterion: 'Wniosek o podzielności', points: 1 }],
  },
  {
    id: 'rr-18',
    topicSlug: 'realne',
    lessonSlug: 'realne-matura',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'Liczba $x = 2-\\sqrt{3}$. Oblicz $\\dfrac{1}{x}$ i zapisz wynik w postaci $a+b\\sqrt{3}$, gdzie $a$ i $b$ są liczbami całkowitymi. Podaj wartość $a+b$.',
    answer: '3',
    acceptedAnswers: ['3', '3,0'],
    tags: ['pierwiastki', 'niewymiernosc'],
    skills: ['realne-pierwiastki'],
    hints: ['Usuń niewymierność z mianownika, mnożąc przez sprzężenie $2+\\sqrt{3}$.', 'W mianowniku pojawi się różnica kwadratów: $(2-\\sqrt{3})(2+\\sqrt{3}) = 4-3$.'],
    solution: '$\\dfrac{1}{2-\\sqrt{3}} = \\dfrac{2+\\sqrt{3}}{(2-\\sqrt{3})(2+\\sqrt{3})} = \\dfrac{2+\\sqrt{3}}{4-3} = 2+\\sqrt{3}$. Zatem $a = 2$ i $b = 1$, czyli $a+b = 3$.',
    steps: ['Pomnóż licznik i mianownik przez sprzężenie $2+\\sqrt{3}$.', 'Oblicz mianownik jako różnicę kwadratów: $4-3 = 1$.', 'Odczytaj $a=2$, $b=1$ i wyznacz $a+b = 3$.'],
  },
]
