import type { ContentTask } from '@/content/types'

/**
 * Bank zadań do działu „Równania i nierówności” (poziom podstawowy z elementami rozszerzenia).
 * Kody `ro-*` są stabilnym kluczem importu — nie zmieniaj ich przy edycji treści.
 */
export const rownaniaTasks: ContentTask[] = [
  {
    id: 'ro-01',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-liniowe',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Rozwiąż równanie $3x - 7 = 8$.',
    answer: '5',
    acceptedAnswers: ['5', '5,0'],
    tags: ['liniowe', 'przeksztalcenia'],
    skills: ['rownania-liniowe'],
    hints: ['Przenieś wyraz wolny na prawą stronę.', 'Następnie podziel obie strony przez współczynnik przy $x$.'],
    solution: '$3x - 7 = 8$, więc $3x = 15$ i $x = 5$.',
    steps: ['Dodaj $7$ do obu stron: $3x = 15$.', 'Podziel przez $3$.', '$x = 5$.'],
  },
  {
    id: 'ro-02',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-liniowe',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Rozwiąż równanie $2(x-3) = x + 4$.',
    answer: '10',
    acceptedAnswers: ['10', '10,0'],
    tags: ['liniowe', 'nawiasy'],
    skills: ['rownania-liniowe'],
    hints: ['Najpierw opuść nawias.', '$2x - 6 = x + 4$'],
    solution: '$2x - 6 = x + 4$, czyli $2x - x = 4 + 6$ i $x = 10$. Sprawdzenie: $2 \\cdot 7 = 14$ oraz $10 + 4 = 14$.',
    steps: ['Opuść nawias: $2x - 6 = x + 4$.', 'Przenieś niewiadome na lewo: $x = 10$.', 'Sprawdź wynik podstawieniem.'],
  },
  {
    id: 'ro-03',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-liniowe',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Które z równań nie ma rozwiązania?',
    options: ['$2x = 2x + 1$', '$x + 1 = 3$', '$2x = 0$', '$x - 1 = 2x$'],
    answer: '$2x = 2x + 1$',
    tags: ['liniowe', 'sprzeczne'],
    skills: ['rownania-liniowe'],
    hints: ['Przenieś $2x$ na jedną stronę.', 'Zobacz, co zostaje po uporządkowaniu równania.'],
    solution: 'Po odjęciu $2x$ od obu stron zostaje $0 = 1$ — sprzeczność, więc równanie nie ma rozwiązań. Pozostałe równania mają rozwiązania: $x = 2$, $x = 0$ i $x = -1$.',
    steps: ['Upodobnij wyrazy z $x$ po jednej stronie.', 'Otrzymujesz $0 = 1$.', 'Sprzeczność oznacza brak rozwiązań.'],
  },
  {
    id: 'ro-04',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-liniowe',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Podaj największą liczbę całkowitą spełniającą nierówność $5 - 2x > 1$.',
    answer: '1',
    acceptedAnswers: ['1'],
    tags: ['nierownosci', 'liczby-calkowite'],
    skills: ['rownania-nierownosci-liniowe'],
    hints: ['Odejmij $5$ od obu stron.', 'Dzieląc przez liczbę ujemną, odwróć znak nierówności.'],
    solution: '$5 - 2x > 1$, więc $-2x > -4$. Dzielimy przez $-2$ i odwracamy znak: $x < 2$. Największa liczba całkowita mniejsza od $2$ to $1$.',
    steps: ['Odejmij $5$: $-2x > -4$.', 'Podziel przez $-2$ i odwróć znak: $x < 2$.', 'Największa liczba całkowita to $1$.'],
  },
  {
    id: 'ro-05',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-liniowe',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Rozwiąż równanie $\\frac{x+2}{3} = \\frac{2x-1}{5}$.',
    answer: '13',
    acceptedAnswers: ['13', '13,0'],
    tags: ['liniowe', 'ulamki'],
    skills: ['rownania-liniowe'],
    hints: ['Pomnóż obie strony przez $15$ (wspólny mianownik).', '$5(x+2) = 3(2x-1)$'],
    solution: '$5(x+2) = 3(2x-1)$, więc $5x + 10 = 6x - 3$ i $x = 13$. Sprawdzenie: $\\frac{15}{3} = 5$ oraz $\\frac{25}{5} = 5$.',
    steps: ['Pomnóż przez $15$.', 'Opuść nawiasy: $5x + 10 = 6x - 3$.', 'Wyznacz $x = 13$.'],
  },
  {
    id: 'ro-06',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-liniowe',
    type: 'open',
    difficulty: 3,
    points: 3,
    prompt: 'Rozwiąż równanie $4(x-1) - 3(2x+1) = 5 + 2x$.',
    answer: '-3',
    acceptedAnswers: ['-3', '−3'],
    tags: ['liniowe', 'otwarte'],
    skills: ['rownania-liniowe'],
    hints: ['Opuszczając nawias po znaku minus, zmień znaki wszystkich wyrazów.', 'Po uporządkowaniu: $-2x - 7 = 5 + 2x$.'],
    solution: '$4(x-1) - 3(2x+1) = 4x - 4 - 6x - 3 = -2x - 7$. Zatem $-2x - 7 = 5 + 2x$, czyli $-4x = 12$ i $x = -3$. Sprawdzenie: lewa strona $4 \\cdot (-4) - 3 \\cdot (-5) = -16 + 15 = -1$, prawa $5 + 2 \\cdot (-3) = -1$.',
    steps: ['Opuść nawiasy i zredukuj: $-2x - 7 = 5 + 2x$.', 'Przenieś wyrazy: $-4x = 12$.', '$x = -3$ i sprawdzenie podstawieniem.'],
    rubric: [
      { criterion: 'Poprawne opuszczenie nawiasów i redukcja wyrażeń podobnych', points: 1 },
      { criterion: 'Przeniesienie wyrazów i wyznaczenie $x = -3$', points: 1 },
      { criterion: 'Sprawdzenie rozwiązania podstawieniem', points: 1 },
    ],
  },
  {
    id: 'ro-07',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-liniowe',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Zbiorem rozwiązań nierówności $-3x \\geq 12$ jest przedział:',
    options: ['$(-\\infty, -4]$', '$[-4, \\infty)$', '$(-\\infty, 4]$', '$[4, \\infty)$'],
    answer: '$(-\\infty, -4]$',
    tags: ['nierownosci', 'przedzialy'],
    skills: ['rownania-nierownosci-liniowe'],
    hints: ['Podziel obie strony przez $-3$.', 'Przy dzieleniu przez liczbę ujemną znak nierówności się odwraca.'],
    solution: '$-3x \\geq 12$, więc $x \\leq -4$. Zbiór rozwiązań to $(-\\infty, -4]$.',
    steps: ['Podziel przez $-3$ i odwróć znak: $x \\leq -4$.', 'Zapisz przedział: $(-\\infty, -4]$.'],
  },
  {
    id: 'ro-08',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-uklady',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Dany jest układ $\\begin{cases} x + y = 7 \\\\ x - y = 3 \\end{cases}$. Podaj wartość $x$.',
    answer: '5',
    acceptedAnswers: ['5', '5,0'],
    tags: ['uklady', 'przeciwne-wspolczynniki'],
    skills: ['rownania-uklady'],
    hints: ['Dodaj równania stronami — $y$ się zredukuje.', '$2x = 10$'],
    solution: 'Dodajemy równania stronami: $2x = 10$, więc $x = 5$. Wtedy $y = 7 - 5 = 2$.',
    steps: ['Dodaj równania: $2x = 10$.', '$x = 5$.', 'Sprawdź: $5 + 2 = 7$ i $5 - 2 = 3$.'],
  },
  {
    id: 'ro-09',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-uklady',
    type: 'numeric',
    difficulty: 2,
    points: 1,
    prompt: 'Dany jest układ $\\begin{cases} 2x + y = 8 \\\\ x - y = 1 \\end{cases}$. Podaj wartość $y$.',
    answer: '2',
    acceptedAnswers: ['2', '2,0'],
    tags: ['uklady'],
    skills: ['rownania-uklady'],
    hints: ['Dodaj równania stronami.', '$3x = 9$, a potem wróć do drugiego równania.'],
    solution: 'Dodajemy stronami: $3x = 9$, więc $x = 3$. Z drugiego równania $y = x - 1 = 2$.',
    steps: ['Dodaj równania: $3x = 9$.', '$x = 3$.', '$y = 3 - 1 = 2$.'],
  },
  {
    id: 'ro-10',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-uklady',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'Dany jest układ $\\begin{cases} 3x - 2y = 4 \\\\ x + y = 3 \\end{cases}$. Oblicz $x^{2} + y^{2}$.',
    answer: '5',
    acceptedAnswers: ['5', '5,0'],
    tags: ['uklady', 'podstawianie'],
    skills: ['rownania-uklady'],
    hints: ['Z drugiego równania wyznacz $x = 3 - y$.', 'Podstaw do pierwszego: $3(3-y) - 2y = 4$.'],
    solution: 'Z drugiego równania $x = 3 - y$. Podstawiamy: $3(3-y) - 2y = 4$, czyli $9 - 5y = 4$ i $y = 1$. Wtedy $x = 2$. Stąd $x^{2} + y^{2} = 4 + 1 = 5$.',
    steps: ['Wyznacz $x = 3 - y$.', 'Podstaw i wyznacz $y = 1$, potem $x = 2$.', 'Oblicz $x^{2} + y^{2} = 5$.'],
  },
  {
    id: 'ro-11',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-uklady',
    type: 'single_choice',
    difficulty: 2,
    points: 1,
    prompt: 'Dany jest układ $\\begin{cases} 2x + y = 4 \\\\ 4x + 2y = 9 \\end{cases}$. Ten układ jest:',
    options: ['sprzeczny — nie ma rozwiązań', 'oznaczony — ma dokładnie jedno rozwiązanie', 'nieoznaczony — ma nieskończenie wiele rozwiązań', 'nieoznaczony tylko dla $x = 0$'],
    answer: 'sprzeczny — nie ma rozwiązań',
    tags: ['uklady', 'liczba-rozwiazan'],
    skills: ['rownania-uklady'],
    hints: ['Pomnóż pierwsze równanie przez $2$.', 'Porównaj wynik z drugim równaniem.'],
    solution: 'Po pomnożeniu pierwszego równania przez $2$ otrzymujemy $4x + 2y = 8$, a drugie równanie mówi $4x + 2y = 9$. To sprzeczność, więc układ nie ma rozwiązań.',
    steps: ['Pomnóż pierwsze równanie przez $2$: $4x + 2y = 8$.', 'Porównaj z $4x + 2y = 9$.', '$8 \\neq 9$, więc układ jest sprzeczny.'],
  },
  {
    id: 'ro-12',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-uklady',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'Sprzedano $200$ biletów: normalne po $12$ zł i ulgowe po $8$ zł, za łącznie $2200$ zł. Ile sprzedano biletów ulgowych?',
    answer: '50',
    acceptedAnswers: ['50', '50,0'],
    tags: ['tekstowe', 'uklady'],
    skills: ['rownania-zadania-tekstowe'],
    hints: ['Oznacz liczbę biletów normalnych przez $n$, ulgowych przez $u$.', 'Ułóż dwa równania: $n + u = 200$ oraz $12n + 8u = 2200$.'],
    solution: 'Mamy $n + u = 200$ i $12n + 8u = 2200$. Podstawiamy $n = 200 - u$: $12(200-u) + 8u = 2200$, czyli $2400 - 4u = 2200$ i $u = 50$. Sprawdzenie: $150 \\cdot 12 + 50 \\cdot 8 = 2200$.',
    steps: ['Oznacz niewiadome i zapisz układ równań.', 'Podstaw $n = 200 - u$.', 'Wyznacz $u = 50$ i sprawdź w treści zadania.'],
  },
  {
    id: 'ro-13',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-uklady',
    type: 'open',
    difficulty: 3,
    points: 3,
    prompt: 'Suma dwóch liczb wynosi $36$, a ich różnica $12$. Wyznacz te liczby i oblicz ich iloczyn.',
    answer: '288',
    acceptedAnswers: ['288', '288,0'],
    tags: ['tekstowe', 'uklady', 'otwarte'],
    skills: ['rownania-zadania-tekstowe'],
    hints: ['Zapisz układ: $a + b = 36$ i $a - b = 12$.', 'Dodając równania stronami, otrzymasz $2a = 48$.'],
    solution: 'Z układu $a + b = 36$, $a - b = 12$ po dodaniu stronami mamy $2a = 48$, czyli $a = 24$ i $b = 12$. Iloczyn wynosi $24 \\cdot 12 = 288$.',
    steps: ['Ułóż układ równań.', 'Wyznacz $a = 24$ i $b = 12$.', 'Oblicz iloczyn: $288$.'],
    rubric: [
      { criterion: 'Zapisanie układu równań opisującego warunki zadania', points: 1 },
      { criterion: 'Wyznaczenie obu liczb: $24$ i $12$', points: 1 },
      { criterion: 'Obliczenie iloczynu: $288$', points: 1 },
    ],
  },
  {
    id: 'ro-14',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-uklady',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'Dany jest układ $\\begin{cases} \\frac{1}{2}x + y = 4 \\\\ x - y = 2 \\end{cases}$. Oblicz iloczyn $x \\cdot y$.',
    answer: '8',
    acceptedAnswers: ['8', '8,0'],
    tags: ['uklady', 'podstawianie', 'ulamki'],
    skills: ['rownania-uklady'],
    hints: ['Z drugiego równania $x = y + 2$.', 'Podstaw do pierwszego i pomnóż obie strony przez $2$.'],solution: 'Z drugiego równania $x = y + 2$. Podstawiamy: $\\frac{1}{2}(y+2) + y = 4$. Mnożymy przez $2$: $(y+2) + 2y = 8$, czyli $3y = 6$ i $y = 2$. Wtedy $x = 4$. Iloczyn $x \\cdot y = 8$.', steps: ['Wyznacz $x = y + 2$.', 'Rozwiąż $3y = 6$, więc $y = 2$ i $x = 4$.', 'Oblicz iloczyn: $8$.'], rubric: [{ criterion: 'Wyznaczenie zależności $x=y+2$', points: 1 }, { criterion: 'Rozwiązanie układu', points: 1 }],
  },
  {
    id: 'ro-15',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-matura',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'Rozwiąż równanie $\\frac{x+1}{x-2} = 3$.',
    answer: '3,5',
    acceptedAnswers: ['3,5', '3.5', '7/2', '3 1/2'],
    tags: ['wymierne', 'zalozenia'],
    skills: ['rownania-wymierne'],
    hints: ['Zapisz najpierw założenie: mianownik nie może być zerem.', 'Pomnóż obie strony przez $x-2$.'],
    solution: 'Założenie: $x \\neq 2$. Mnożymy obie strony przez $x-2$: $x + 1 = 3x - 6$, czyli $-2x = -7$ i $x = 3{,}5$. Założenie jest spełnione.',
    steps: ['Założenie $x \\neq 2$.', 'Pomnóż przez mianownik: $x + 1 = 3x - 6$.', '$x = 3{,}5$ — zgodne z założeniem.'],
  },
  {
    id: 'ro-16',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-matura',
    type: 'single_choice',
    difficulty: 3,
    points: 1,
    prompt: 'Równanie $\\frac{x^{2}-4}{x-2} = 0$:',
    options: ['ma dokładnie jedno rozwiązanie: $x = -2$', 'ma dwa rozwiązania: $x = 2$ i $x = -2$', 'nie ma rozwiązań', 'ma nieskończenie wiele rozwiązań'],
    answer: 'ma dokładnie jedno rozwiązanie: $x = -2$',
    tags: ['wymierne', 'zalozenia'],
    skills: ['rownania-wymierne'],
    hints: ['Zapisz założenie $x \\neq 2$.', 'Rozłóż licznik: $x^{2} - 4 = (x-2)(x+2)$.'],solution: 'Założenie: $x \\neq 2$. Licznik zeruje się dla $x = 2$ oraz $x = -2$, ale $x = 2$ odrzucamy przez założenie. Zostaje jedno rozwiązanie: $x = -2$.',    steps: ['Założenie $x \\neq 2$.', '$x^{2} - 4 = 0$ daje $x = 2$ lub $x = -2$.', 'Odrzucamy $x = 2$ — zostaje $x = -2$.'],
  },
  {
    id: 'ro-17',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-matura',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'Rozwiąż równanie $|x-3| = 7$. Podaj sumę jego rozwiązań.',
    answer: '6',
    acceptedAnswers: ['6', '6,0'],
    tags: ['modul', 'rownania'],
    skills: ['rownania-z-modulem'],
    hints: ['Rozważ dwa przypadki: $x - 3 = 7$ oraz $x - 3 = -7$.', 'Rozwiązaniami są $x = 10$ i $x = -4$.'],solution: 'Z $x - 3 = 7$ mamy $x = 10$; z $x - 3 = -7$ mamy $x = -4$. Suma rozwiązań: $10 + (-4) = 6$.', steps: ['Rozbij moduł na dwa przypadki.', 'Otrzymaj $x = 10$ i $x = -4$.', 'Suma: $6$.'], rubric: [{ criterion: 'Rozbijcie modułu', points: 1 }, { criterion: 'Obliczenie rozwiązań i sumy', points: 1 }],
  },
  {
    id: 'ro-18',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-matura',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'Rozwiąż równanie $|2x+1| = 5$. Podaj większe z rozwiązań.',
    answer: '2',
    acceptedAnswers: ['2', '2,0'],
    tags: ['modul', 'rownania'],
    skills: ['rownania-z-modulem'],
    hints: ['Dwa przypadki: $2x + 1 = 5$ i $2x + 1 = -5$.', 'Otrzymasz $x = 2$ oraz $x = -3$.'],
    solution: 'Z $2x + 1 = 5$ mamy $x = 2$; z $2x + 1 = -5$ mamy $x = -3$. Większym rozwiązaniem jest $2$.',
    steps: ['Rozbij moduł na dwa równania.', 'Wyznacz $x = 2$ i $x = -3$.', 'Większe rozwiązanie to $2$.'],
  },
  {
    id: 'ro-19',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-matura',
    type: 'single_choice',
    difficulty: 3,
    points: 1,
    prompt: 'Zbiorem rozwiązań nierówności $(x-1)(x-3) > 0$ jest:',
    options: ['$(-\\infty, 1) \\cup (3, \\infty)$', '$(1, 3)$', '$(-\\infty, 1] \\cup [3, \\infty)$', '$(-\\infty, 3) \\cup (3, \\infty)$'],
    answer: '$(-\\infty, 1) \\cup (3, \\infty)$',
    tags: ['wielomianowe', 'nierownosci', 'siatka-znakow'],
    skills: ['rownania-nierownosci-wielomianowe'],
    hints: ['Wyznacz miejsca zerowe: $x = 1$ i $x = 3$.', 'Określ znak iloczynu w każdym z trzech przedziałów.'],
    solution: 'Miejsca zerowe to $1$ i $3$. Dla $x < 1$ oba czynniki są ujemne, więc iloczyn jest dodatni; dla $1 < x < 3$ iloczyn jest ujemny; dla $x > 3$ dodatni. Nierówność jest ostra, więc końce przedziałów nie należą do zbioru rozwiązań: $(-\\infty, 1) \\cup (3, \\infty)$.',
    steps: ['Miejsca zerowe: $1$ i $3$.', 'Ustal znaki w przedziałach.', 'Wybierz przedziały z iloczynem dodatnim.'],
  },
  {
    id: 'ro-20',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-matura',
    type: 'numeric',
    difficulty: 4,
    points: 2,
    prompt: 'Ile liczb całkowitych spełnia nierówność $(x+2)(x-1)(x-4) \\leq 0$?',
    answer: '5',
    acceptedAnswers: ['5'],
    tags: ['wielomianowe', 'nierownosci', 'liczby-calkowite'],
    skills: ['rownania-nierownosci-wielomianowe'],
    hints: ['Miejsca zerowe to $-2$, $1$ i $4$.', 'Nierówność jest nieostra, więc miejsca zerowe też wchodzą do zbioru rozwiązań.'],
    solution: 'Miejsca zerowe: $-2$, $1$, $4$. Znak wyrażenia: ujemny dla $x < -2$, dodatni dla $-2 < x < 1$, ujemny dla $1 < x < 4$, dodatni dla $x > 4$. Z nierównością $\\leq 0$ zbiór rozwiązań to $[-2, 1] \\cup \\{4\\}$. Liczby całkowite: $-2, -1, 0, 1$ oraz $4$ — razem $5$.',
    steps: ['Wyznacz miejsca zerowe i znaki w przedziałach.', 'Zapisz zbiór rozwiązań: $[-2, 1] \\cup \\{4\\}$.', 'Policz liczby całkowite: $5$.'],
  },
  {
    id: 'ro-21',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-matura',
    type: 'proof',
    difficulty: 4,
    points: 3,
    prompt: 'Wykaż, że równanie $\\frac{x-1}{x+2} = 1$ nie ma rozwiązań.',
    answer: 'Równanie jest sprzeczne: dla $x \\neq -2$ otrzymujemy $-1 = 2$.',
    tags: ['wymierne', 'dowod'],
    skills: ['rownania-wymierne'],
    hints: ['Zapisz założenie dotyczące mianownika.', 'Pomnóż obie strony przez $x+2$ i sprawdź, co zostaje.'],
    solution: 'Założenie: $x \\neq -2$. Mnożymy obie strony przez $x + 2$: $x - 1 = x + 2$, czyli $-1 = 2$ — sprzeczność. Żadna liczba spełniająca założenie nie jest rozwiązaniem, więc równanie nie ma rozwiązań.',
    steps: ['Zapisz założenie $x \\neq -2$.', 'Pomnóż przez mianownik: $x - 1 = x + 2$.', 'Wskaż sprzeczność $-1 = 2$ i sformułuj wniosek.'],
    rubric: [
      { criterion: 'Zapisanie założenia $x \\neq -2$', points: 1 },
      { criterion: 'Przekształcenie równania do postaci $-1 = 2$', points: 1 },
      { criterion: 'Sformułowanie wniosku o braku rozwiązań', points: 1 },
    ],
  },
  {
    id: 'ro-22',
    topicSlug: 'rownania',
    lessonSlug: 'rownania-matura',
    type: 'open',
    difficulty: 4,
    points: 4,
    prompt: 'Rozwiąż nierówność $(x+3)(x-2) \\geq 0$. Zapisz zbiór rozwiązań przedziałem.',
    answer: '$(-\\infty, -3] \\cup [2, \\infty)$',
    tags: ['wielomianowe', 'nierownosci', 'otwarte'],
    skills: ['rownania-nierownosci-wielomianowe'],
    hints: ['Wyznacz miejsca zerowe obu czynników.', 'Nierówność jest nieostra, więc miejsca zerowe należą do zbioru rozwiązań.'],
    solution: 'Miejsca zerowe: $x = -3$ i $x = 2$. Dla $x < -3$ oba czynniki są ujemne, więc iloczyn jest dodatni; dla $-3 < x < 2$ iloczyn jest ujemny; dla $x > 2$ dodatni. Z nierównością $\\geq 0$ zbiorem rozwiązań jest $(-\\infty, -3] \\cup [2, \\infty)$.',
    steps: ['Miejsca zerowe: $-3$ i $2$.', 'Ustal znak iloczynu w trzech przedziałach.', 'Wybierz przedziały z iloczynem nieujemnym i domknij końce.', 'Zapisz odpowiedź: $(-\\infty, -3] \\cup [2, \\infty)$.'],
    rubric: [
      { criterion: 'Wyznaczenie miejsc zerowych: $-3$ i $2$', points: 1 },
      { criterion: 'Poprawne ustalenie znaku iloczynu w przedziałach', points: 1 },
      { criterion: 'Wybór przedziałów zgodnych z nierównością', points: 1 },
      { criterion: 'Poprawny zapis zbioru rozwiązań przedziałami', points: 1 },
    ],
  },
]
