import type { ContentTask } from '@/content/types'

export const statystykaTasks: ContentTask[] = [
  { id: 'st-01', topicSlug: 'statystyka', lessonSlug: 'statystyka-miary-centralne', type: 'numeric', difficulty: 1, points: 1, prompt: 'Oblicz średnią arytmetyczną liczb $2, 4, 6, 8$.', answer: '5', acceptedAnswers: ['5', '5,0'], tags: ['srednia'], skills: ['statystyka-srednia'], hints: ['Zsumuj cztery liczby.', 'Podziel sumę przez 4.'], solution: '$\\bar{x} = \\frac{2+4+6+8}{4} = 5$.', steps: ['Suma wynosi $20$.', 'Liczba danych to $4$.', 'Średnia wynosi $5$.'] },
  { id: 'st-02', topicSlug: 'statystyka', lessonSlug: 'statystyka-miary-centralne', type: 'numeric', difficulty: 1, points: 1, prompt: 'Wyznacz medianę zestawu $3, 7, 2, 9, 4$.', answer: '4', acceptedAnswers: ['4'], tags: ['mediana'], skills: ['statystyka-mediana'], hints: ['Uporządkuj dane rosnąco.', 'Weź trzeci element pięcioelementowego zestawu.'], solution: 'Po uporządkowaniu: $2, 3, 4, 7, 9$. Medianą jest środkowy element $4$.', steps: ['Uporządkuj dane.', 'Zidentyfikuj element środkowy.', 'Mediana to $4$.'] },
  { id: 'st-03', topicSlug: 'statystyka', lessonSlug: 'statystyka-miary-centralne', type: 'single_choice', difficulty: 1, points: 1, prompt: 'Jaka jest dominanta danych $1, 4, 4, 7, 9$?', options: ['$1$', '$4$', '$7$', '$9$'], answer: '$4$', tags: ['dominanta'], skills: ['statystyka-mediana'], hints: ['Dominanta to wartość najczęściej występująca.', 'Policz powtórzenia.'], solution: 'Liczba $4$ występuje dwa razy, a pozostałe po jednym, więc dominantą jest $4$.', steps: ['Policz wystąpienia wartości.', '$4$ pojawia się najczęściej.', 'Dominanta to $4$.'] },
  { id: 'st-04', topicSlug: 'statystyka', lessonSlug: 'statystyka-miary-centralne', type: 'numeric', difficulty: 2, points: 1, prompt: 'Wartości $2$ i $8$ mają wagi odpowiednio $3$ i $2$. Oblicz średnią ważoną.', answer: '22/5', acceptedAnswers: ['22/5', '4,4', '4.4'], tags: ['srednia-wazona'], skills: ['statystyka-srednia'], hints: ['Zmnoż każdą wartość przez jej wagę.', 'Dodaj iloczyny i podziel przez sumę wag.'], solution: '$\\frac{2\\cdot3+8\\cdot2}{3+2} = \\frac{22}{5} = 4{,}4$.', steps: ['Oblicz iloczyny: $6$ i $16$.', 'Suma wag to $5$.', 'Wynik to $\\frac{22}{5}=4{,}4$.'] },
  { id: 'st-05', topicSlug: 'statystyka', lessonSlug: 'statystyka-zmiennosc', type: 'numeric', difficulty: 2, points: 1, prompt: 'Oblicz rozstęp danych $12, 7, 19, 4$.', answer: '15', acceptedAnswers: ['15'], tags: ['rozstep'], skills: ['statystyka-zmiennosc'], hints: ['Znajdź wartość największą i najmniejszą.', 'Odejmij mniejszą od większej.'], solution: '$R = 19 - 4 = 15$.', steps: ['Maksimum to $19$.', 'Minimum to $4$.', 'Rozstęp wynosi $15$.'] },
  { id: 'st-06', topicSlug: 'statystyka', lessonSlug: 'statystyka-zmiennosc', type: 'single_choice', difficulty: 2, points: 1, prompt: 'Dwa zestawy danych mają tę samą średnią. Który jest bardziej rozproszony, jeśli ma większe odchylenie standardowe?', options: ['zestaw o mniejszym odchyleniu', 'zestaw o większym odchyleniu', 'nie można tego określić', 'oba zawsze mają taki sam rozstęp'], answer: 'zestaw o większym odchyleniu', tags: ['odchylenie'], skills: ['statystyka-zmiennosc'], hints: ['Odchylenie standardowe mierzy odległość typowych danych od średniej.', 'Większa wartość oznacza większe rozproszenie.'], solution: 'Większe odchylenie standardowe oznacza większe rozproszenie danych wokół średniej.', steps: ['Porównaj wartości odchyleń.', 'Większe odchylenie oznacza większe rozproszenie.', 'Wybierz odpowiedź z największym odchyleniem.'] },
  { id: 'st-07', topicSlug: 'statystyka', lessonSlug: 'statystyka-zmiennosc', type: 'numeric', difficulty: 3, points: 2, prompt: 'Dla danych $2, 4, 6$ oblicz wariancję z dzielnikiem $n$.', answer: '8/3', acceptedAnswers: ['8/3', '2,67'], tags: ['wariancja'], skills: ['statystyka-zmiennosc'], hints: ['Najpierw oblicz średnią: $4$.', 'Odejmij $4$ od każdej wartości, podnieś do kwadratu i uśrednij.'], solution: 'Średnia to $4$. Kwadraty odchyleń to $4, 0, 4$, więc $s^2 = \\frac{8}{3}$.', steps: ['Wyznacz średnią $4$.', 'Oblicz odchylenia $-2, 0, 2$ i ich kwadraty.', 'Uśrednij: $\\frac{4+0+4}{3} = \\frac{8}{3}$.'] },
  { id: 'st-08', topicSlug: 'statystyka', lessonSlug: 'statystyka-miary-centralne', type: 'open', difficulty: 3, points: 3, prompt: 'W klasie jest 12 uczniów, a suma ich ocen wynosi $42$. Oblicz średnią arytmetyczną tych ocen i wyjaśnij, dlaczego dzielimy przez liczbę uczniów.', answer: '42/12=3,5', acceptedAnswers: ['42/12=3,5', '3,5'], tags: ['srednia'], skills: ['statystyka-srednia'], hints: ['Porównaj sumę ocen z iloczynem $3{,}5\\cdot12$.', 'Podaj poprawne obliczenie.'], solution: 'Poprawnie: $\\frac{42}{12} = 3{,}5$. Dzielimy sumę ocen przez liczbę uczniów, aby otrzymać jedną wartość reprezentującą całą grupę.', steps: ['Zapisz wzór na średnią.', 'Oblicz $\\frac{42}{12}$.', ' Wynik: $3{,}5$.'], rubric: [{ criterion: 'Zastosowanie wzoru średniej arytmetycznej', points: 1 }, { criterion: 'Poprawne obliczenie $42/12$', points: 1 }, { criterion: 'Wyjaśnienie roli mianownika', points: 1 }] },
  { id: 'st-09', topicSlug: 'statystyka', lessonSlug: 'statystyka-miary-centralne', type: 'open', difficulty: 3, points: 3, prompt: 'Podaj medianę i dominantę danych $4, 4, 6, 7, 7, 10$.', answer: 'mediana 6,5; dominanta nie istnieje', acceptedAnswers: ['6,5; brak dominanty', '6,5; brak'], tags: ['mediana', 'dominanta'], skills: ['statystyka-mediana'], hints: ['Dane są już uporządkowane.', 'Przy sześciu danych licz średnią trzeciego i czwartego elementu.'], solution: 'Mediana to $\\frac{6+7}{2}=6{,}5$. Wartości $4$ i $7$ występują po dwa razy, więc nie ma jednej dominanty.', steps: ['Zidentyfikuj elementy środkowe: $6$ i $7$.', 'Oblicz medianę: $6{,}5$.', 'Sprawdź powtórzenia i stwierdź brak dominanty.'], rubric: [{ criterion: 'Poprawne wyznaczenie elementów środkowych', points: 1 }, { criterion: 'Obliczenie mediany $6{,}5$', points: 1 }, { criterion: 'Wniosek o braku dominanty', points: 1 }] },
  { id: 'st-10', topicSlug: 'statystyka', lessonSlug: 'statystyka-zmiennosc', type: 'open', difficulty: 4, points: 4, prompt: 'Dwa zawodnicy zdobyli w czterech startach odpowiednio $8$ i $10$ punktów. Wyniki jednego to $7, 8, 8, 9$, a drugiego to $6, 6, 12, 16$. Który zawodnik ma większe odchylenie standardowe? Uzasadnij bez pełnego liczenia pierwiastka.', answer: 'drugi', acceptedAnswers: ['drugi zawodnik', 'zawodnik drugi'], tags: ['odchylenie', 'porownanie'], skills: ['statystyka-zmiennosc'], hints: ['Oblicz średnie obu zestawów: $8$ i $10$.', 'Porównaj sumy kwadratów odchyleń od średniej.'], solution: 'Średnie wynoszą odpowiednio $8$ i $10$. Suma kwadratów odchyleń pierwszego zestawu to $1+0+0+1=2$, a drugiego to $16+16+4+36=72$. Przy tej samej liczbie obserwacji drugi zestaw ma większą wariancję, a więc większe odchylenie standardowe.', steps: ['Oblicz średnie.', 'Oblicz sumy kwadratów odchyleń.', 'Porównaj: $72>2$, więc drugi zawodnik.'], rubric: [{ criterion: 'Obliczenie średnich', points: 1 }, { criterion: 'Porównanie rozproszenia', points: 2 }, { criterion: 'Poprawny wniosek', points: 1 }] },
]
