import type { ContentTask } from '@/content/types'

/**
 * Bank zadań do działu „Stereometria”. Kody `sr-*` są stabilnym kluczem importu.
 */
export const stereometriaTasks: ContentTask[] = [
  {
    id: 'sr-01',
    topicSlug: 'stereometria',
    lessonSlug: 'stereometria-objetosci',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'Podstawą graniastosłupa jest kwadrat o boku $5$ cm, a wysokość ma długość $8$ cm. Oblicz objętość tego graniastosłupa.',
    answer: '200',
    acceptedAnswers: ['200'],
    tags: ['objetosc', 'graniastoslup'],
    skills: ['stereometria-objetosci'],
    hints: ['Oblicz pole podstawy: to kwadrat o boku $5$.', 'Zastosuj $V = P_{p} \\cdot h$.'],
    solution: '$P_{p} = 5^{2} = 25$ cm², więc $V = 25 \\cdot 8 = 200$ cm³.',
    steps: ['Pole podstawy: $P_{p} = 5^{2} = 25$ cm².', 'Wysokość: $h = 8$ cm.', 'Objętość: $V = 25 \\cdot 8 = 200$ cm³.'],
  },
  {
    id: 'sr-02',
    topicSlug: 'stereometria',
    lessonSlug: 'stereometria-objetosci',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Ostrosłup ma podstawę w postaci trójkąta o polu $24$ cm² i wysokość $9$ cm. Oblicz jego objętość.',
    answer: '72',
    acceptedAnswers: ['72'],
    tags: ['objetosc', 'ostroslup'],
    skills: ['stereometria-objetosci'],
    hints: ['Ostrosłup ma objętość trzykrotnie mniejszą od graniastosłupa o tej samej podstawie i wysokości.', 'Zastosuj $V = \\frac{1}{3} P_{p} h$.'],
    solution: '$V = \\frac{1}{3} \\cdot 24 \\cdot 9 = 72$ cm³.',
    steps: ['Zastosuj wzór na ostrosłup z czynnikiem $\\frac{1}{3}$.', 'Podstaw: $V = \\frac{1}{3} \\cdot 24 \\cdot 9$.', 'Oblicz $72$ cm³.'],
  },
  {
    id: 'sr-03',
    topicSlug: 'stereometria',
    lessonSlug: 'stereometria-objetosci',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Walec ma promień podstawy $3$ cm i wysokość $10$ cm. Oblicz jego objętość. Wynik podaj w postaci $\\pi \\cdot$ liczby.',
    answer: '90π',
    acceptedAnswers: ['90π', '90\\pi', '90*π', '282,74', '282.74'],
    tags: ['objetosc', 'walec'],
    skills: ['stereometria-objetosci'],
    hints: ['Zastosuj $V = \\pi r^{2} h$.', 'Policz $r^{2} = 9$ i pomnóż przez wysokość $10$.'],
    solution: '$V = \\pi \\cdot 3^{2} \\cdot 10 = 90\\pi$ cm³.',
    steps: ['Zapisz wzór: $V = \\pi r^{2} h$.', 'Podstaw: $V = \\pi \\cdot 9 \\cdot 10$.', 'Wynik: $90\\pi$ cm³.'],
  },
  {
    id: 'sr-04',
    topicSlug: 'stereometria',
    lessonSlug: 'stereometria-objetosci',
    type: 'single_choice',
    difficulty: 3,
    points: 2,
    prompt: 'Ile wynosi pole powierzchni całkowitej stożka o promieniu podstawy $3$ cm i tworzącej $5$ cm?',
    options: ['$24\\pi$ cm²', '$18\\pi$ cm²', '$30\\pi$ cm²', '$15\\pi$ cm²'],
    answer: '$24\\pi$ cm²',
    tags: ['pole-powierzchni', 'stozek'],
    skills: ['stereometria-pola-bryly'],
    hints: ['Najpierw wyznacz wysokość stożka z twierdzenia Pitagorasa.', 'Pole całkowite stożka to pole podstawy plus pole powierzchni bocznej.'],
    solution: 'Wysokość: $h = \\sqrt{5^{2} - 3^{2}} = \\sqrt{16} = 4$ cm. Pole podstawy: $\\pi \\cdot 3^{2} = 9\\pi$. Pole boczne: $\\pi \\cdot 3 \\cdot 4 = 12\\pi$. Suma: $9\\pi + 12\\pi = 24\\pi$ cm².',
    steps: ['Wyznacz wysokość: $h = \\sqrt{5^{2} - 3^{2}} = 4$.', 'Pole podstawy: $9\\pi$.', 'Pole boczne: $\\pi r l = \\pi \\cdot 3 \\cdot 4 = 12\\pi$.', 'Suma: $24\\pi$ cm².'],
  },
  {
    id: 'sr-05',
    topicSlug: 'stereometria',
    lessonSlug: 'stereometria-objetosci',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Kula ma promień $6$ cm. Oblicz jej objętość. Wynik podaj w postaci $\\pi \\cdot$ liczby.',
    answer: '288π',
    acceptedAnswers: ['288π', '288\\pi', '288*π'],
    tags: ['objetosc', 'kula'],
    skills: ['stereometria-objetosci'],
    hints: ['Zastosuj $V = \\frac{4}{3} \\pi r^{3}$.', 'Policz $r^{3} = 216$.'],
    solution: '$V = \\frac{4}{3} \\cdot \\pi \\cdot 6^{3} = \\frac{4}{3} \\cdot \\pi \\cdot 216 = 288\\pi$ cm³.',
    steps: ['Policz $6^{3} = 216$.', 'Zastosuj: $V = \\frac{4}{3} \\cdot \\pi \\cdot 216$.', 'Wynik: $288\\pi$ cm³.'],
  },
  {
    id: 'sr-06',
    topicSlug: 'stereometria',
    lessonSlug: 'stereometria-katy-odleglosci',
    type: 'open',
    difficulty: 4,
    points: 4,
    prompt: 'Ostrosłup prawidłowy czworokątny ma wszystkie krawędzie boczne długości $13$ cm, a podstawę będącą kwadratem o boku $10$ cm. Oblicz wysokość tego ostrosłupa.',
    answer: '√119',
    acceptedAnswers: ['√119', 'sqrt(119)', '≈10,91', '10.91'],
    tags: ['wysokosc', 'ostroslup', 'katy'],
    skills: ['stereometria-katy', 'stereometria-przekroje'],
    hints: ['Wysokość przechodzi przez środek podstawy — zrób przekrój osiowy.', 'Odległość od środka kwadratu do jego wierzchołka to połowa przekątnej: $\\frac{10\\sqrt{2}}{2}$.'],
    solution: 'Przekrój osiowy daje trójkąt prostokątny, którego hipotenuzą jest krawędź boczna $13$ cm, a przeciwprostokątną — odległość od środka podstawy do wierzchołka kwadratu, czyli połowa przekątnej: $d = \\frac{10\\sqrt{2}}{2} = 5\\sqrt{2}$. Z twierdzenia Pitagorasa: $h = \\sqrt{13^{2} - (5\\sqrt{2})^{2}} = \\sqrt{169 - 50} = \\sqrt{119}$ cm.',
    steps: ['Narysuj przekrój osiowy: wysokość $h$ i krawędź boczna $13$ tworzą trójkąt prostokątny.', 'Oblicz połowę przekątnej podstawy: $d = \\frac{10\\sqrt{2}}{2} = 5\\sqrt{2}$.', 'Zastosuj Pitagorasa: $h = \\sqrt{169 - 50} = \\sqrt{119}$ cm.'],
    rubric: [
      { criterion: 'Rozpoznanie przekroju osiowego i trójkąta prostokątnego', points: 1 },
      { criterion: 'Obliczenie odległości od środka podstawy do wierzchołka', points: 1 },
      { criterion: 'Zastosowanie twierdzenia Pitagorasa', points: 1 },
      { criterion: 'Wynik $\\sqrt{119}$ cm', points: 1 },
    ],
  },
  {
    id: 'sr-07',
    topicSlug: 'stereometria',
    lessonSlug: 'stereometria-katy-odleglosci',
    type: 'numeric',
    level: 'extended',
    difficulty: 4,
    points: 3,
    prompt: 'W stożku o tworzącej $10$ cm i promieniu podstawy $6$ cm wyznacz kąt nachylenia tworzącej do podstawy. Wynik podaj w stopniach, zaokrąglając do całości.',
    answer: '37',
    acceptedAnswers: ['37', '37°', '36,87', '36.87'],
    tags: ['katy', 'stozek'],
    skills: ['stereometria-katy'],
    hints: ['Zrób przekrój osiowy stożka — otrzymasz trójkąt prostokątny.', 'Kąt nachylenia tworzącej do podstawy jest przy podstawie tego trójkąta.'],
    solution: 'Przekrój osiowy daje trójkąt prostokątny o przeciwprostokątnej $10$ cm i przyprostokątnej $6$ cm (promień podstawy). Szukany kąt $\\varphi$ leży przy podstawie, więc $\\sin \\varphi = \\frac{6}{10} = 0{,}6$. Stąd $\\varphi \\approx 36{,}87^{\\circ} \\approx 37^{\\circ}$.',
    steps: ['Sporządź przekrój osiowy.', 'Zapisz: $\\sin \\varphi = \\frac{r}{l} = \\frac{6}{10}$.', 'Oblicz: $\\varphi \\approx 37^{\\circ}$.'],
  },
  {
    id: 'sr-08',
    topicSlug: 'stereometria',
    lessonSlug: 'stereometria-katy-odleglosci',
    type: 'single_choice',
    level: 'extended',
    difficulty: 3,
    points: 2,
    prompt: 'Wysokość ostrosłupa prawidłowego czterościennego ma długość $12$ cm, a jego podstawą jest kwadrat o boku $10$ cm. Ile wynosi długość krawędzi bocznej?',
    options: ['$13$ cm', '$12$ cm', '$\\sqrt{194}$ cm', '$14$ cm'],
    answer: '$\\sqrt{194}$ cm',
    tags: ['krawedzie', 'ostroslup', 'katy'],
    skills: ['stereometria-katy', 'stereometria-przekroje'],
    hints: ['Zrób przekrój osiowy i zastosuj twierdzenie Pitagorasa.', 'Odległość od środka podstawy do jej wierzchołka to $\\frac{10\\sqrt{2}}{2} = 5\\sqrt{2}$.'],
    solution: 'Odległość od środka podstawy do wierzchołka: $d = \\frac{10\\sqrt{2}}{2} = 5\\sqrt{2}$, więc $d^{2} = 50$. Krawędź boczna: $l = \\sqrt{12^{2} + 50} = \\sqrt{194} \\approx 13{,}93$ cm.',
    steps: ['Oblicz $d = \\frac{10\\sqrt{2}}{2} = 5\\sqrt{2}$, czyli $d^{2} = 50$.', 'Zastosuj Pitagorasa: $l = \\sqrt{144 + 50} = \\sqrt{194}$.', 'Porównaj z odpowiedziami: $\\sqrt{194} \\approx 13{,}93$ cm.'],
  },
  {
    id: 'sr-09',
    topicSlug: 'stereometria',
    lessonSlug: 'stereometria-katy-odleglosci',
    type: 'open',
    level: 'extended',
    difficulty: 4,
    points: 4,
    prompt: 'Ostrosłup prawidłowy trójkątny ma podstawę będącą trójkątem równobocznym o boku $12$ cm. Wysokość ostrosłupa ma długość $8$ cm. Oblicz objętość tego ostrosłupa.',
    answer: '96√3',
    acceptedAnswers: ['96√3', '96\\sqrt{3}', '≈166,28', '166.28'],
    tags: ['objetosc', 'ostroslup', 'pole-podstawy'],
    skills: ['stereometria-objetosci', 'stereometria-katy'],
    hints: ['Najpierw oblicz pole podstawy — trójkąta równobocznego o boku $12$.', 'Wysokość ostrosłupa to $8$ cm; objętość to $\\frac{1}{3} P_{p} h$.'],
    solution: 'Wysokość trójkąta równobocznego: $\\frac{12\\sqrt{3}}{2} = 6\\sqrt{3}$. Pole podstawy: $P_{p} = \\frac{1}{2} \\cdot 12 \\cdot 6\\sqrt{3} = 36\\sqrt{3}$. Objętość: $V = \\frac{1}{3} \\cdot 36\\sqrt{3} \\cdot 8 = 96\\sqrt{3}$ cm³.',
    steps: ['Oblicz wysokość podstawy: $6\\sqrt{3}$.', 'Oblicz pole podstawy: $P_{p} = 36\\sqrt{3}$.', 'Zastosuj $V = \\frac{1}{3} P_{p} h$.', 'Wynik: $96\\sqrt{3}$ cm³.'],
    rubric: [
      { criterion: 'Obliczenie pola podstawy trójkąta równobocznego', points: 2 },
      { criterion: 'Zastosowanie wzoru na objętość ostrosłupa', points: 1 },
      { criterion: 'Wynik $96\\sqrt{3}$ cm³', points: 1 },
    ],
  },
  {
    id: 'sr-10',
    topicSlug: 'stereometria',
    lessonSlug: 'stereometria-katy-odleglosci',
    type: 'open',
    level: 'extended',
    difficulty: 5,
    points: 5,
    prompt: 'W prostopadłościanie $ABCD A_{1}B_{1}C_{1}D_{1}$ podstawa ma wymiary $6$ cm i $8$ cm, a wysokość $5$ cm. Oblicz pole powierzchni całkowitej tego prostopadłościanu.',
    answer: '236',
    acceptedAnswers: ['236'],
    tags: ['pole-powierzchni', 'prostopadloscian'],
    skills: ['stereometria-pola-bryly'],
    hints: ['Pole całkowite to $2$ razy pole podstawy plus obwód podstawy razy wysokość.', 'Obwód podstawy wynosi $2 \\cdot (6 + 8) = 28$.'],
    solution: 'Podstawa ma wymiary $6 \\times 8$, więc $P_{p} = 48$ cm² i obwód $2 \\cdot (6 + 8) = 28$ cm. Pola ścian bocznych: $28 \\cdot 5 = 140$ cm². Pole całkowite: $2 \\cdot 48 + 140 = 236$ cm².',
    steps: ['Oblicz pole podstawy: $P_{p} = 6 \\cdot 8 = 48$.', 'Oblicz obwód podstawy: $28$.', 'Pola boczne: $28 \\cdot 5 = 140$.', 'Zsumuj: $2 \\cdot 48 + 140 = 236$ cm².'],
    rubric: [
      { criterion: 'Obliczenie pola podstawy i obwodu podstawy', points: 2 },
      { criterion: 'Obliczenie pól ścian bocznych', points: 2 },
      { criterion: 'Wynik $236$ cm²', points: 1 },
    ],
  },
]
