import type { ContentTask } from '@/content/types'

/**
 * Bank zadań do działu „Trygonometria”. Kody `tg-*` są stabilnym kluczem importu.
 */
export const trygonometriaTasks: ContentTask[] = [
  {
    id: 'tg-01',
    topicSlug: 'trygonometria',
    lessonSlug: 'trygonometria-trojkat',
    type: 'numeric',
    difficulty: 1,
    points: 1,
    prompt: 'W trójkącie prostokątnym przyprostokątna leżąca naprzeciw kąta $\\alpha$ ma długość $6$, a przeciwprostokątna długość $10$. Oblicz $\\sin \\alpha$.',
    answer: '3/5',
    acceptedAnswers: ['3/5', '0,6', '0.6'],
    tags: ['definicje', 'trojkat-prostokatny'],
    skills: ['trygonometria-trojkat'],
    hints: ['Sinus kąta ostrego to stosunek przyprostokątnej naprzeciw kąta do przeciwprostokątnej.', 'Podstaw: $\\sin \\alpha = \\frac{6}{10}$ i skróć ułamek.'],
    solution: 'Z definicji: $\\sin \\alpha = \\frac{6}{10} = \\frac{3}{5}$.',
    steps: ['Wskaż bok naprzeciw kąta ($6$) i przeciwprostokątną ($10$).', 'Podstaw do definicji: $\\sin \\alpha = \\frac{6}{10}$.', 'Skróć: $\\frac{3}{5}$.'],
    figure: {
      kind: 'geometry',
      caption: 'Trójkąt prostokątny: bok naprzeciw kąta $\\alpha$ ma długość $6$, przeciwprostokątna — $10$.',
      elements: [
        { type: 'polyline', points: [[0, 0], [8, 0], [0, 6]], closed: true, color: 'violet' },
        { type: 'rightAngle', vertex: [0, 0], dirDeg: 0, size: 0.7 },
        { type: 'namedPoint', id: 'A', at: [8, 0] },
        { type: 'namedPoint', id: 'B', at: [0, 6] },
        { type: 'namedPoint', id: 'C', at: [0, 0] },
        { type: 'angle', vertex: [8, 0], fromDeg: 143, toDeg: 180, r: 1.5, color: 'amber', label: 'α' },
      ],
      labels: { A: 'A', B: 'B', C: 'C' },
    },
  },
  {
    id: 'tg-02',
    topicSlug: 'trygonometria',
    lessonSlug: 'trygonometria-trojkat',
    type: 'single_choice',
    difficulty: 1,
    points: 1,
    prompt: 'W trójkącie prostokątnym przyprostokątna leżąca naprzeciw kąta ostrego $\\alpha$ ma długość $5$, a przyprostokątna przylegająca do niego długość $8$. Wtedy $\\tan \\alpha$ jest równy:',
    options: ['$\\frac{5}{8}$', '$\\frac{8}{5}$', '$\\frac{5}{\\sqrt{89}}$', '$\\frac{8}{\\sqrt{89}}$'],
    answer: '$\\frac{5}{8}$',
    tags: ['definicje', 'zamkniete'],
    skills: ['trygonometria-trojkat'],
    hints: ['Tangens kąta ostrego to stosunek przyprostokątnej naprzeciw do przylegającej.', 'Uważaj: przeciwprostokątna ($\\sqrt{89}$) nie występuje w definicji tangensa.'],
    solution: 'Z definicji tangensa: $\\tan \\alpha = \\frac{\\text{naprzeciw}}{\\text{przy}} = \\frac{5}{8}$. Długość $\\sqrt{89}$ to przeciwprostokątna (z Pitagorasa), która w definicji tangensa nie występuje.',
    steps: ['Wyznacz przeciwprostokątną $\\sqrt{5^{2} + 8^{2}} = \\sqrt{89}$.', 'Zastosuj definicję: $\\tan \\alpha = \\frac{5}{8}$.'],
  },
  {
    id: 'tg-03',
    topicSlug: 'trygonometria',
    lessonSlug: 'trygonometria-trojkat',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Drabina o długości $4$ m opiera się o ścianę pod kątem $60^{\\circ}$ do podłoża. Na jakiej wysokości nad podłożem znajduje się górny koniec drabiny? Wynik podaj w metrach.',
    answer: '2√3',
    acceptedAnswers: ['2√3', '3,46', '3.46'],
    tags: ['definicje', 'zadanie-praktyczne'],
    skills: ['trygonometria-trojkat'],
    hints: ['Drabina to przeciwprostokątna trójkąta prostokątnego.', 'Wysokość leży naprzeciw kąta, więc $h = 4 \\cdot \\sin 60^{\\circ}$.'],
    solution: 'Wysokość leży naprzeciw kąta $60^{\\circ}$, a drabina jest przeciwprostokątną: $h = 4 \\cdot \\sin 60^{\\circ} = 4 \\cdot \\frac{\\sqrt{3}}{2} = 2\\sqrt{3} \\approx 3{,}46$ m.',
    steps: ['Rozpoznaj trójkąt prostokątny: drabina to przeciwprostokątna.', 'Podstaw: $h = 4 \\sin 60^{\\circ}$.', 'Oblicz: $h = 2\\sqrt{3} \\approx 3{,}46$ m.'],
  },
  {
    id: 'tg-04',
    topicSlug: 'trygonometria',
    lessonSlug: 'trygonometria-trojkat',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'W trójkącie prostokątnym przeciwprostokątna ma długość $13$, a $\\sin \\alpha = \\frac{5}{13}$ dla kąta ostrego $\\alpha$. Oblicz $\\tan \\alpha$.',
    answer: '5/12',
    acceptedAnswers: ['5/12'],
    tags: ['definicje', 'pitagoras'],
    skills: ['trygonometria-trojkat'],
    hints: ['Z definicji sinusa wyznacz przyprostokątną naprzeciw kąta.', 'Drugą przyprostokątną policz z twierdzenia Pitagorasa.'],
    solution: 'Przyprostokątna naprzeciw: $13 \\cdot \\frac{5}{13} = 5$. Druga przyprostokątna: $\\sqrt{13^{2} - 5^{2}} = \\sqrt{144} = 12$. Stąd $\\tan \\alpha = \\frac{5}{12}$.',
    steps: ['Wyznacz bok naprzeciw: $a = c \\sin \\alpha = 5$.', 'Pitagoras: $b = \\sqrt{169 - 25} = 12$.', 'Oblicz $\\tan \\alpha = \\frac{5}{12}$.'],
  },
  {
    id: 'tg-05',
    topicSlug: 'trygonometria',
    lessonSlug: 'trygonometria-katy',
    type: 'single_choice',
    difficulty: 1,
    points: 1,
    prompt: 'Wartość $\\cos 60^{\\circ}$ jest równa:',
    options: ['$\\frac{1}{2}$', '$\\frac{\\sqrt{3}}{2}$', '$\\frac{\\sqrt{2}}{2}$', '$\\frac{\\sqrt{3}}{3}$'],
    answer: '$\\frac{1}{2}$',
    tags: ['katy-specjalne', 'zamkniete'],
    skills: ['trygonometria-katy-specjalne'],
    hints: ['Dla $60^{\\circ}$ sinus jest większy od cosinusa.', 'Wspomnij trójkąt o kątach $30^{\\circ}$, $60^{\\circ}$, $90^{\\circ}$ i boku $1$ naprzeciw $30^{\\circ}$.'],
    solution: 'Z tabeli wartości: $\\cos 60^{\\circ} = \\frac{1}{2}$ (a $\\sin 60^{\\circ} = \\frac{\\sqrt{3}}{2}$).',
    steps: ['Przypomnij tabelę wartości dla $30^{\\circ}$, $45^{\\circ}$, $60^{\\circ}$.', 'Odczytaj: $\\cos 60^{\\circ} = \\frac{1}{2}$.'],
  },
  {
    id: 'tg-06',
    topicSlug: 'trygonometria',
    lessonSlug: 'trygonometria-katy',
    type: 'numeric',
    difficulty: 2,
    points: 2,
    prompt: 'Oblicz wartość wyrażenia $2 \\sin 30^{\\circ} + \\tan 45^{\\circ}$.',
    answer: '2',
    acceptedAnswers: ['2', '2,0'],
    tags: ['katy-specjalne', 'wyrazenie'],
    skills: ['trygonometria-katy-specjalne'],
    hints: ['Podstaw znane wartości: $\\sin 30^{\\circ}$ oraz $\\tan 45^{\\circ}$.', '$\\sin 30^{\\circ} = \\frac{1}{2}$ oraz $\\tan 45^{\\circ} = 1$'],
    solution: '$2 \\sin 30^{\\circ} + \\tan 45^{\\circ} = 2 \\cdot \\frac{1}{2} + 1 = 1 + 1 = 2$.',
    steps: ['Podstaw $\\sin 30^{\\circ} = \\frac{1}{2}$.', 'Podstaw $\\tan 45^{\\circ} = 1$.', 'Oblicz: $1 + 1 = 2$.'],
  },
  {
    id: 'tg-07',
    topicSlug: 'trygonometria',
    lessonSlug: 'trygonometria-katy',
    type: 'single_choice',
    difficulty: 3,
    points: 2,
    prompt: 'Kąt $\\alpha$ jest ostry oraz $\\sin \\alpha = \\frac{1}{3}$. Wtedy $\\cos \\alpha$ jest równe:',
    options: ['$\\frac{2\\sqrt{2}}{3}$', '$\\frac{\\sqrt{2}}{3}$', '$\\frac{2\\sqrt{3}}{3}$', '$\\frac{8}{9}$'],
    answer: '$\\frac{2\\sqrt{2}}{3}$',
    tags: ['jedynka-trygonometryczna', 'zamkniete'],
    skills: ['trygonometria-jedynka'],
    hints: ['Z jedynki trygonometrycznej: $\\cos^{2} \\alpha = 1 - \\sin^{2} \\alpha$.', 'Dla kąta ostrego cosinus jest dodatni, więc bierzemy wartość nieujemną.'],
    solution: '$\\cos^{2} \\alpha = 1 - \\frac{1}{9} = \\frac{8}{9}$, więc $\\cos \\alpha = \\sqrt{\\frac{8}{9}} = \\frac{2\\sqrt{2}}{3}$ (wartość dodatnia, bo kąt ostry).',
    steps: ['Podstaw do $\\sin^{2} \\alpha + \\cos^{2} \\alpha = 1$.', 'Oblicz $\\cos^{2} \\alpha = \\frac{8}{9}$.', 'Wyznacz $\\cos \\alpha = \\frac{2\\sqrt{2}}{3}$.'],
  },
  {
    id: 'tg-08',
    topicSlug: 'trygonometria',
    lessonSlug: 'trygonometria-katy',
    type: 'numeric',
    difficulty: 3,
    points: 2,
    prompt: 'Kąt $150^{\\circ}$ wyrażony w miarze łukowej jest równy $\\frac{k}{6}\\pi$, gdzie $k$ jest liczbą naturalną. Podaj liczbę $k$.',
    answer: '5',
    acceptedAnswers: ['5'],
    tags: ['miara-lukowa'],
    skills: ['trygonometria-jedynka'],
    hints: ['Stopnie przeliczasz na radiany, mnożąc przez $\\frac{\\pi}{180}$.', '$150^{\\circ} = 150 \\cdot \\frac{\\pi}{180} = \\frac{150\\pi}{180}$'],
    solution: '$150^{\\circ} = 150 \\cdot \\frac{\\pi}{180} = \\frac{150\\pi}{180} = \\frac{5\\pi}{6} = \\frac{5}{6}\\pi$, więc $k = 5$.',
    steps: ['Zapisz przeliczenie: $150^{\\circ} \\cdot \\frac{\\pi}{180}$.', 'Skróć ułamek: $\\frac{150}{180} = \\frac{5}{6}$.', 'Odczytaj $k = 5$.'],
  },
  {
    id: 'tg-09',
    topicSlug: 'trygonometria',
    lessonSlug: 'trygonometria-tozsamosci',
    type: 'single_choice',
    level: 'extended',
    difficulty: 3,
    points: 2,
    prompt: 'Wyrażenie $\\sin 2\\alpha$ jest równe:',
    options: ['$2 \\sin \\alpha \\cos \\alpha$', '$\\sin \\alpha + \\cos \\alpha$', '$2 \\sin \\alpha$', '$\\sin^{2} \\alpha \\cos^{2} \\alpha$'],
    answer: '$2 \\sin \\alpha \\cos \\alpha$',
    tags: ['kat-podwojony', 'zamkniete', 'rozszerzenie'],
    skills: ['trygonometria-tozsamosci'],
    hints: ['Wzór na sinus kąta podwojonego wynika z wzoru na sinus sumy przy $\\beta = \\alpha$.', 'To jeden z najczęściej używanych wzorów na maturze rozszerzonej.'],
    solution: 'Ze wzoru $\\sin(\\alpha + \\beta) = \\sin \\alpha \\cos \\beta + \\cos \\alpha \\sin \\beta$ dla $\\beta = \\alpha$ otrzymujemy $\\sin 2\\alpha = 2 \\sin \\alpha \\cos \\alpha$.',
    steps: ['Zapisz wzór na sinus sumy.', 'Podstaw $\\beta = \\alpha$.', 'Zredukuj wyrazy podobne: $\\sin 2\\alpha = 2 \\sin \\alpha \\cos \\alpha$.'],
  },
  {
    id: 'tg-10',
    topicSlug: 'trygonometria',
    lessonSlug: 'trygonometria-tozsamosci',
    type: 'numeric',
    level: 'extended',
    difficulty: 4,
    points: 2,
    prompt: 'Kąt $\\alpha$ jest ostry oraz $\\sin \\alpha = \\frac{3}{5}$. Oblicz wartość wyrażenia $\\cos 2\\alpha$.',
    answer: '7/25',
    acceptedAnswers: ['7/25', '0,28', '0.28'],
    tags: ['kat-podwojony', 'jedynka-trygonometryczna', 'rozszerzenie'],
    skills: ['trygonometria-tozsamosci', 'trygonometria-jedynka'],
    hints: ['Użyj postaci $\\cos 2\\alpha = 1 - 2\\sin^{2} \\alpha$ — wystarczy znać sinus.', 'Podstaw: $1 - 2 \\cdot \\frac{9}{25}$.'],
    solution: '$\\cos 2\\alpha = 1 - 2\\sin^{2} \\alpha = 1 - 2 \\cdot \\frac{9}{25} = 1 - \\frac{18}{25} = \\frac{7}{25}$.',
    steps: ['Zapisz $\\cos 2\\alpha = 1 - 2\\sin^{2} \\alpha$.', 'Podstaw $\\sin \\alpha = \\frac{3}{5}$: $1 - \\frac{18}{25}$.', 'Oblicz $\\frac{7}{25}$.'],
  },
  {
    id: 'tg-11',
    topicSlug: 'trygonometria',
    lessonSlug: 'trygonometria-tozsamosci',
    type: 'open',
    level: 'extended',
    difficulty: 4,
    points: 3,
    prompt: 'Wykaż, że dla dowolnego kąta $\\alpha$ prawdziwa jest tożsamość $\\cos 2\\alpha = 1 - 2\\sin^{2} \\alpha$.',
    answer: 'Dowód: cos 2α = cos²α − sin²α = (1 − sin²α) − sin²α = 1 − 2sin²α',
    acceptedAnswers: ['Dowód: cos 2α = cos²α − sin²α = (1 − sin²α) − sin²α = 1 − 2sin²α'],
    tags: ['kat-podwojony', 'dowod', 'rozszerzenie'],
    skills: ['trygonometria-tozsamosci', 'trygonometria-jedynka'],
    hints: ['Zacznij od wzoru $\\cos 2\\alpha = \\cos^{2} \\alpha - \\sin^{2} \\alpha$.', 'Wykorzystaj jedynkę trygonometryczną, aby zastąpić $\\cos^{2} \\alpha$.'],
    solution: 'Z wzoru na kąt podwojony: $\\cos 2\\alpha = \\cos^{2} \\alpha - \\sin^{2} \\alpha$. Z jedynki trygonometrycznej $\\cos^{2} \\alpha = 1 - \\sin^{2} \\alpha$. Po podstawieniu: $\\cos 2\\alpha = (1 - \\sin^{2} \\alpha) - \\sin^{2} \\alpha = 1 - 2\\sin^{2} \\alpha$, co należało wykazać.',
    steps: ['Zapisz $\\cos 2\\alpha = \\cos^{2} \\alpha - \\sin^{2} \\alpha$.', 'Podstaw $\\cos^{2} \\alpha = 1 - \\sin^{2} \\alpha$ z jedynki.', 'Zredukuj: $1 - 2\\sin^{2} \\alpha$.'],
    rubric: [
      { criterion: 'Zapisanie wzoru $\\cos 2\\alpha = \\cos^{2} \\alpha - \\sin^{2} \\alpha$', points: 1 },
      { criterion: 'Zastosowanie jedynki trygonometrycznej $\\cos^{2} \\alpha = 1 - \\sin^{2} \\alpha$', points: 1 },
      { criterion: 'Poprawna redukcja i zakończenie dowodu', points: 1 },
    ],
  },
  {
    id: 'tg-12',
    topicSlug: 'trygonometria',
    lessonSlug: 'trygonometria-tozsamosci',
    type: 'open',
    level: 'extended',
    difficulty: 4,
    points: 3,
    prompt: 'Rozwiąż równanie $\\sin x = \\frac{\\sqrt{3}}{2}$ w przedziale $[0^{\\circ}, 360^{\\circ}]$. Podaj wszystkie rozwiązania.',
    answer: '60°, 120°',
    acceptedAnswers: ['60°, 120°', '60° i 120°', '60,120', '120,60', '{60°, 120°}'],
    tags: ['rownania-trygonometryczne', 'rozszerzenie'],
    skills: ['trygonometria-rownania'],
    hints: ['Znajdź jeden kąt z tabeli wartości: dla jakiego kąta sinus równa się $\\frac{\\sqrt{3}}{2}$?', 'Drugi kąt w pełnym obrocie ma tę samą wartość sinusa: $180^{\\circ} - x_{0}$.'],
    solution: 'Z tabeli: $\\sin 60^{\\circ} = \\frac{\\sqrt{3}}{2}$. Drugi kąt: $180^{\\circ} - 60^{\\circ} = 120^{\\circ}$. W przedziale $[0^{\\circ}, 360^{\\circ}]$ rozwiązania to $x \\in \\{60^{\\circ}, 120^{\\circ}\\}$.',
    steps: ['Wyznacz pierwszy kąt: $x_{1} = 60^{\\circ}$.', 'Znajdź drugi: $x_{2} = 180^{\\circ} - 60^{\\circ} = 120^{\\circ}$.', 'Sprawdź, że oba kąty leżą w przedziale, i zapisz zbiór rozwiązań.'],
    rubric: [
      { criterion: 'Wyznaczenie pierwszego kąta $60^{\\circ}$', points: 1 },
      { criterion: 'Wyznaczenie drugiego kąta $120^{\\circ}$ (symetria $180^{\\circ} - x$)', points: 1 },
      { criterion: 'Poprawny zapis pełnego zbioru rozwiązań', points: 1 },
    ],
  },
  {
    id: 'tg-13',
    topicSlug: 'trygonometria',
    lessonSlug: 'trygonometria-tozsamosci',
    type: 'single_choice',
    level: 'extended',
    difficulty: 3,
    points: 2,
    prompt: 'Rozwiązaniami równania $\\tan x = \\sqrt{3}$ w przedziale $[0^{\\circ}, 360^{\\circ}]$ są:',
    options: ['$60^{\\circ}$ oraz $240^{\\circ}$', '$30^{\\circ}$ oraz $210^{\\circ}$', '$60^{\\circ}$ oraz $120^{\\circ}$', '$45^{\\circ}$ oraz $225^{\\circ}$'],
    answer: '$60^{\\circ}$ oraz $240^{\\circ}$',
    tags: ['rownania-trygonometryczne', 'tangens', 'rozszerzenie'],
    skills: ['trygonometria-rownania'],
    hints: ['Dla tangensa rozwiązania powtarzają się co $180^{\\circ}$, a nie co $360^{\\circ}$.', 'Z tablicy: $\\tan 60^{\\circ} = \\sqrt{3}$.'],
    solution: '$\\tan 60^{\\circ} = \\sqrt{3}$, a tangens przyjmuje tę samą wartość dla kątów różniących się o $180^{\\circ}$: $60^{\\circ} + 180^{\\circ} = 240^{\\circ}$. Rozwiązania: $\\{60^{\\circ}, 240^{\\circ}\\}$.',
    steps: ['Znajdź pierwszy kąt: $x_{1} = 60^{\\circ}$.', 'Dodaj $180^{\\circ}$: $x_{2} = 240^{\\circ}$.', 'Sprawdź, że oba kąty leżą w przedziale.'],
  },
  {
    id: 'tg-14',
    topicSlug: 'trygonometria',
    lessonSlug: 'trygonometria-tozsamosci',
    type: 'open',
    level: 'extended',
    difficulty: 5,
    points: 5,
    prompt: 'Rozwiąż równanie $2 \\sin^{2} x - \\cos x - 1 = 0$ w przedziale $[0^{\\circ}, 360^{\\circ}]$. Podaj wszystkie rozwiązania.',
    answer: '60°, 180°, 300°',
    acceptedAnswers: ['60°, 180°, 300°', '60,180,300', '180, 60, 300', '{60°, 180°, 300°}'],
    tags: ['rownania-trygonometryczne', 'jedynka-trygonometryczna', 'kwadratowe', 'rozszerzenie'],
    skills: ['trygonometria-rownania', 'trygonometria-tozsamosci'],
    hints: ['Wykorzystaj $\\sin^{2} x = 1 - \\cos^{2} x$, aby równanie sprowadzić do jednej funkcji.', 'Po podstawieniu otrzymasz równanie kwadratowe względem $\\cos x$.', 'Pamiętaj: $\\cos x = -1$ daje jeden kąt, a $\\cos x = \\frac{1}{2}$ daje dwa.'],
    solution: 'Podstawiamy $\\sin^{2} x = 1 - \\cos^{2} x$: $2(1 - \\cos^{2} x) - \\cos x - 1 = 0$, czyli $-2\\cos^{2} x - \\cos x + 1 = 0$, stąd $2\\cos^{2} x + \\cos x - 1 = 0$. Pierwiastki: $\\cos x = \\frac{-1 \\pm 3}{4}$, czyli $\\cos x = \\frac{1}{2}$ albo $\\cos x = -1$. Dla $\\cos x = \\frac{1}{2}$: $x = 60^{\\circ}$ lub $x = 300^{\\circ}$. Dla $\\cos x = -1$: $x = 180^{\\circ}$. Rozwiązania: $x \\in \\{60^{\\circ}, 180^{\\circ}, 300^{\\circ}\\}$.',
    steps: ['Podstaw $\\sin^{2} x = 1 - \\cos^{2} x$ i uprość do $2\\cos^{2} x + \\cos x - 1 = 0$.', 'Rozwiąż równanie kwadratowe: $\\cos x = \\frac{1}{2}$ lub $\\cos x = -1$.', 'Dla $\\frac{1}{2}$ znajdź $60^{\\circ}$ i $300^{\\circ}$; dla $-1$ tylko $180^{\\circ}$.', 'Zapisz pełny zbiór: $\\{60^{\\circ}, 180^{\\circ}, 300^{\\circ}\\}$.'],
    rubric: [
      { criterion: 'Sprowadzenie równania do jednej funkcji za pomocą jedynki trygonometrycznej', points: 2 },
      { criterion: 'Rozwiązanie równania kwadratowego: $\\cos x = \\frac{1}{2}$ lub $\\cos x = -1$', points: 2 },
      { criterion: 'Poprawny zapis pełnego zbioru rozwiązań w przedziale', points: 1 },
    ],
  },
]
