import type { ContentTask } from '@/content/types'

export const wielomianyTasks: ContentTask[] = [
  { id: 'wm-01', topicSlug: 'wielomiany', lessonSlug: 'wielomiany-rozklad', type: 'numeric', difficulty: 1, points: 1, prompt: 'Rozkład $x^2-16$ na czynniki.', answer: '(x-4)(x+4)', tags: ['rozklad'], skills: ['wielomiany-rozkladanie'], hints: ['Zastosuj różnicę kwadratów.'], solution: '$x^2-16=(x-4)(x+4)$.', steps: ['Rozpoznaj $a^2-b^2$.', 'Zapisz $(x-4)(x+4)$.'] },
  { id: 'wm-02', topicSlug: 'wielomiany', lessonSlug: 'wielomiany-rozklad', type: 'numeric', difficulty: 1, points: 1, prompt: 'Rozkład $4x^2+12x+9$.', answer: '(2x+3)^2', tags: ['kwadrat'], skills: ['wielomiany-rozkladanie'], hints: ['Szukaj wzoru $(ax+b)^2$.'], solution: '$4x^2+12x+9=(2x+3)^2$.', steps: ['Zauważ że $4x^2=(2x)^2$ i $9=3^2$.', 'Zapisz kwadrat sumy.'] },
  { id: 'wm-03', topicSlug: 'wielomiany', lessonSlug: 'wielomiany-rozklad', type: 'numeric', difficulty: 2, points: 1, prompt: 'Wyznacz miejsca zerowe wielomianu $x^2-5x+6$.', answer: '2, 3', tags: ['zera'], skills: ['wielomiany-rozkladanie'], hints: ['Rozkład na $(x-2)(x-3)$.'], solution: '$x^2-5x+6=(x-2)(x-3)$, więc zera to $2$ i $3$.', steps: ['Rozkład wielomian.', 'Zapisz czynniki równe zeru.'] },
  { id: 'wm-04', topicSlug: 'wielomiany', lessonSlug: 'wielomiany-rozklad', type: 'single_choice', difficulty: 2, points: 1, prompt: 'Który zapis jest rozkładem $3x^2-12$?', options: ['$(3x-2)(x+2)$', '$3(x-2)(x+2)$', '$(3x-2)^2$', '$3x(x-4)$'], answer: '$3(x-2)(x+2)$', tags: ['rozklad'], skills: ['wielomiany-rozkladanie'], hints: ['Najpierw wyłóż $3$.', 'Zastosuj różnicę kwadratów.'], solution: '$3x^2-12=3(x^2-4)=3(x-2)(x+2)$.', steps: ['Wyłóż wspólny czynnik $3$.', 'Rozkład różnicę kwadratów.'] },
  { id: 'wm-05', topicSlug: 'wielomiany', lessonSlug: 'wielomiany-dzielenie', type: 'numeric', difficulty: 2, points: 1, prompt: 'Oblicz resztę z dzielenia $x^2+3x-4$ przez $x-1$.', answer: '0', tags: ['reszta'], skills: ['wielomiany-dzielenie'], hints: ['Zastosuj $P(1)$.'], solution: '$P(1)=1+3-4=0$, więc reszta wynosi $0$.', steps: ['Podstaw $x=1$.', 'Oblicz $P(1)$.'] },
  { id: 'wm-06', topicSlug: 'wielomiany', lessonSlug: 'wielomiany-dzielenie', type: 'numeric', difficulty: 3, points: 2, prompt: 'Wykonaj dzielenie $x^2+5x+6$ przez $x+2$.', answer: 'x+3', tags: ['dzielenie'], skills: ['wielomiany-dzielenie'], hints: ['Szukaj ilorazu $x+3$.', 'Sprawdź iloczyn.'], solution: '$(x+2)(x+3)=x^2+5x+6$, więc iloraz to $x+3$.', steps: ['Dopasuj wyrazy.', 'Sprawdź iloczyn.'] },
  { id: 'wm-07', topicSlug: 'wielomiany', lessonSlug: 'wielomiany-dzielenie', type: 'open', difficulty: 3, points: 3, prompt: 'Udowodnij tożsamość $a^2+14a+49=(a+7)^2$.', answer: 'a^2+14a+49=(a+7)^2', tags: ['dowod'], skills: ['wielomiany-rozkladanie'], hints: ['Zastosuj wzór $(a+b)^2$.', 'Porównaj wyrażenia.'], solution: 'Zgodnie ze wzorem $(a+b)^2=a^2+2ab+b^2$ dla $b=7$ mamy $a^2+2a\\cdot7+7^2=a^2+14a+49$.', steps: ['Zapisz wzór kwadratu sumy.', 'Podstaw $b=7$.', 'Otrzymaj tożsamość.'], rubric: [{ criterion: 'Wzór kwadratu sumy', points: 1 }, { criterion: 'Podstawienie $b=7$', points: 1 }, { criterion: 'Poprawny wniosek', points: 1 }] },
  { id: 'wm-08', topicSlug: 'wielomiany', lessonSlug: 'wielomiany-rozklad', type: 'open', difficulty: 3, points: 3, prompt: 'Rozwiąż $x^2-7x+12=0$ przez rozkład na czynniki.', answer: '3, 4', tags: ['rownanie'], skills: ['wielomiany-rozkladanie'], hints: ['Szukaj liczb o sumie $7$ i iloczynie $12$.'], solution: '$x^2-7x+12=(x-3)(x-4)$, zatem $x=3$ lub $x=4$.', steps: ['Rozkład wielomian.', 'Wyznacz miejsca zerowe.'], rubric: [{ criterion: 'Poprawny rozkład', points: 1 }, { criterion: 'Rozwiązanie czynników', points: 1 }, { criterion: 'Zapis odpowiedzi', points: 1 }] },
  { id: 'wm-09', topicSlug: 'wielomiany', lessonSlug: 'wielomiany-dzielenie', type: 'open', difficulty: 4, points: 4, prompt: 'Wyznacz resztę z dzielenia $x^4-2x^3+5$ przez $x-2$.', answer: '5', tags: ['reszta'], skills: ['wielomiany-dzielenie'], hints: ['Skorzystaj z twierdzenia o reszcie.', 'Oblicz wartość wielomianu dla $x=2$.'], solution: '$P(2)=2^4-2\\cdot2^3+5=16-16+5=5$. Reszta wynosi $5$.', steps: ['Zastosuj $P(2)$.', 'Oblicz $16-16+5$.', 'Wynik to $5$.'], rubric: [{ criterion: 'Zastosowanie twierdzenia o reszcie', points: 1 }, { criterion: 'Obliczenie wartości wielomianu', points: 2 }, { criterion: 'Poprawna reszta', points: 1 }] },
  { id: 'wm-10', topicSlug: 'wielomiany', lessonSlug: 'wielomiany-rozklad', type: 'open', difficulty: 4, points: 4, prompt: 'Rozkład $x^3-4x$ i wyznacz jego miejsca zerowe.', answer: '0, -2, 2', tags: ['rozklad', 'zera'], skills: ['wielomiany-rozkladanie'], hints: ['Wyłóż $x$.', 'W nawiasie rozpoznaj różnicę kwadratów.'], solution: '$x^3-4x=x(x^2-4)=x(x-2)(x+2)$, zatem zera to $0,-2,2$.', steps: ['Wyłóż $x$.', 'Rozkład $x^2-4$.', 'Wyznacz zera czynników.'], rubric: [{ criterion: 'Wyłonienie czynnika $x$', points: 1 }, { criterion: 'Rozkład różnicy kwadratów', points: 2 }, { criterion: 'Poprawne miejsca zerowe', points: 1 }] },
]
