import type { ContentTask } from '@/content/types'

export const wymierneTasks: ContentTask[] = [
  { id: 'wy-01', topicSlug: 'wymierne', lessonSlug: 'wymierne-dziedzina', type: 'text', difficulty: 1, points: 1, prompt: 'Wyznacz dziedzinę funkcji $f(x)=\\frac{x+1}{x-2}$.', answer: 'R\\setminus\\{2\\}', tags: ['dziedzina'], skills: ['wymierne-dziedzina'], hints: ['Mianownik nie może być zerowy.', 'Rozwiąż $x-2=0$.'], solution: '$x-2=0$ dla $x=2$, więc $D_f=\\mathbb R\\setminus\\{2\\}$.', steps: ['Wyznacz zero mianownika.', 'Odejmij tę wartość od $\\mathbb R$.'] },
  { id: 'wy-02', topicSlug: 'wymierne', lessonSlug: 'wymierne-dziedzina', type: 'numeric', difficulty: 1, points: 1, prompt: 'Wyznacz najmniejsze miejsce zerowe $f(x)=\\frac{x-3}{x+1}$.', answer: '3', tags: ['zero'], skills: ['wymierne-zera'], hints: ['Licznik musi być zerowy.', 'Sprawdź, czy punkt należy do dziedziny.'], solution: 'Licznik zeruje się dla $x=3$. Ponieważ $3\\neq-1$, jest to miejsce zerowe.', steps: ['Rozwiąż $x-3=0$.', 'Sprawdź mianownik.'] },
  { id: 'wy-03', topicSlug: 'wymierne', lessonSlug: 'wymierne-dziedzina', type: 'single_choice', difficulty: 2, points: 1, prompt: 'Która liczba nie należy do dziedziny $f(x)=\\frac{1}{x^2-4}$?', options: ['$0$', '$2$', '$3$', '$-1$'], answer: '$2$', tags: ['dziedzina'], skills: ['wymierne-dziedzina'], hints: ['Zrób mianownik równy zero.'], solution: '$x^2-4=(x-2)(x+2)$ zeruje się dla $x=2$ i $x=-2$, więc $2$ nie należy do dziedziny.', steps: ['Rozkład mianownik.', 'Wskaż jego pierwiastek.'] },
  { id: 'wy-04', topicSlug: 'wymierne', lessonSlug: 'wymierne-dziedzina', type: 'numeric', difficulty: 2, points: 1, prompt: 'Dla $f(x)=\\frac{x^2-9}{x-3}$ uproszczona wartość $f(x)$ dla $x\\neq3$ jest równa:', answer: 'x+3', tags: ['skracanie'], skills: ['wymierne-zera'], hints: ['Rozkład liczniki i mianownika.', 'Skróć wspólny czynnik, pamiętając o $x\\neq3$.'], solution: '$\\frac{(x-3)(x+3)}{x-3}=x+3$ dla $x\\neq3$.', steps: ['Rozkład oba wyrażenia.', 'Skróć $x-3$.'] },
  { id: 'wy-05', topicSlug: 'wymierne', lessonSlug: 'wymierne-asymptoty', type: 'text', difficulty: 2, points: 1, prompt: 'Wyznacz pionową asymptotę funkcji $f(x)=\\frac{2}{x-4}$.', answer: 'x=4', tags: ['asymptota'], skills: ['wymierne-asymptoty'], hints: ['Pierwiastek mianownika jest kandydatem na asymptotę pionową.'], solution: 'Mianownik zeruje się dla $x=4$, więc asymptotą pionową jest $x=4$.', steps: ['Rozwiąż $x-4=0$.', 'Zapisz prostą.'] },
  { id: 'wy-06', topicSlug: 'wymierne', lessonSlug: 'wymierne-asymptoty', type: 'single_choice', difficulty: 2, points: 1, prompt: 'Funkcja $f(x)=\\frac{3}{x^2+1}$ ma asymptotę poziomą:', options: ['$y=0$', '$y=3$', '$y=1$', 'nie ma asymptoty poziomej'], answer: '$y=0$', tags: ['asymptota'], skills: ['wymierne-asymptoty'], hints: ['Stopień mianownika jest większy niż licznika.'], solution: 'Gdy $|x|\\to\\infty$, ułamek dąży do $0$, więc asymptotą poziomą jest $y=0$.', steps: ['Porównaj stopnie.', 'Wyznacz granicę.'] },
  { id: 'wy-07', topicSlug: 'wymierne', lessonSlug: 'wymierne-dziedzina', type: 'open', difficulty: 3, points: 3, prompt: 'Wyznacz dziedzinę $f(x)=\\frac{x-1}{(x-2)(x+3)}$.', answer: 'R\\setminus\\{2,-3\\}', tags: ['dziedzina'], skills: ['wymierne-dziedzina'], hints: ['Mianownik musi być różny od zera.', 'Rozwiąż oba czynniki.'], solution: 'Mianownik zeruje się dla $x=2$ lub $x=-3$, zatem $D_f=\\mathbb R\\setminus\\{2,-3\\}$.', steps: ['Zapisz warunek mianownika.', 'Odejmij oba wykluczone punkty.'], rubric: [{ criterion: 'Warunek mianownika', points: 1 }, { criterion: 'Poprawne wyłączenia', points: 1 }, { criterion: 'Zapis dziedziny', points: 1 }] },
  { id: 'wy-08', topicSlug: 'wymierne', lessonSlug: 'wymierne-asymptoty', type: 'open', difficulty: 4, points: 4, prompt: 'Określ miejsca zerowe i asymptoty poziome funkcji $f(x)=\\frac{2x+1}{x+4}$.', answer: 'zero -1/2; asymptota y=2', tags: ['zera', 'asymptota'], skills: ['wymierne-zera', 'wymierne-asymptoty'], hints: ['Zero: licznik=0.', 'Stopnie są równe, więc granica jest ilorazem współczynników.'], solution: '$2x+1=0$ daje $x=-\\frac12$. Ponieważ stopnie są równe, asymptota pozioma to $y=2$.', steps: ['Rozwiąż licznik.', 'Porównaj stopnie i współczynniki.'], rubric: [{ criterion: 'Miejsce zerowe', points: 2 }, { criterion: 'Asymptota pozioma', points: 1 }, { criterion: 'Uzasadnienie', points: 1 }] },
  { id: 'wy-09', topicSlug: 'wymierne', lessonSlug: 'wymierne-dziedzina', type: 'single_choice', difficulty: 3, points: 1, prompt: 'Wartość $x=2$ jest miejscem zerowym uproszczonej funkcji, ale nie należy do jej pierwotnej dziedziny, jeśli wyjściowa postać to:', options: ['$\\frac{x-2}{x-2}$', '$\\frac{1}{x-2}$', '$\\frac{x+2}{x-2}$', '$\\frac{x^2-4}{x+2}$'], answer: '$\\frac{x-2}{x-2}$', tags: ['skracanie'], skills: ['wymierne-zera'], hints: ['Szukaj wspólnego czynnika $x-2$.'], solution: 'W $\\frac{x-2}{x-2}$ punkt $2$ jest wykluczony przez pierwotny mianownik, choć po skróceniu otrzymujemy $1$.', steps: ['Sprawdź mianownik w pierwotnej postaci.', 'Porównaj ze skróconą.' ] },
  { id: 'wy-10', topicSlug: 'wymierne', lessonSlug: 'wymierne-asymptoty', type: 'open', difficulty: 4, points: 4, prompt: 'Dla $f(x)=\\frac{x^2}{x^2+4}$ wyznacz wszystkie asymptoty i miejsca zerowe.', answer: 'zero 0; asymptota y=1', tags: ['asymptota', 'zero'], skills: ['wymierne-zera', 'wymierne-asymptoty'], hints: ['Zero: $x^2=0$.', 'Stopnie są równe, więc granica to 1.'], solution: 'Funkcja ma zero $x=0$, a ponieważ granica na nieskończoności wynosi $1$, asymptotą poziomą jest $y=1$.', steps: ['Wyznacz zero licznika.', 'Oblicz granicę przez współczynnik dominujący.'] , rubric: [{ criterion: 'Zero funkcji', points: 1 }, { criterion: 'Granica na nieskończoności', points: 2 }, { criterion: 'Wniosek o asymptocie', points: 1 }] },
]
