import { z } from 'zod'

export const questionTypeSchema = z.enum(['numeric', 'text', 'single_choice', 'multiple_choice', 'open', 'proof'])
export const generationRequestSchema = z.object({ topic: z.string().min(2).max(120), subtopic: z.string().max(120).optional(), level: z.enum(['basic', 'extended']), difficulty: z.number().int().min(1).max(5), questionType: questionTypeSchema, count: z.number().int().min(1).max(10).default(1), estimatedMinutes: z.number().int().min(1).max(180).optional(), skills: z.array(z.string().max(80)).max(12).default([]), mode: z.enum(['standard', 'personalized', 'similar', 'plan']).default('standard'), parentQuestionId: z.string().uuid().optional(), context: z.string().max(4000).optional() })
export const generatedQuestionSchema = z.object({ title: z.string().min(3).max(180), questionText: z.string().min(10).max(8000), level: z.enum(['basic', 'extended']), topic: z.string().min(2), subtopic: z.string().optional(), difficulty: z.number().int().min(1).max(5), questionType: questionTypeSchema, estimatedMinutes: z.number().int().min(1).max(180), points: z.number().int().min(1).max(20), answer: z.string().min(1).max(2000), solution: z.string().min(10).max(12000), hints: z.array(z.string().min(3).max(500)).min(1).max(4), skills: z.array(z.string().max(80)).max(12), tags: z.array(z.string().max(50)).max(12), choices: z.array(z.string().max(500)).max(8).optional() })
export type GenerationRequest = z.infer<typeof generationRequestSchema>
export type GeneratedQuestion = z.infer<typeof generatedQuestionSchema>
export const generatedQuestionJsonSchema = { type: 'object', additionalProperties: false, required: ['title','questionText','level','topic','difficulty','questionType','estimatedMinutes','points','answer','solution','hints','skills','tags'], properties: { title: { type: 'string' }, questionText: { type: 'string' }, level: { type: 'string', enum: ['basic','extended'] }, topic: { type: 'string' }, subtopic: { type: 'string' }, difficulty: { type: 'integer', minimum: 1, maximum: 5 }, questionType: { type: 'string' }, estimatedMinutes: { type: 'integer' }, points: { type: 'integer' }, answer: { type: 'string' }, solution: { type: 'string' }, hints: { type: 'array', items: { type: 'string' } }, skills: { type: 'array', items: { type: 'string' } }, tags: { type: 'array', items: { type: 'string' } } } } as const
export function normalizeQuestion(question: GeneratedQuestion, request: GenerationRequest): GeneratedQuestion { return { ...question, topic: request.topic, subtopic: request.subtopic ?? question.subtopic, level: request.level, difficulty: request.difficulty, questionType: request.questionType, estimatedMinutes: request.estimatedMinutes ?? question.estimatedMinutes, points: Math.max(1, Math.min(20, question.points)), hints: question.hints.slice(0, 4), skills: [...new Set([...request.skills, ...question.skills])].slice(0, 12), tags: [...new Set(question.tags)].slice(0, 12) } }
